---
# remove_lambda_account_setup.yml
# Lambda APIアカウントレベル設定削除プレイブック
#
# 使用方法:
#   ansible-playbook playbooks/lambda/remove/remove_lambda_account_setup.yml

- name: Remove Lambda Account Setup
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    env_name: "{{ env | default('dev') }}"

  pre_tasks:
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"

    - name: Set required variables
      ansible.builtin.set_fact:
        project_name: "{{ projects.lambda_api.name }}"

    - name: Display operation info
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda Account Setup Removal
          ==========================================
          Environment: {{ env_name }}
          Project: {{ project_name }}-account-setup
          Region: {{ aws_region }}
          ==========================================

  roles:
    - aws_setup
    - pulumi_helper

  tasks:
    - name: Execute Lambda Account Setup removal
      ansible.builtin.include_role:
        name: lambda_account_setup
      vars:
        operation: "destroy"
        
  post_tasks:
    - name: Display results
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda Account Setup Removal Complete
          ==========================================
          Lambda account setup has been removed.
          Note: This may affect API Gateway logging functionality.