---
# Lambda APIセキュリティグループのデプロイタスク

- name: Display security deployment information
  ansible.builtin.debug:
    msg: "Deploying Lambda API Security Infrastructure for {{ env_name }} environment"

# Pulumiデプロイ
- name: Deploy Security Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize security stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-security"
        stack_name: "{{ env_name }}"
    

    # Pulumiプレビュー
    - name: Preview security deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-security"
      when: preview_only | default(false) | bool
    
    # Pulumiデプロイ
    - name: Deploy security stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-security"
      when: not preview_only | default(false) | bool
    
    # デプロイ成功を示す変数設定
    - name: Set security deployment status
      ansible.builtin.set_fact:
        security_deployed: true
      when: not preview_only | default(false) | bool
    
    # セキュリティグループ情報の表示
    - name: Display security deployment summary
      ansible.builtin.debug:
        msg: "Lambda API Security Infrastructure deployed successfully for {{ env_name }} environment"
      when: not preview_only | default(false) | bool
  
  rescue:
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Lambda API security deployment failed."
