---
# Lambda APIセキュリティグループのデプロイタスク

# SSMからPhase設定を取得
- name: Get database security groups flag from SSM
  ansible.builtin.include_role:
    name: ssm_parameter_store
    tasks_from: get_parameter
  vars:
    parameter_name: "/{{ project_name }}/{{ env_name }}/phase/database-sg-enabled"
    store_as: "database_sg_param"
    default_value: "false"
    ssm_parameter_store_fail_on_missing: false

- name: Set database security groups flag
  ansible.builtin.set_fact:
    enable_database: "{{ ssm_parameter_store_database_sg_param | default('false') | bool }}"

- name: Display security deployment information
  ansible.builtin.debug:
    msg: "Deploying Lambda API Security Infrastructure for {{ env_name }} environment"

# Pulumiデプロイ
- name: Deploy Security Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize security stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-security"
        stack_name: "{{ env_name }}"
    
    - name: Configure security stack - AWS region
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-security"
        config_key: "aws:region"
        config_value: "{{ aws_region_name }}"

    - name: Configure security stack - project name
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-security"
        config_key: "{{ security_project_name }}:projectName"
        config_value: "{{ project_name }}"

    - name: Configure security stack - network stack name
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-security"
        config_key: "{{ security_project_name }}:networkStackName"
        config_value: "{{ network_project_name }}"

    - name: Configure security stack - enable database security groups
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-security"
        config_key: "{{ security_project_name }}:enableDatabaseSecurityGroups"
        config_value: "{{ enable_database | string | lower }}"
    
    # Pulumiプレビュー
    - name: Preview security deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-security"
      when: preview_only | default(false) | bool
    
    # Pulumiデプロイ
    - name: Deploy security stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-security"
      when: not preview_only | default(false) | bool
    
    # デプロイ成功を示す変数設定
    - name: Set security deployment status
      ansible.builtin.set_fact:
        security_deployed: true
      when: not preview_only | default(false) | bool
    
    # セキュリティグループ情報の表示
    - name: Display security deployment summary
      ansible.builtin.debug:
        msg: "Lambda API Security Infrastructure deployed successfully for {{ env_name }} environment"
      when: not preview_only | default(false) | bool
  
  rescue:
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Lambda API security deployment failed."
