---
# Jenkins設定タスク - jenkins_applicationと同様のアプローチ

- name: Display jenkins configuration information
  ansible.builtin.debug:
    msg: "Configuring Jenkins Controller for {{ env_name }} environment"

# JenkinsインスタンスIDの取得（Parameter Storeから）
- name: Get Jenkins instance ID from SSM Parameter Store
  ansible.builtin.include_role:
    name: ssm_parameter_store
    tasks_from: get_parameter
  vars:
    parameter_name: "/jenkins-infra/{{ env_name }}/controller/instance-id"
    store_as: "jenkins_instance_id"

- name: Verify Jenkins instance ID
  ansible.builtin.fail:
    msg: "Invalid Jenkins instance ID format: {{ jenkins_instance_id }}"
  when: not (jenkins_instance_id | regex_search('^i-[a-f0-9]+$'))

# EFSファイルシステムIDの取得 - SSM Parameter Storeから優先的に取得
- name: Get EFS file system ID from Parameter Store
  when: efs_file_system_id is not defined or efs_file_system_id == ""
  ansible.builtin.include_role:
    name: ssm_parameter_store
    tasks_from: get_parameter
  vars:
    parameter_name: "/jenkins-infra/{{ env_name }}/storage/efs-file-system-id"
    store_as: "efs_file_system_id"

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true

# 設定Pulumiスタックのデプロイ
- name: Deploy Jenkins Configuration with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize config stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-config"
        stack_name: "{{ env_name }}"
    
    - name: Configure config stack - AWS region
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-config"
        config_key: "aws:region"
        config_value: "{{ aws_region_name }}"
    
    
    # Pulumiプレビュー
    - name: Preview config deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-config"
    
    # Pulumiデプロイ
    - name: Deploy config stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-config"
    
    # SSMドキュメント名の取得（SSMパラメータから）
    - name: Get update repo document name from SSM Parameter Store
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/config/update-repo-document-name"
        store_as: "update_repo_document_name"
    
    - name: Get execute script document name from SSM Parameter Store
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/config/execute-script-document-name"
        store_as: "execute_script_document_name"
    
  
  rescue:
    - name: Display error on config deployment
      ansible.builtin.debug:
        msg: "Failed to deploy Jenkins configuration resources. See error details above."
      
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Jenkins configuration deployment failed."

# インスタンスの設定処理
- name: Wait for SSM agent to be operational
  ansible.builtin.pause:
    seconds: 30
  when: not ansible_check_mode

# jenkins_applicationと同様のアプローチで、スクリプトを順次実行
- name: Execute Jenkins configuration scripts
  block:
    # ステップ0: Gitリポジトリの更新
    - name: Update Git repository
      ansible.builtin.include_tasks: execute_ssm_command.yml
      vars:
        ssm_document_name: "{{ update_repo_document_name }}"
        ssm_parameters: "ProjectName={{ project_name }},Environment={{ env_name }},GitBranch={{ git_branch }},GitRepo={{ git_repo }}"
        ssm_comment: "Updating Git repository"
        instance_id: "{{ jenkins_instance_id }}"
    
    # ステップ1: EFSマウント
    - name: Mount EFS
      ansible.builtin.include_tasks: execute_ssm_command.yml
      vars:
        ssm_document_name: "{{ execute_script_document_name }}"
        ssm_parameters: "ScriptPath=scripts/jenkins/shell/controller-mount-efs.sh,ScriptArgs={{ efs_file_system_id }} {{ aws_region_name }}"
        ssm_comment: "Mounting EFS"
        instance_id: "{{ jenkins_instance_id }}"
    
    # ステップ2: Jenkinsインストール
    - name: Install Jenkins
      ansible.builtin.include_tasks: execute_ssm_command.yml
      vars:
        ssm_document_name: "{{ execute_script_document_name }}"
        ssm_parameters: "ScriptPath=scripts/jenkins/shell/controller-install.sh,ScriptArgs={{ jenkins_version }} {{ jenkins_color }}"
        ssm_comment: "Installing Jenkins"
        instance_id: "{{ jenkins_instance_id }}"
    
    # ステップ3: Jenkins設定
    - name: Configure Jenkins
      ansible.builtin.include_tasks: execute_ssm_command.yml
      vars:
        ssm_document_name: "{{ execute_script_document_name }}"
        ssm_parameters: "ScriptPath=scripts/jenkins/shell/controller-configure.sh,ScriptArgs={{ recovery_mode | ternary('recovery', 'normal') }} {{ jenkins_color }}"
        ssm_comment: "Configuring Jenkins"
        instance_id: "{{ jenkins_instance_id }}"
    
    # ステップ4: Jenkins起動
    - name: Start Jenkins
      ansible.builtin.include_tasks: execute_ssm_command.yml
      vars:
        ssm_document_name: "{{ execute_script_document_name }}"
        ssm_parameters: "ScriptPath=scripts/jenkins/shell/controller-startup.sh,ScriptArgs={{ jenkins_color }}"
        ssm_comment: "Starting Jenkins"
        instance_id: "{{ jenkins_instance_id }}"

# 設定結果のサマリー表示
- name: Display Jenkins setup completion status
  ansible.builtin.debug:
    msg: "Jenkins Controller setup completed successfully for {{ env_name }} environment"
