---
# Lambda API VPCエンドポイントのデプロイタスク

- name: Display VPC endpoints deployment information
  ansible.builtin.debug:
    msg: "Deploying Lambda API VPC Endpoints for {{ env_name }} environment"

# Pulumiデプロイ
- name: Deploy VPC Endpoints with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize VPC endpoints stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-vpce"
        stack_name: "{{ env_name }}"
    
    - name: Configure VPC endpoints stack - AWS region
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-vpce"
        config_key: "aws:region"
        config_value: "{{ aws_region_name }}"
    
    # Pulumiプレビュー
    - name: Preview VPC endpoints deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-vpce"
      when: preview_only | default(false) | bool
    
    # Pulumiデプロイ
    - name: Deploy VPC endpoints stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-vpce"
      when: not preview_only | default(false) | bool
    
    # デプロイ成功を示す変数設定
    - name: Set VPC endpoints deployment status
      ansible.builtin.set_fact:
        vpce_deployed: true
      when: not preview_only | default(false) | bool
    
    # VPCエンドポイント情報の表示
    - name: Display VPC endpoints deployment summary
      ansible.builtin.debug:
        msg: "Lambda API VPC Endpoints deployed successfully for {{ env_name }} environment"
      when: not preview_only | default(false) | bool
  
  rescue:
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Lambda API VPC endpoints deployment failed."
