---
# ============================================================
# Ansible グループ共通変数定義
# ============================================================
# このファイルには、すべての環境とロールで共通して使用される変数を定義します。
# 環境固有の設定は、dev.yml, staging.yml, prod.yml で上書きしてください。

# ============================================================
# 基本設定
# ============================================================

# デフォルト環境名（環境別ファイルで上書き）
env_name: "dev"

# 操作モード（deploy/destroy）
operation: "deploy"

# AWS デフォルトリージョン
aws_region: "ap-northeast-1"

# ============================================================
# パス定義
# ============================================================

# スクリプトディレクトリへのパス（15以上のロールで使用）
scripts_dir: "{{ inventory_dir }}/../../scripts"

# Pulumiプロジェクトディレクトリへのパス（15以上のロールで使用）
pulumi_path: "{{ inventory_dir }}/../../pulumi"

# AWS認証スクリプトのパス
aws_credentials_script_path: "{{ scripts_dir }}/aws/setup-aws-credentials.sh"

# ============================================================
# Pulumi設定
# ============================================================

pulumi:
  # バックエンドタイプ（"cloud" または "s3"）
  backend_type: "s3"

  # S3バックエンド設定
  s3:
    # S3バケット名（CloudFormationで作成されたバケット名を指定）
    bucket: ""  # 空の場合はSSMパラメータストアから取得
    region: "ap-northeast-1"

# ============================================================
# Jenkins インフラストラクチャ設定
# ============================================================

infra:
  # プロジェクト名
  project_name: "jenkins-infra"

  # AWS設定
  aws:
    default_region: "ap-northeast-1"

# ============================================================
# Lambda API インフラストラクチャ設定
# ============================================================

lambda_api_infra:
  # プロジェクト名
  project_name: "lambda-api"

  # AWS設定
  aws:
    default_region: "ap-northeast-1"