---
# ============================================================
# Ansible グループ共通変数定義
# ============================================================
# このファイルには、すべての環境とロールで共通して使用される変数を定義します。
# 環境固有の設定は、dev.yml, staging.yml, prod.yml で上書きしてください。

# ============================================================
# 基本設定
# ============================================================

# デフォルト環境名（環境別ファイルで上書き）
env_name: "dev"

# AWS デフォルトリージョン
aws_region: "ap-northeast-1"

# ============================================================
# パス定義
# ============================================================

# スクリプトディレクトリへのパス（15以上のロールで使用）
scripts_dir: "{{ inventory_dir }}/../../scripts"

# Pulumiプロジェクトディレクトリへのパス（15以上のロールで使用）
pulumi_path: "{{ inventory_dir }}/../../pulumi"

# AWS認証スクリプトのパス
aws_credentials_script_path: "{{ scripts_dir }}/aws/setup-aws-credentials.sh"

# ============================================================
# Pulumi設定
# ============================================================

# S3バックエンド固定
# S3バケット名はSSMパラメータストア(/bootstrap/pulumi/s3bucket-name)から自動取得
# リージョンはaws_regionパラメータを使用

# ============================================================
# プロジェクト設定
# ============================================================

projects:
  jenkins:
    name: "jenkins-infra"
  lambda_api:
    name: "lambda-api"