---
# インフラストラクチャ共通設定
#
# このファイルには、すべての環境とロールで共通して使用される変数を定義します。
# 環境固有の設定は、dev.yml, staging.yml, prod.yml で上書きしてください。

# ============================================================
# パスとディレクトリ設定（共通変数）
# ============================================================
# スクリプトディレクトリへのパス（15以上のロールで使用）
scripts_dir: "{{ inventory_dir }}/../../scripts"
# Pulumiプロジェクトディレクトリへのパス（15以上のロールで使用）
pulumi_path: "{{ inventory_dir }}/../../pulumi"
# AWS認証スクリプトのパス
aws_credentials_script_path: "{{ scripts_dir }}/aws/setup-aws-credentials.sh"

# デフォルト環境名（環境別ファイルで上書き）
env_name: "dev"

# AWS デフォルトリージョン
aws_region: "ap-northeast-1"

# 操作モード（deploy/destroy）
operation: "deploy"

# ============================================================
# Pulumi設定
# ============================================================

# Pulumi バックエンド設定
pulumi:
  # バックエンドタイプ（"cloud" または "s3"）
  backend_type: "s3"
  
  # S3バックエンド設定
  s3:
    # S3バケット名（CloudFormationで作成されたバケット名を指定）
    bucket: ""  # 空の場合はSSMパラメータストアから取得
    region: "ap-northeast-1"
  

# ============================================================
# Jenkins インフラストラクチャ設定
# ============================================================

# プロジェクト識別子
infra:
  # メインのプロジェクト名（変数展開に使用）
  project_name: "jenkins-infra"
  
  # Pulumiプロジェクト名（スタック参照に使用）
  pulumi:
    network_project: "jenkins-network"
    security_project: "jenkins-security"
    nat_project: "jenkins-nat"
    storage_project: "jenkins-storage"
    loadbalancer_project: "jenkins-loadbalancer"
    controller_project: "jenkins-controller"
    agent_project: "jenkins-agent"
    config_project: "jenkins-config"
    application_project: "jenkins-application"

  # AWS設定
  aws:
    default_region: "ap-northeast-1"

# ============================================================
# Lambda インフラストラクチャ設定
# ============================================================

# Lambda API プロジェクト設定
lambda_api_infra:
  # メインのプロジェクト名
  project_name: "lambda-api"
  
  # Pulumiプロジェクト名
  pulumi:
    network_project: "lambda-network"
    security_project: "lambda-security"
    vpce_project: "lambda-vpce"
    nat_project: "lambda-nat"
    functions_project: "lambda-functions"
    api_gateway_project: "lambda-api-gateway"

  # AWS設定
  aws:
    default_region: "ap-northeast-1"

# ============================================================
# Jenkins プロジェクト設定
# ============================================================

# Jenkins設定
jenkins:
  version: "latest"
  color: "blue"
  recovery_mode: false

  # Git設定
  git:
    repo: "https://github.com/tielec/infrastructure-as-code.git"
    branch: "main"

