---
# deploy_lambda_api_gateway.yml
# API Gatewayデプロイメントプレイブック（デプロイ用）
# 
# 使用方法:
#   ansible-playbook playbooks/lambda/deploy/deploy_lambda_api_gateway.yml -e "env=dev"

- name: Deploy API Gateway
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    env_name: "{{ env | default('dev') }}"
    preview_only: "{{ preview | default(false) }}"
    
  pre_tasks:
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"
    
    - name: Set required variables
      ansible.builtin.set_fact:
        project_name: "{{ projects.lambda_api.name }}"
        
    - name: Display operation info
      ansible.builtin.debug:
        msg: |
          ==========================================
          API Gateway Deploy
          ==========================================
          Environment: {{ env_name }}
          Project: {{ project_name }}-api-gateway
          Region: {{ aws_region }}
          Preview Only: {{ preview_only }}
          ==========================================
          
    - name: Check Lambda functions deployment
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/{{ project_name }}/{{ env_name }}/lambda/main-function-arn"
        store_as: "functions_check"
        default_value: ""
        ssm_parameter_store_fail_on_missing: false
        
    - name: Verify Lambda functions deployment
      ansible.builtin.fail:
        msg: |
          Lambda functions are not deployed!
          Please run: ansible-playbook playbooks/lambda/deploy/deploy_lambda_functions.yml -e "env={{ env_name }}"
      when:
        - functions_check | default('') | length == 0
  
  roles:
    - aws_setup
    - pulumi_helper
    - lambda_api_gateway
        
  post_tasks:
    - name: Display results
      ansible.builtin.debug:
        msg: |
          ==========================================
          API Gateway {{ 'Preview' if preview_only else 'Deploy' }} Complete
          ==========================================
          {% if not preview_only %}
          Status: {{ 'Success' if api_gateway_deployed | default(false) else 'Failed' }}
          API Endpoint: {{ api_endpoint | default('Not available') }}
          
          To get API Key:
          pulumi stack output apiKeyInfo -C {{ pulumi_path }}/{{ project_name }}-api-gateway
          
          Next step (optional):
          ansible-playbook playbooks/lambda/deploy/deploy_lambda_waf.yml -e "env={{ env_name }}"
          {% endif %}