---
# deploy_lambda_account_setup.yml
# Lambda APIアカウントレベル設定プレイブック（デプロイ用）
#
# 注意: これはAWSアカウントの各リージョンで1回だけ実行する設定です
#       環境（dev/staging/prod）に依存しません
#       API Gateway CloudWatch Logsロールはリージョンごとに設定が必要です
#
# 使用方法:
#   ansible-playbook playbooks/lambda/deploy/deploy_lambda_account_setup.yml
#
#   # 別リージョンで実行する場合:
#   ansible-playbook playbooks/lambda/deploy/deploy_lambda_account_setup.yml -e "aws_region=us-east-1"

- name: Deploy Lambda Account Setup
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    env_name: "{{ env | default('dev') }}"
    preview_only: "{{ preview | default(false) }}"

  pre_tasks:
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"

    - name: Set required variables
      ansible.builtin.set_fact:
        project_name: "{{ projects.lambda_api.name }}"

    - name: Display operation info
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda Account Setup Deploy
          ==========================================
          Environment: {{ env_name }}
          Project: {{ project_name }}-account-setup
          Region: {{ aws_region }}
          Preview Only: {{ preview_only }}
          ==========================================

  roles:
    - aws_setup
    - pulumi_helper
    - lambda_account_setup
        
  post_tasks:
    - name: Display results
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda Account Setup {{ 'Preview' if preview_only else 'Deploy' }} Complete
          ==========================================
          {% if not preview_only %}
          Status: {{ 'Success' if account_setup_deployed | default(false) else 'Failed' }}

          API Gateway CloudWatch Logs role has been configured.

          Next step:
          ansible-playbook playbooks/lambda/deploy/deploy_lambda_ssm_init.yml -e "env={{ env_name }}"
          {% endif %}