---
# deploy_lambda_shipment_s3.yml
# Lambda Shipment S3バケットデプロイメントプレイブック（デプロイ用）
#
# 使用方法:
#   ansible-playbook playbooks/lambda/deploy/deploy_lambda_shipment_s3.yml -e "env=dev"

- name: Deploy Lambda Shipment S3
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    env_name: "{{ env | default('dev') }}"
    preview_only: "{{ preview | default(false) }}"

  pre_tasks:
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"

    - name: Set required variables
      ansible.builtin.set_fact:
        project_name: "{{ projects.lambda_api.name }}"

    - name: Display operation info
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda Shipment S3 Deploy
          ==========================================
          Environment: {{ env_name }}
          Project: {{ project_name }}-shipment-s3
          Region: {{ aws_region }}
          Preview Only: {{ preview_only }}
          ==========================================

  roles:
    - aws_setup
    - pulumi_helper
    - lambda_shipment_s3
        
  post_tasks:
    - name: Display results
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda Shipment S3 {{ 'Preview' if preview_only else 'Deploy' }} Complete
          ==========================================
          {% if not preview_only %}
          Status: {{ 'Success' if shipment_s3_deployed | default(false) else 'Failed' }}

          Next step:
          ansible-playbook playbooks/lambda/deploy/deploy_lambda_functions.yml -e "env={{ env_name }}"
          {% endif %}