---
# deploy_lambda_security.yml
# Lambda API用セキュリティグループデプロイメントプレイブック
# 
# 使用方法:
#   ansible-playbook playbooks/lambda/deploy/deploy_lambda_security.yml -e "env=dev"

- name: Deploy Lambda API Security Groups
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    env_name: "{{ env | default('dev') }}"
    preview_only: "{{ preview | default(false) }}"
    
  pre_tasks:
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"
    
    - name: Set required variables
      ansible.builtin.set_fact:
        project_name: "{{ projects.lambda_api.name }}"
        
    - name: Display operation info
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda API Security Groups Deploy
          ==========================================
          Environment: {{ env_name }}
          Project: {{ project_name }}-security
          Region: {{ aws_region }}
          Preview Only: {{ preview_only }}
          ==========================================
          
    - name: Check network deployment
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/{{ project_name }}/{{ env_name }}/network/vpc-id"
        store_as: "vpc_id_check"
        default_value: ""
        ssm_parameter_store_fail_on_missing: false
        
    - name: Verify network deployment
      ansible.builtin.fail:
        msg: |
          Network infrastructure is not deployed!
          Please run: ansible-playbook playbooks/lambda/deploy/deploy_lambda_network.yml -e "env={{ env_name }}"
      when:
        - ssm_parameter_value | default('') | length == 0
  
  roles:
    - aws_setup
    - pulumi_helper
    - lambda_security
        
  post_tasks:
    - name: Display results
      ansible.builtin.debug:
        msg: |
          ==========================================
          Security Groups {{ 'Preview' if preview_only else 'Deploy' }} Complete
          ==========================================
          {% if not preview_only %}
          Status: {{ 'Success' if security_deployed | default(false) else 'Failed' }}
          
          Next step:
          ansible-playbook playbooks/lambda/deploy/deploy_lambda_vpce.yml -e "env={{ env_name }}"
          {% endif %}