---
# deploy_lambda_functions.yml
# Lambda関数デプロイメントプレイブック（デプロイ用）
# 
# 使用方法:
#   ansible-playbook playbooks/lambda/deploy/deploy_lambda_functions.yml -e "env=dev"

- name: Deploy Lambda Functions
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    env_name: "{{ env | default('dev') }}"
    preview_only: "{{ preview | default(false) }}"
    
  pre_tasks:
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"
    
    - name: Set required variables
      ansible.builtin.set_fact:
        project_name: "{{ projects.lambda_api.name }}"
        
    - name: Display operation info
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda Functions Deploy
          ==========================================
          Environment: {{ env_name }}
          Project: {{ project_name }}-functions
          Region: {{ aws_region }}
          Preview Only: {{ preview_only }}
          ==========================================

  roles:
    - aws_setup
    - pulumi_helper
    - lambda_functions
        
  post_tasks:
    - name: Display results
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda Functions {{ 'Preview' if preview_only else 'Deploy' }} Complete
          ==========================================
          {% if not preview_only %}
          Status: {{ 'Success' if functions_deployed | default(false) else 'Failed' }}
          Functions Deployed: {{ lambda_function_count | default(0) }}
          
          Next step:
          ansible-playbook playbooks/lambda/deploy/deploy_lambda_api_gateway.yml -e "env={{ env_name }}"
          {% endif %}