---
# ロードバランサーデプロイタスク

- name: Display loadbalancer deployment information
  ansible.builtin.debug:
    msg: "Deploying LoadBalancer Infrastructure for {{ env_name }} environment"

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true  # 詳細なログを抑制

# Pulumiデプロイ
- name: Deploy LoadBalancer Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize loadbalancer stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-loadbalancer"
        stack_name: "{{ env_name }}"
    
    # Pulumiプレビュー
    - name: Preview loadbalancer deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-loadbalancer"
    
    # Pulumiデプロイ
    - name: Deploy loadbalancer stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-loadbalancer"
    
    - name: Summary of loadbalancer deployment
      ansible.builtin.debug:
        msg: "LoadBalancer Infrastructure deployed successfully for {{ env_name }} environment"
  
  rescue:
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to deploy loadbalancer infrastructure. See error details above."

    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "LoadBalancer deployment failed."
