# lambda_functions ロールのデフォルト変数

# パスがプレイブックからの相対パスになるよう修正
scripts_dir: "{{ playbook_dir }}/../../scripts"
pulumi_path: "{{ playbook_dir }}/../../pulumi"

# 環境名のデフォルト値
env_name: "dev"

# Lambda関数設定のデフォルト値
lambda_runtime: "nodejs18.x"
lambda_memory: 256
lambda_timeout: 30
log_level: "INFO"
log_retention_days: 7

# DLQ設定のデフォルト値
dlq_max_retry_count: 3
dlq_visibility_timeout_multiplier: 6
dlq_retention_days: 14

# プレビューモード
preview_only: false
