---
# IP Whitelist初期化タスク

- name: Set secret name
  ansible.builtin.set_fact:
    secret_name: "{{ lambda_api.ip_whitelist.secret_name_pattern | replace('{environment}', env_name) }}"

- name: Display initialization information
  ansible.builtin.debug:
    msg: |
      Initializing IP Whitelist:
      - Environment: {{ env_name }}
      - Secret Name: {{ secret_name }}

- name: Check if secret already exists
  ansible.builtin.shell: |
    eval $({{ scripts_dir }}/aws-env.sh)
    aws secretsmanager describe-secret \
      --secret-id {{ secret_name }} \
      --region {{ aws_region_name }} 2>/dev/null
  register: secret_check
  failed_when: false
  changed_when: false

- name: Create initial IP whitelist structure
  ansible.builtin.set_fact:
    initial_whitelist:
      version: "1.0"
      lastUpdated: "{{ ansible_date_time.iso8601 }}"
      clients: []

- name: Create secret if not exists
  ansible.builtin.shell: |
    eval $({{ scripts_dir }}/aws-env.sh)
    aws secretsmanager create-secret \
      --name {{ secret_name }} \
      --description "IP Whitelist for Lambda API {{ env_name }} environment" \
