---
# IP Whitelist一覧表示タスク

- name: Set secret name
  ansible.builtin.set_fact:
    secret_name: "{{ lambda_api.ip_whitelist.secret_name_pattern | replace('{environment}', env_name) }}"

- name: Get current IP whitelist
  ansible.builtin.shell: |
    eval $({{ scripts_dir }}/aws-env.sh)
    aws secretsmanager get-secret-value \
      --secret-id {{ secret_name }} \
      --region {{ aws_region_name }} \
      --query SecretString --output text
  register: current_whitelist_raw
  changed_when: false

- name: Parse whitelist
  ansible.builtin.set_fact:
    current_whitelist: "{{ current_whitelist_raw.stdout | from_json }}"

- name: Display IP whitelist summary
  ansible.builtin.debug:
    msg: |
      ====================================
      IP Whitelist for {{ env_name }}
      ====================================
      Secret: {{ secret_name }}
      Version: {{ current_whitelist.version }}
      Last Updated: {{ current_whitelist.lastUpdated }}
      Total Clients: {{ current_whitelist.clients | length }}
      ====================================

- name: Display client details
  ansible.builtin.debug:
    msg: |
      Client: {{ item.name }} ({{ item.id }})
      - Description: {{ item.description }}
      - Enabled: {{ item.enabled }}
      - IP Addresses: {{ item.ipAddresses | join(', ') }}
      - Tags: {{ item.tags | default({}) | to_json }}
      ------------------------------------
  loop: "{{ current_whitelist.clients }}"
  when: current_whitelist.clients | length > 0

- name: Display empty whitelist message
  ansible.builtin.debug:
    msg: "No clients configured in the IP whitelist."
  when: current_whitelist.clients | length == 0
