jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 30
      computerConnector:
        sSHConnector:
          credentialsId: "ec2-agent-keypair"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          retryWaitTime: 15
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      disableTaskResubmit: false
      executorScaler: "noScaler"
      fleet: "sfr-46b88830-297e-4b70-81ae-e598b445e51d"
      idleMinutes: 15
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 900
      labelString: "ec2-fleet"
      maxSize: 1
      maxTotalUses: -1
      minSize: 0
      minSpareSize: 0
      name: "ec2-fleet"
      noDelayProvision: false
      numExecutors: 3
      privateIpUsed: true
      region: "ap-northeast-1"
      restrictUsage: false
      scaleExecutorsByWeight: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"
  labelAtoms:
  - name: "bootstrap-workterminal"
  - name: "built-in"
  - name: "ec2-fleet"
  markupFormatter:
    markdownFormatter:
      disableSyntaxHighlighting: false
  mode: NORMAL
  myViewsTabBar: "standard"
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  nodes:
  - permanent:
      labelString: "bootstrap-workterminal"
      launcher:
        ssh:
          credentialsId: "ec2-bootstrap-workterminal-keypair"
          host: "3.112.246.38"
          port: 22
          retryWaitTime: 5
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      mode: EXCLUSIVE
      name: "bootstrap-workterminal"
      nodeDescription: "Bootstrap Workterminal Node"
      remoteFS: "/home/ec2-user/jenkins-agent"
      retentionStrategy: "always"
  numExecutors: 1
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "cli-user"
        name: "Jenkins CLI User"
        properties:
        - "apiToken"
        - "consoleUrlProvider"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - theme:
            theme: "noOp"
        - "timezone"
        - "experimentalFlags"
        - mailer:
            emailAddress: "cli-user@jenkins.local"
      - id: "yutotakashi"
        name: "Yuto Takashi"
        properties:
        - "apiToken"
        - "consoleUrlProvider"
        - "myView"
        - "timezone"
        - "experimentalFlags"
        - preferredProvider:
            providerId: "default"
        - theme:
            theme: "noOp"
        - mailer:
            emailAddress: "yuto.takashi@plan-b.co.jp"
  slaveAgentPort: 0
  systemMessage: "Jenkins is configured automatically using JCasC"
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  pipelineGraphView:
    showGraphOnBuildPage: false
    showGraphOnJobPage: false
    showStageDurations: false
    showStageNames: false
  prism:
    theme: PRISM
  themeManager:
    disableUserThemes: false
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  copyartifact:
    mode: PRODUCTION
  cps:
    hideSandbox: false
  envInject:
    enableLoadingFromMaster: false
    enablePermissions: false
    hideInjectedVars: false
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  buildUserVars:
    allBuilds: true
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    throttlingEnabled: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://jenkins-in-alb-9ddad6a-1116181156.ap-northeast-1.elb.amazonaws.com/github-webhook/"
  globalLibraries:
    libraries:
    - defaultVersion: "main"
      name: "jenkins-shared-lib"
      retriever:
        modernSCM:
          clone: true
          libraryPath: "jenkins/jobs/shared/"
          scm:
            git:
              id: "5df19413-be18-4a7c-8680-73a4b37a061d"
              remote: "https://github.com/tielec/infrastructure-as-code/"
              traits:
              - "gitBranchDiscovery"
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwriteable: false
  jobConfigHistory:
    changeReasonCommentIsMandatory: false
    excludePattern: "queue\\.xml|nodeMonitors\\.xml|UpdateCenter\\.xml|global-build-stats|LockableResourcesManager\\\
      .xml|MilestoneStep\\.xml|cloudbees-disk-usage-simple\\.xml"
    saveModuleConfiguration: false
    showBuildBadges: "always"
    showChangeReasonCommentWindow: false
    skipDuplicateHistory: true
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "jenkins-admin@example.com"
    url: "http://jenkins-in-alb-9ddad6a-1116181156.ap-northeast-1.elb.amazonaws.com/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  scheduleBuild:
    defaultScheduleTime: "22:00:00"
    defaultStartTime: "22:00:00"
    timeZone: "Asia/Tokyo"
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  upstream:
    globalUpstreamFilterStrategy: UseOldest
  whitelist:
    enabled: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
