# lambda_account_setup ロールのデフォルト変数
scripts_dir: "{{ inventory_dir }}/../scripts"
pulumi_path: "{{ inventory_dir }}/../pulumi"

# アラートメール設定
alert_email: "dev-team@example.com"
critical_alert_email: "cto@example.com"

# プレビューモード
preview_only: false
