---
# ネットワークデプロイタスク

- name: Display network deployment information
  ansible.builtin.debug:
    msg: "Deploying Network Infrastructure for {{ env_name }} environment"

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true  # 詳細なログを抑制

# Pulumiデプロイ
- name: Deploy Network Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize network stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-network"
        stack_name: "{{ env_name }}"
    
    # 注: プロジェクト名とVPC CIDRはSSMパラメータから取得するため、
    # Pulumi設定は不要（Pulumiコード内でSSMから取得）

    # Pulumiプレビュー
    - name: Preview network deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-network"
    
    # Pulumiデプロイ
    - name: Deploy network stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-network"
    
    
    - name: Set network deployment status
      ansible.builtin.set_fact:
        network_deployed: true

    - name: Summary of network deployment
      ansible.builtin.debug:
        msg: "Network Infrastructure deployed successfully for {{ env_name }} environment"
  
  rescue:
    - name: Set network deployment status on failure
      ansible.builtin.set_fact:
        network_deployed: false
      
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to deploy network infrastructure. See error details above."
      
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Network deployment failed."
