---
# ネットワーク削除タスク

- name: Display network destruction information
  ansible.builtin.debug:
    msg: "Destroying Jenkins Network Infrastructure for {{ env_name }} environment (Remove Stack: {{ remove_stacks | default(false) }})"

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true  # 詳細なログを抑制

# Pulumiによる削除
- name: Destroy Network Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize network stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-network"
        stack_name: "{{ env_name }}"
    
    # Pulumiリソースの削除
    - name: Destroy network resources with Pulumi
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: destroy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-network"
    
    # スタック自体の削除（オプション）
    - name: Remove network stack (if requested)
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: remove_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-network"
        stack_name: "{{ env_name }}"
      when: remove_stacks | default(false) | bool
    

  rescue:
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Network destruction failed."
