---
# エージェントデプロイタスク

- name: Display agent deployment information
  ansible.builtin.debug:
    msg: |
      Deploying Jenkins Agent Infrastructure:
      - Project: {{ project_name }}
      - Agent Pulumi Project: {{ agent_project_name }}
      - Network Pulumi Project: {{ network_project_name }}
      - Security Pulumi Project: {{ security_project_name }}
      - Environment: {{ env_name }}

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true  # 詳細なログを抑制
  
- name: Report permission update
  ansible.builtin.debug:
    msg: "aws-env.sh スクリプトに実行権限を付与しました"
  when: aws_env_script_permission.changed

# エージェントセットアップスクリプトの確認
- name: Ensure agent-setup.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/jenkins/shell/agent-setup.sh"
    mode: '0755'
  register: agent_setup_script_permission
  no_log: true  # 詳細なログを抑制
  failed_when: false  # スクリプトが存在しない場合もエラーにしない
  
- name: Report agent script permission update
  ansible.builtin.debug:
    msg: "agent-setup.sh スクリプトに実行権限を付与しました"
  when: agent_setup_script_permission is defined and agent_setup_script_permission.changed

# Pulumiデプロイ
- name: Deploy Agent Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize agent stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-agent"
        stack_name: "{{ env_name }}"
    
    - name: Configure agent stack - AWS region
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-agent"
        config_key: "aws:region"
        config_value: "{{ aws_region_name }}"
    
    # Pulumiプレビュー
    - name: Preview agent deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-agent"
    
    # Pulumiデプロイ
    - name: Deploy agent stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-agent"
    
    - name: Set agent facts for use in other playbooks
      ansible.builtin.set_fact:
        agent_deployed: true
        # スタック参照情報も保存
        agent_stack_name: "{{ agent_project_name }}"

    - name: Summary of agent deployment
      ansible.builtin.debug:
        msg: "Jenkins Agent Infrastructure Deployed Successfully"
  
  rescue:
    - name: Set agent deployment status on failure
      ansible.builtin.set_fact:
        agent_deployed: false
      
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to deploy agent infrastructure. See error details above."
      
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Agent deployment failed."
