---
# VPC Endpointsデプロイタスク

- name: Display VPC endpoints deployment information
  ansible.builtin.debug:
    msg: |
      Deploying VPC Endpoints:
      - Project: {{ project_name }}
      - VPC Endpoints Pulumi Project: {{ vpc_endpoints_project_name }}
      - Environment: {{ env_name }}
      - Region: {{ aws_region_name }}

# 必要なSSMパラメータの確認
- name: Verify required SSM parameters exist
  block:
    - name: Check VPC ID exists
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/network/vpc-id"
        store_as: "vpc_id_check"
      register: vpc_id_result
      ignore_errors: true

    - name: Check Jenkins security group exists
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/security/jenkins-sg-id"
        store_as: "sg_id_check"
      register: sg_id_result
      ignore_errors: true

    - name: Fail if required parameters are missing
      ansible.builtin.fail:
        msg: |
          Required SSM parameters are missing. Please deploy the following first:
          - Network stack (for VPC ID)
          - Security stack (for Security Group ID)
      when: vpc_id_result.failed or sg_id_result.failed

# Pulumiデプロイ
- name: Deploy VPC Endpoints with Pulumi
  block:
    # Pulumiスタックを初期化
    - name: Initialize VPC endpoints stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_project_path }}"
        stack_name: "{{ env_name }}"
    
    # AWS リージョン設定
    - name: Configure VPC endpoints stack - AWS region
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_project_path }}"
        config_key: "aws:region"
        config_value: "{{ aws_region_name }}"
    
    # プレビュー（オプション）
    - name: Preview VPC endpoints deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_project_path }}"
      when: preview_only | bool
    
    # デプロイ実行
    - name: Deploy VPC endpoints stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_project_path }}"
      when: not preview_only | bool
    
    # デプロイ後に少し待機
    - name: Wait for endpoints to be available
      ansible.builtin.pause:
        seconds: 30
      when: 
        - not preview_only | bool
        - not ansible_check_mode
    
    # デプロイ完了時刻をSSMに保存
    - name: Save deployment timestamp to SSM
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: set_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/vpc-endpoints/deployed-at"
        parameter_value: "{{ ansible_date_time.iso8601 }}"
        parameter_type: "String"
        description: "VPC Endpoints deployment timestamp"
      when: not preview_only | bool
    
    - name: Set deployment status
      ansible.builtin.set_fact:
        vpc_endpoints_deployed: true
    
    - name: Summary of VPC endpoints deployment
      ansible.builtin.debug:
        msg: |
          VPC Endpoints deployed successfully:
          - SSM Endpoint
          - SSM Messages Endpoint
          - EC2 Messages Endpoint
          - EC2 Endpoint
          - S3 Endpoint (Gateway type)
          
          These endpoints enable private connectivity from EC2 instances
          to AWS services without requiring NAT or Internet Gateway.

  rescue:
    - name: Set deployment status on failure
      ansible.builtin.set_fact:
        vpc_endpoints_deployed: false
    
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to deploy VPC endpoints. See error details above."
    
    - name: Fail the task
      ansible.builtin.fail:
        msg: "VPC endpoints deployment failed."