---
# バッチ単位でパラメータを取得する内部タスク

- name: Get batch of parameters
  block:
    # 個別にパラメータを取得（community.awsモジュールはバッチ取得をサポートしていないため）
    - name: Initialize batch results
      ansible.builtin.set_fact:
        batch_parameters: {}
        batch_metadata: {}
        batch_failed: []

    - name: Get each parameter in batch
      community.aws.ssm_parameter_info:
        name: "{{ param }}"
        region: "{{ ssm_parameter_store_region }}"
        with_decryption: "{{ decrypt | default(true) }}"
      register: param_result
      loop: "{{ parameter_batch }}"
      loop_control:
        loop_var: param
      ignore_errors: true
      no_log: true

    - name: Process successful parameters
      ansible.builtin.set_fact:
        batch_parameters: >-
          {{
            batch_parameters | combine({
              item.param: item.parameters[0].value
            })
          }}
        batch_metadata: >-
          {{
            batch_metadata | combine({
              item.param: {
                'type': item.parameters[0].type | default('String'),
                'version': item.parameters[0].version | default(1),
                'last_modified': item.parameters[0].last_modified_date | default('')
              }
            })
          }}
      loop: "{{ param_result.results }}"
      when: 
        - item is not failed
        - item.parameters is defined
        - item.parameters | length > 0
      no_log: true

    - name: Track failed parameters
      ansible.builtin.set_fact:
        batch_failed: >-
          {{
            batch_failed + [item.param]
          }}
      loop: "{{ param_result.results }}"
      when: item is failed

    - name: Update main results
      ansible.builtin.set_fact:
        ssm_parameters: >-
          {{
            ssm_parameters | combine(batch_parameters)
          }}
        ssm_parameter_metadata: >-
          {{
            ssm_parameter_metadata | combine(batch_metadata)
          }}
        failed_parameters: >-
          {{
            failed_parameters + batch_failed
          }}

  rescue:
    - name: Handle batch failure
      ansible.builtin.debug:
        msg: "Failed to retrieve batch {{ batch_index }}: {{ ansible_failed_result.msg | default('Unknown error') }}"
      when: ssm_parameter_store_debug

    - name: Add all parameters to failed list
      ansible.builtin.set_fact:
        failed_parameters: >-
          {{
            failed_parameters + parameter_batch
          }}
