---
# SSMパラメータを削除するタスク（aws_cli_helper版）

- name: Validate inputs
  ansible.builtin.assert:
    that:
      - parameter_name is defined
      - parameter_name | length > 0
    fail_msg: "Required variable 'parameter_name' must be defined and not empty"

# パラメータを削除
- name: Delete parameter from SSM using AWS CLI helper
  ansible.builtin.include_role:
    name: aws_cli_helper
    tasks_from: execute_with_retry
  vars:
    aws_command: >-
      aws ssm delete-parameter
      --name "{{ parameter_name }}"
    operation_name: "ssm_delete_parameter"

# 結果の処理
- name: Process deletion result
  ansible.builtin.set_fact:
    ssm_operation_success: "{{ aws_cli_success or aws_cli_error_type == 'ResourceNotFound' }}"
    ssm_operation_error: >-
      {%- if aws_cli_success -%}
        ""
      {%- elif aws_cli_error_type == 'ResourceNotFound' -%}
        "Parameter already deleted"
      {%- else -%}
        {{ aws_cli_error_message }}
      {%- endif -%}

# デバッグ出力
- name: Display operation result
  when: ssm_parameter_store_verbose
  ansible.builtin.debug:
    msg: |
      Parameter: {{ parameter_name }}
      Deleted: {{ ssm_operation_success }}
      Retry Attempts: {{ aws_cli_retry_attempts | default(1) }}
      {% if ssm_operation_error %}
      Note: {{ ssm_operation_error }}
      {% endif %}
