---
# パス指定でSSMパラメータを一括取得するタスク（シンプル版）

- name: Validate required variables
  ansible.builtin.fail:
    msg: "Required variable 'parameter_path' is not defined"
  when: parameter_path is not defined or parameter_path | length == 0

# パスの正規化
- name: Normalize parameter path
  ansible.builtin.set_fact:
    normalized_path: "{{ parameter_path if parameter_path.endswith('/') else parameter_path + '/' }}"

# パラメータを取得
- name: Get parameters by path
  ansible.builtin.shell: |
    aws ssm get-parameters-by-path \
      --path "{{ normalized_path }}" \
      {% if recursive | default(true) %}--recursive{% endif %} \
      {% if decrypt | default(true) %}--with-decryption{% endif %} \
      --region {{ ssm_parameter_store_region }} \
      --output json
  register: path_result
  no_log: true

# 結果の処理
- name: Process results
  when: path_result.rc == 0
  block:
    - name: Parse parameters
      ansible.builtin.set_fact:
        _path_data: "{{ path_result.stdout | from_json }}"
      no_log: true

    - name: Extract parameters
      ansible.builtin.set_fact:
        ssm_parameters: >-
          {%- set params = {} -%}
          {%- for param in _path_data.Parameters | default([]) -%}
            {%- set _ = params.update({param.Name: param.Value}) -%}
          {%- endfor -%}
          {{ params }}

    - name: Extract metadata
      ansible.builtin.set_fact:
        ssm_parameter_metadata: >-
          {%- set metadata = {} -%}
          {%- for param in _path_data.Parameters | default([]) -%}
            {%- set _ = metadata.update({
              param.Name: {
                'type': param.Type,
                'version': param.Version,
                'last_modified': param.LastModifiedDate | default('')
              }
            }) -%}
          {%- endfor -%}
          {{ metadata }}

    - name: Set success status
      ansible.builtin.set_fact:
        ssm_operation_success: true
        ssm_parameter_count: "{{ ssm_parameters | length }}"

# エラー処理
- name: Handle errors
  when: path_result.rc != 0
  ansible.builtin.set_fact:
    ssm_operation_success: false
    ssm_operation_error: "{{ path_result.stderr | default('Failed to retrieve parameters') }}"
    ssm_parameters: {}
    ssm_parameter_count: 0

# デバッグ出力
- name: Display summary
  ansible.builtin.debug:
    msg: |
      Path: {{ normalized_path }}
      Recursive: {{ recursive | default(true) }}
      Success: {{ ssm_operation_success }}
      Parameters found: {{ ssm_parameter_count | default(0) }}
      {% if not ssm_operation_success %}
      Error: {{ ssm_operation_error }}
      {% endif %}
  when: ssm_parameter_store_verbose
