---
# 単一のSSMパラメータを取得するタスク（aws_cli_helper版）

- name: Validate inputs
  ansible.builtin.assert:
    that:
      - parameter_name is defined
      - parameter_name | length > 0
    fail_msg: "Required variable 'parameter_name' must be defined and not empty"

# セキュアパラメータかどうかを判定
- name: Determine if parameter is secure
  ansible.builtin.set_fact:
    is_secure: >-
      {{
        ssm_parameter_store_auto_secure and (
          parameter_name | lower | regex_search('(' + ssm_parameter_store_secure_keywords | join('|') + ')')
        ) is not none
      }}

# パラメータを取得
- name: Get parameter from SSM
  ansible.builtin.include_role:
    name: aws_cli_helper
    tasks_from: execute_with_retry
  vars:
    aws_command: >-
      aws ssm get-parameter
      --name "{{ parameter_name }}"
      {% if decrypt | default(true) %}--with-decryption{% endif %}
      --output json
    operation_name: "ssm_get_parameter"
    no_log_output: "{{ is_secure }}"
    max_retries: "{{ ssm_parameter_store_retry_count }}"
    retry_delay: "{{ ssm_parameter_store_retry_delay }}"

# 結果の処理
- name: Process get result
  when: aws_cli_success
  block:
    - name: Extract parameter value and metadata
      ansible.builtin.set_fact:
        ssm_parameter_value: "{{ aws_cli_data.Parameter.Value }}"
        ssm_parameter_metadata:
          name: "{{ aws_cli_data.Parameter.Name }}"
          type: "{{ aws_cli_data.Parameter.Type }}"
          version: "{{ aws_cli_data.Parameter.Version }}"
          last_modified: "{{ aws_cli_data.Parameter.LastModifiedDate | default('') }}"
        ssm_operation_success: true
        ssm_operation_error: ""
      no_log: "{{ is_secure }}"

    # JSONパラメータの処理
    - name: Parse JSON value if requested
      when: parse_json | default(false)
      block:
        - name: Attempt to parse parameter value as JSON
          ansible.builtin.set_fact:
            ssm_parameter_value: "{{ ssm_parameter_value | from_json }}"
          failed_when: false
          register: _json_parse_result

        - name: Log JSON parse failure
          when: _json_parse_result is failed
          ansible.builtin.debug:
            msg: "Failed to parse parameter value as JSON: {{ _json_parse_result.msg | default('Unknown error') }}"

    # カスタム変数として保存
    - name: Store as custom variable
      when: store_as is defined
      ansible.builtin.set_fact:
        "{{ store_as }}": "{{ ssm_parameter_value }}"
      no_log: "{{ is_secure }}"

# パラメータが見つからない場合の処理
- name: Handle parameter not found
  when: not aws_cli_success
  block:
    - name: Check if parameter not found
      ansible.builtin.set_fact:
        _parameter_not_found: "{{ aws_cli_error_type == 'ResourceNotFound' }}"

    - name: Use default value if specified
      when:
        - _parameter_not_found
        - default_value is defined
      ansible.builtin.set_fact:
        ssm_parameter_value: "{{ default_value }}"
        ssm_operation_success: true
        ssm_operation_error: ""

    - name: Handle missing parameter without default
      when:
        - _parameter_not_found
        - default_value is not defined
      ansible.builtin.set_fact:
        ssm_operation_success: false
        ssm_operation_error: "Parameter not found"
      failed_when: ssm_parameter_store_fail_on_missing

    - name: Set error for other failures
      when: not _parameter_not_found
      ansible.builtin.set_fact:
        ssm_operation_success: false
        ssm_operation_error: "{{ aws_cli_error_message }}"

# デバッグ出力
- name: Display parameter info
  when: ssm_parameter_store_verbose
  ansible.builtin.debug:
    msg: |
      Parameter: {{ parameter_name }}
      Success: {{ ssm_operation_success }}
      Retry Attempts: {{ aws_cli_retry_attempts | default(1) }}
      {% if ssm_operation_success and not is_secure %}
      Value: {{ ssm_parameter_value }}
      {% elif ssm_operation_success and is_secure %}
      Value: [SECURE - {{ ssm_parameter_store_mask_partial | ternary(ssm_parameter_value[:3] + '***', ssm_parameter_store_mask_value) }}]
      {% else %}
      Error: {{ ssm_operation_error }}
      {% endif %}
