---
# パス指定でSSMパラメータを一括取得するタスク（aws_cli_helper版）

- name: Validate inputs
  ansible.builtin.assert:
    that:
      - parameter_path is defined
      - parameter_path | length > 0
    fail_msg: "Required variable 'parameter_path' must be defined"

# パスの正規化
- name: Normalize parameter path
  ansible.builtin.set_fact:
    normalized_path: "{{ parameter_path if parameter_path.endswith('/') else parameter_path + '/' }}"

# パラメータを取得
- name: Get parameters by path using AWS CLI helper
  ansible.builtin.include_role:
    name: aws_cli_helper
    tasks_from: execute_with_retry
  vars:
    aws_command: >-
      aws ssm get-parameters-by-path
      --path "{{ normalized_path }}"
      {% if recursive | default(true) %}--recursive{% endif %}
      {% if decrypt | default(true) %}--with-decryption{% endif %}
      --output json
    operation_name: "ssm_get_parameters_by_path"
    no_log_output: true

# 結果の処理
- name: Process results
  when: aws_cli_success
  block:
    - name: Extract parameters
      ansible.builtin.set_fact:
        ssm_parameters: >-
          {%- set params = {} -%}
          {%- for param in aws_cli_data.Parameters | default([]) -%}
            {%- set _ = params.update({param.Name: param.Value}) -%}
          {%- endfor -%}
          {{ params }}

    - name: Extract metadata
      ansible.builtin.set_fact:
        ssm_parameter_metadata: >-
          {%- set metadata = {} -%}
          {%- for param in aws_cli_data.Parameters | default([]) -%}
            {%- set _ = metadata.update({
              param.Name: {
                'type': param.Type,
                'version': param.Version,
                'last_modified': param.LastModifiedDate | default('')
              }
            }) -%}
          {%- endfor -%}
          {{ metadata }}

    - name: Set success status
      ansible.builtin.set_fact:
        ssm_operation_success: true
        ssm_parameter_count: "{{ ssm_parameters | length | int }}"

# エラー処理
- name: Handle errors
  when: not aws_cli_success
  ansible.builtin.set_fact:
    ssm_operation_success: false
    ssm_operation_error: "{{ aws_cli_error_message }}"
    ssm_parameters: {}
    ssm_parameter_count: 0

# デバッグ出力
- name: Display summary
  when: ssm_parameter_store_verbose
  ansible.builtin.debug:
    msg: |
      Path: {{ normalized_path }}
      Recursive: {{ recursive | default(true) }}
      Success: {{ ssm_operation_success }}
      Parameters found: {{ ssm_parameter_count | default(0) }}
      Retry Attempts: {{ aws_cli_retry_attempts | default(1) }}
      {% if not ssm_operation_success %}
      Error: {{ ssm_operation_error }}
      {% endif %}
