---
# 複数のSSMパラメータを一括取得するタスク

- name: Validate required variables
  ansible.builtin.fail:
    msg: "Required variable 'parameter_names' is not defined or empty"
  when: 
    - parameter_names is not defined or parameter_names | length == 0

# バッチ処理の準備
- name: Split parameters into batches
  ansible.builtin.set_fact:
    parameter_batches: >-
      {{
        parameter_names | 
        batch(ssm_parameter_store_batch_size) | 
        list
      }}

- name: Initialize results
  ansible.builtin.set_fact:
    ssm_parameters: {}
    ssm_parameter_metadata: {}
    failed_parameters: []

# 各バッチを処理
- name: Process parameter batches
  ansible.builtin.include_tasks: _get_parameter_batch.yml
  loop: "{{ parameter_batches }}"
  loop_control:
    loop_var: parameter_batch
    index_var: batch_index

# 結果の集計
- name: Check overall success
  ansible.builtin.set_fact:
    ssm_operation_success: "{{ failed_parameters | length == 0 }}"
    ssm_parameter_count: "{{ ssm_parameters | length }}"

# デバッグ出力
- name: Display results summary
  ansible.builtin.debug:
    msg: |
      Total parameters requested: {{ parameter_names | length }}
      Successfully retrieved: {{ ssm_parameter_count }}
      Failed: {{ failed_parameters | length }}
      {% if failed_parameters | length > 0 %}
      Failed parameters:
      {% for param in failed_parameters %}
      - {{ param }}
      {% endfor %}
      {% endif %}
  when: ssm_parameter_store_verbose
