---
# SSMパラメータの一覧を取得するタスク

- name: List parameters
  block:
    # パラメータ情報の取得
    - name: Get parameter list from SSM
      community.aws.ssm_parameter_info:
        region: "{{ ssm_parameter_store_region }}"
        path_prefix: "{{ name_prefix | default(omit) }}"
      register: list_result

    # 結果のフィルタリング（パラメータタイプ指定時）
    - name: Filter by parameter type
      ansible.builtin.set_fact:
        parameter_list: >-
          {{
            list_result.parameters |
            selectattr('type', 'equalto', parameter_type) |
            list
          }}
      when: parameter_type is defined

    - name: Use all parameters (no filter)
      ansible.builtin.set_fact:
        parameter_list: "{{ list_result.parameters }}"
      when: parameter_type is not defined

    # 最大結果数の適用
    - name: Apply max results limit
      ansible.builtin.set_fact:
        parameter_list: "{{ parameter_list[:max_results|int] }}"
      when: max_results is defined

    - name: Set success status
      ansible.builtin.set_fact:
        ssm_operation_success: true

    # 結果の整形
    - name: Format parameter information
      ansible.builtin.set_fact:
        ssm_parameter_info: >-
          {{
            parameter_list | map(attribute='name') | list
          }}
        ssm_parameter_details: >-
          {{
            parameter_list | map(lambda x: {
              'name': x.name,
              'type': x.type | default('String'),
              'last_modified': x.last_modified_date | default(''),
              'version': x.version | default(1)
            }) | list
          }}

  rescue:
    - name: Handle list failure
      ansible.builtin.set_fact:
        ssm_operation_error: "{{ ansible_failed_result.msg | default('Failed to list parameters') }}"
        ssm_operation_success: false
        parameter_list: []
        ssm_parameter_info: []
        ssm_parameter_details: []

# デバッグ出力
- name: Display parameter list
  ansible.builtin.debug:
    msg: |
      Total parameters found: {{ parameter_list | length }}
      {% if ssm_parameter_store_debug %}
      Parameters:
      {% for param in ssm_parameter_details %}
      - {{ param.name }} ({{ param.type }}, v{{ param.version }})
      {% endfor %}
      {% endif %}
  when: 
    - ssm_parameter_store_verbose
    - ssm_operation_success
