---
# SSMパラメータの一覧を取得するタスク（aws_cli_helper版）

# フィルター条件の設定
- name: Build parameter filters
  ansible.builtin.set_fact:
    parameter_filters: >-
      {%- set filters = [] -%}
      {%- if name_prefix is defined -%}
        {%- set _ = filters.append({'Key': 'Name', 'Values': [name_prefix]}) -%}
      {%- endif -%}
      {%- if parameter_type is defined -%}
        {%- set _ = filters.append({'Key': 'Type', 'Values': [parameter_type]}) -%}
      {%- endif -%}
      {{ filters }}

# パラメータ一覧を取得
- name: List parameters using AWS CLI helper
  ansible.builtin.include_role:
    name: aws_cli_helper
    tasks_from: execute_with_retry
  vars:
    aws_command: >-
      aws ssm describe-parameters
      {% if parameter_filters | length > 0 %}
      --parameter-filters '{{ parameter_filters | to_json }}'
      {% endif %}
      {% if max_results is defined %}
      --max-items {{ max_results }}
      {% endif %}
      --output json
    operation_name: "ssm_list_parameters"

# 結果の処理
- name: Process list results
  when: aws_cli_success
  block:
    - name: Format parameter information
      ansible.builtin.set_fact:
        parameter_list: "{{ aws_cli_data.Parameters | default([]) }}"
        ssm_parameter_info: >-
          {{
            parameter_list | map(attribute='Name') | list
          }}
        ssm_parameter_details: >-
          {%- set details = [] -%}
          {%- for param in parameter_list -%}
            {%- set _ = details.append({
              'name': param.Name,
              'type': param.Type,
              'last_modified': param.LastModifiedDate | default(''),
              'version': param.Version | default(1)
            }) -%}
          {%- endfor -%}
          {{ details }}
        ssm_operation_success: true

- name: Handle list failure
  when: not aws_cli_success
  ansible.builtin.set_fact:
    ssm_operation_error: "{{ aws_cli_error_message }}"
    ssm_operation_success: false
    parameter_list: []
    ssm_parameter_info: []
    ssm_parameter_details: []

# デバッグ出力
- name: Display parameter list
  when: 
    - ssm_parameter_store_verbose
    - ssm_operation_success
  ansible.builtin.debug:
    msg: |
      Total parameters found: {{ parameter_list | length }}
      Retry Attempts: {{ aws_cli_retry_attempts | default(1) }}
      {% if ssm_parameter_store_debug and ssm_parameter_details | length > 0 %}
      Parameters:
      {% for param in ssm_parameter_details %}
      - {{ param.name }} ({{ param.type }}, v{{ param.version }})
      {% endfor %}
      {% endif %}
