---
# SSMパラメータの一覧を取得するタスク

# フィルター条件の設定
- name: Build parameter filters
  ansible.builtin.set_fact:
    parameter_filters: >-
      {%- set filters = [] -%}
      {%- if name_prefix is defined -%}
        {%- set _ = filters.append({'Key': 'Name', 'Values': [name_prefix]}) -%}
      {%- endif -%}
      {%- if parameter_type is defined -%}
        {%- set _ = filters.append({'Key': 'Type', 'Values': [parameter_type]}) -%}
      {%- endif -%}
      {{ filters }}

- name: List parameters
  block:
    - name: Get parameter list from SSM
      ansible.builtin.shell: |
        aws ssm describe-parameters \
          {% if parameter_filters | length > 0 %}
          --parameter-filters '{{ parameter_filters | to_json }}' \
          {% endif %}
          {% if max_results is defined %}
          --max-items {{ max_results }} \
          {% endif %}
          --region {{ ssm_parameter_store_region }} \
          --output json
      register: list_result
      changed_when: false

    - name: Parse parameter list
      ansible.builtin.set_fact:
        parameter_list: "{{ (list_result.stdout | from_json).Parameters }}"
        ssm_operation_success: true

    # 結果の整形
    - name: Format parameter information
      ansible.builtin.set_fact:
        ssm_parameter_info: >-
          {{
            parameter_list | map(attribute='Name') | list
          }}
        ssm_parameter_details: >-
          {{
            parameter_list | map(lambda x: {
              'name': x.Name,
              'type': x.Type,
              'last_modified': x.LastModifiedDate | default(''),
              'version': x.Version | default(1)
            }) | list
          }}

  rescue:
    - name: Handle list failure
      ansible.builtin.set_fact:
        ssm_operation_error: "{{ ansible_failed_result.msg | default('Failed to list parameters') }}"
        ssm_operation_success: false
        parameter_list: []

# デバッグ出力
- name: Display parameter list
  ansible.builtin.debug:
    msg: |
      Total parameters found: {{ parameter_list | length }}
      {% if ssm_parameter_store_debug %}
      Parameters:
      {% for param in ssm_parameter_details %}
      - {{ param.name }} ({{ param.type }}, v{{ param.version }})
      {% endfor %}
      {% endif %}
  when: 
    - ssm_parameter_store_verbose
    - ssm_operation_success
