---
# SSMパラメータストアヘルパーのメインタスク（aws_cli_helper統合版）

# AWS CLI Helperが利用可能か確認
- name: Verify AWS CLI Helper is available
  ansible.builtin.include_role:
    name: aws_cli_helper
  run_once: true

# セキュアキーワードの読み込み（オプション）
- name: Load additional secure keywords
  ansible.builtin.include_vars:
    file: secure_keywords.yml
  failed_when: false

# 結果変数の初期化
- name: Initialize result variables
  ansible.builtin.set_fact:
    ssm_parameter_value: null
    ssm_parameters: {}
    ssm_parameter_metadata: {}
    ssm_operation_success: false
    ssm_operation_error: null
    ssm_parameter_count: 0

# AWS認証の確認（オプション）
- name: Validate AWS configuration
  when: ssm_parameter_store_validate_aws | default(true)
  ansible.builtin.include_role:
    name: aws_cli_helper
    tasks_from: execute
  vars:
    aws_command: "aws sts get-caller-identity"
    operation_name: "verify_aws_credentials"
