---
# Jenkins Agent AMI Builder destroy tasks

- name: Destroy Agent AMI Builder Infrastructure
  block:
    
    - name: Destroy agent AMI stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: destroy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-agent-ami"
    
    - name: Display destroy completion message
      ansible.builtin.debug:
        msg: "Jenkins Agent AMI Builder Infrastructure destroyed for {{ env_name }} environment"
    
    # AMI削除（デフォルトで実行）
    - name: Check if AMI deletion should be skipped
      ansible.builtin.debug:
        msg: "Skip AMI deletion: {{ skip_ami_deletion | default(false) }}"
    
    - name: Delete created AMIs
      ansible.builtin.include_tasks: destroy_images.yml
      when: not (skip_ami_deletion | default(false) | bool)
  
  rescue:
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Agent AMI Builder destruction failed."