# AI Workflow - 設定ファイル

# Claude Agent SDK 設定
# 環境変数: CLAUDE_CODE_OAUTH_TOKEN (必須)
# モデル: デフォルト（Claude Code Pro Max の Sonnet 4.5）
claude_agent_sdk:
  model: null  # null の場合は Claude Code Pro Max のデフォルトモデルを使用
  max_tokens_per_request: 4096
  timeout: 120

# ContentParser 設定（レビュー結果パース、戦略抽出）
# 環境変数: OPENAI_API_KEY (必須)
# モデル: gpt-4o-mini（安価・高速）
content_parser:
  model: "gpt-4o-mini"
  max_tokens: 1024
  temperature: 0.0  # 決定論的な出力

# コスト制限
cost_limits:
  per_phase_max_tokens: 100000
  per_workflow_max_cost_usd: 5.0
  warning_threshold: 0.8

# リトライ設定
retry:
  max_attempts: 3
  backoff_multiplier: 2
  initial_delay_seconds: 1

# コードベース分析設定
codebase_analysis:
  max_files: 20
  max_tokens: 50000
  file_size_limit_kb: 100

# テスト実行設定
testing:
  timeout_seconds: 600
  failure_max_retries: 3

# Git設定
git:
  branch_prefix: "feature/issue-"
  commit_message_template: "[AI-Workflow][Phase {phase}] {phase_name}: {status}"
  workflow_dir: ".ai-workflow"

# GitHub設定
github:
  api_url: "https://api.github.com"
  timeout: 30
