---
# Step 5: セキュリティ有効化（冪等）

# 管理者パスワードを取得
- name: Get admin password from SSM
  ansible.builtin.include_role:
    name: ssm_parameter_store
    tasks_from: get_parameter
  vars:
    parameter_name: "/jenkins-infra/{{ env_name }}/credentials/admin-password"
    store_as: "admin_password"
    default_value: ""

- name: Ensure admin password exists
  ansible.builtin.assert:
    that:
      - admin_password != ""
    fail_msg: "Admin password not found in SSM. Please ensure admin user was created in Step 3."

# セキュリティを有効化
- name: Enable Jenkins security via SSM
  ansible.builtin.include_tasks: ../jenkins_application/tasks/execute_ssm_command.yml
  vars:
    ssm_document_name: "{{ execute_script_document_name }}"
    ssm_parameters: "ScriptPath=scripts/jenkins/v2/enable-security.sh"
    ssm_comment: "Enabling Jenkins security"
    instance_id: "{{ jenkins_instance_id }}"
  register: enable_security_result

- name: Check if security was enabled
  ansible.builtin.set_fact:
    security_enabled: "{{ 'SECURITY_ENABLED' in enable_security_result.stdout }}"

# セキュリティが有効になったか確認
- name: Verify security is enabled via SSM
  ansible.builtin.include_tasks: ../jenkins_application/tasks/execute_ssm_command.yml
  vars:
    ssm_document_name: "{{ execute_script_document_name }}"
    ssm_parameters: "ScriptPath=scripts/jenkins/v2/check-security-status.sh"
    ssm_comment: "Verifying security is enabled"
    instance_id: "{{ jenkins_instance_id }}"
  register: verify_security_result

- name: Ensure security is enabled
  ansible.builtin.assert:
    that:
      - "'SECURED' in verify_security_result.stdout"
    fail_msg: "Failed to enable Jenkins security"

# APIトークンを生成（必要に応じて）
- name: Generate API tokens for admin user
  ansible.builtin.include_tasks: ../jenkins_application/tasks/execute_ssm_command.yml
  vars:
    ssm_document_name: "{{ execute_script_document_name }}"
    ssm_parameters: "ScriptPath=scripts/jenkins/v2/generate-api-tokens.sh"
    ssm_comment: "Generating API tokens"
    instance_id: "{{ jenkins_instance_id }}"
  register: api_token_result
  ignore_errors: true

# フェーズを更新
- name: Update phase to security_enabled
  ansible.builtin.include_role:
    name: ssm_parameter_store
    tasks_from: put_parameter
  vars:
    parameter_name: "/jenkins-infra/{{ env_name }}/application/phase"
    parameter_value: "security_enabled"
    parameter_type: "String"
    parameter_description: "Jenkins application configuration phase"

- name: Step 5 completed
  ansible.builtin.debug:
    msg: |
      Step 5 - Security enabled successfully
      Jenkins is now secured with authentication
      Admin user: {{ jenkins_admin_user }}
      Use the admin password from SSM to login