---
# Lambda API関数のデプロイタスク

- name: Display Lambda functions deployment information
  ansible.builtin.debug:
    msg: "Deploying Lambda API Functions for {{ env_name }} environment"

# Pulumiデプロイ
- name: Deploy Lambda functions with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize functions stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-functions"
        stack_name: "{{ env_name }}"
    
    
    # Pulumi Configは使用しない（SSMパラメータから取得するため）
    
    # Pulumiプレビュー
    - name: Preview functions deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-functions"
      when: preview_only | default(false) | bool
    
    # Pulumiデプロイ
    - name: Deploy Lambda functions
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-functions"
      when: not preview_only | default(false) | bool
    
    # デプロイ成功を示す変数設定
    - name: Set functions deployment status
      ansible.builtin.set_fact:
        functions_deployed: true
      when: not preview_only | default(false) | bool
    
    # Lambda関数情報の表示
    - name: Display Lambda functions deployment summary
      ansible.builtin.debug:
        msg: "Lambda functions deployed successfully for {{ env_name }} environment"
      when: not preview_only | default(false) | bool
  
  rescue:
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Lambda API functions deployment failed."

