---
# roles/lambda_shipment_s3/tasks/deploy.yml
# Lambda Shipment S3バケットのデプロイタスク

- name: Set deployment variables
  ansible.builtin.set_fact:
    shipment_s3_stack_name: "lambda-shipment-s3"
    shipment_s3_project_path: "{{ pulumi_path }}/lambda-shipment-s3"

- name: Check if project exists
  ansible.builtin.stat:
    path: "{{ shipment_s3_project_path }}"
  register: shipment_s3_project

- name: Fail if project doesn't exist
  ansible.builtin.fail:
    msg: "Lambda Shipment S3 project not found at {{ shipment_s3_project_path }}"
  when: not shipment_s3_project.stat.exists

- name: Initialize Lambda Shipment S3 stack
  ansible.builtin.include_role:
    name: pulumi_helper
    tasks_from: init_stack
  vars:
    pulumi_project_path: "{{ shipment_s3_project_path }}"
    stack_name: "{{ env_name }}"

- name: Preview Lambda Shipment S3 deployment
  ansible.builtin.include_role:
    name: pulumi_helper
    tasks_from: preview
  vars:
    pulumi_project_path: "{{ shipment_s3_project_path }}"
  when: preview_only | default(false) | bool

- name: Deploy Lambda Shipment S3 bucket
  ansible.builtin.include_role:
    name: pulumi_helper
    tasks_from: deploy
  vars:
    pulumi_project_path: "{{ shipment_s3_project_path }}"
  when: not preview_only | default(false) | bool

- name: Set deployment status
  ansible.builtin.set_fact:
    shipment_s3_deployed: "{{ pulumi_deployment_succeeded | default(false) }}"

- name: Display deployment summary
  ansible.builtin.debug:
    msg: |
      Lambda Shipment S3 Deployment Summary:
      =====================================
      Stack: {{ shipment_s3_stack_name }}
      Environment: {{ env_name }}
      Status: {{ 'Success' if shipment_s3_deployed else 'Failed' }}
      Preview Only: {{ preview_only }}
  when: not preview_only