---
# Jenkins VPCエンドポイントデプロイメント用プレイブック
# プライベートサブネットからAWSサービスへの接続を提供

- name: Deploy VPC Endpoints for Jenkins Infrastructure
  hosts: localhost
  gather_facts: yes
  vars:
    deploy_env: "{{ env | default('dev') }}"
    
  tasks:
    - name: Deploy VPC endpoints using role
      ansible.builtin.include_role:
        name: jenkins_vpc_endpoints
      vars:
        operation: deploy
        deploy_env: "{{ deploy_env }}"