---
# configure_jenkins_controller.yml
# Jenkinsコントローラーの設定タスクを実行
#
# 使用方法 (ansibleディレクトリから実行):
#   ansible-playbook playbooks/jenkins/deploy/deploy_jenkins_config.yml -e "env=dev"


- name: Configure Jenkins Controller
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    # コマンドラインから環境名を受け取る
    env_name: "{{ env | default('dev') }}"
    jenkins_instance_id: "{{ instance_id | default('') }}"
  
  pre_tasks:
    # all.yml から変数を読み込む
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"
        
    # 必要な変数を設定
    - name: Set required variables from all.yml
      ansible.builtin.set_fact:
        project_name: "{{ infra.project_name }}"
        aws_region_name: "{{ infra.aws.default_region }}"
        network_project_name: "{{ infra.pulumi.network_project }}"
        security_project_name: "{{ infra.pulumi.security_project }}"
        storage_project_name: "{{ infra.pulumi.storage_project }}"
        loadbalancer_project_name: "{{ infra.pulumi.loadbalancer_project }}"
        controller_project_name: "{{ infra.pulumi.controller_project }}"
        config_project_name: "{{ infra.pulumi.config_project }}"

  roles:
    - jenkins_config