---
# deploy_jenkins_network.yml
# Jenkinsインフラのネットワークリソース（VPC、サブネット等）をデプロイ
#
# 使用方法 (ansibleディレクトリから実行):
#   ansible-playbook playbooks/jenkins/deploy/deploy_jenkins_network.yml -e "env=dev"

- name: Deploy Jenkins Network Infrastructure
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    # コマンドラインから環境名を受け取る
    env_name: "{{ env | default('dev') }}"
  
  pre_tasks:
    # all.yml から変数を読み込む
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../inventory/group_vars/all.yml"
        
    # 必要な変数を設定
    - name: Set required variables from all.yml
      ansible.builtin.set_fact:
        project_name: "{{ infra.project_name }}"
        aws_region_name: "{{ infra.aws.default_region }}"
        network_project_name: "{{ infra.pulumi.network_project }}"
        vpc_cidr: "{{ infra.aws.vpc_cidr }}"
  
  roles:
    - jenkins_network
