---
# deploy_jenkins_application.yml
# Jenkins環境構築後のアプリケーション設定を管理
#
# 使用方法 (ansibleディレクトリから実行):
#   ansible-playbook playbooks/jenkins/deploy/deploy_jenkins_application.yml -e "env=dev"


- name: Deploy Jenkins Application Configuration
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    # コマンドラインから環境名を受け取る
    env_name: "{{ env | default('dev') }}"
    # アプリケーション設定
    restart_jenkins: "{{ restart | default(true) }}"
    install_plugins: "{{ plugins | default(true) }}"
    update_repo: "{{ update_git | default(true) }}"
  
  pre_tasks:
    # all.yml から変数を読み込む
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"
        
    # 必要な変数を設定
    - name: Set required variables from all.yml
      ansible.builtin.set_fact:
        project_name: "{{ projects.jenkins.name }}"
  
  roles:
    - jenkins_application