---
# deploy_jenkins_agent.yml
# Jenkinsインフラのエージェントリソース（SpotFleet、LaunchTemplate等）をデプロイ
#
# 使用方法 (ansibleディレクトリから実行):
#   ansible-playbook playbooks/jenkins/deploy/deploy_jenkins_agent.yml -e "env=dev"

- name: Deploy Jenkins Agent Infrastructure
  hosts: localhost
  connection: local
  gather_facts: yes
    
  vars:
    # コマンドラインから環境名を受け取る
    env_name: "{{ env | default('dev') }}"

  pre_tasks:
    # all.yml から変数を読み込む
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"
        
    # 必要な変数を設定 - ロールに渡す変数の準備
    - name: Set required variables from all.yml
      ansible.builtin.set_fact:
        project_name: "{{ infra.project_name }}"
  
  roles:
    - jenkins_agent
