---
# アプリケーション設定デプロイタスク

- name: Display application deployment information
  ansible.builtin.debug:
    msg: |
      Deploying Jenkins Application Configuration:
      - Project: {{ project_name }}
      - Application Pulumi Project: {{ application_project_name }}
      - Environment: {{ env_name }}
      - Jenkins Version: {{ jenkins_version }}
      - Install Plugins: {{ install_plugins }}
      - Update Repository: {{ update_repo }}

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true

# Pulumiデプロイ
- name: Deploy Application Configuration with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize application stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-application"
        stack_name: "{{ env_name }}"
    
    - name: Configure application stack
      ansible.builtin.shell: |
        {{ scripts_dir }}/aws-env.sh
        cd {{ pulumi_path }}/jenkins-application
        sudo -E /root/.pulumi/bin/pulumi config set aws:region {{ aws_region_name }}
        sudo -E /root/.pulumi/bin/pulumi config set {{ application_project_name }}:projectName {{ project_name }}
        sudo -E /root/.pulumi/bin/pulumi config set {{ application_project_name }}:jenkinsVersion {{ jenkins_version }}
      register: pulumi_config_result
      changed_when: pulumi_config_result.rc == 0
    
    # Pulumiプレビュー
    - name: Preview application deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-application"
    
    # Pulumiデプロイ
    - name: Deploy application stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-application"
    
    # SSMドキュメント名の取得（jenkins_configと同様の実装）
    - name: Get SSM document names
      ansible.builtin.shell: |
        cd {{ pulumi_path }}/jenkins-application
        export PULUMI_ACCESS_TOKEN="{{ lookup('env', 'PULUMI_ACCESS_TOKEN') }}"
        sudo -E /root/.pulumi/bin/pulumi stack output ssmDocuments --json 2>/dev/null || echo '{}'
      register: ssm_documents_output
      changed_when: false

    - name: Set SSM document names
      ansible.builtin.set_fact:
        ssm_documents: "{{ ssm_documents_output.stdout | from_json }}"
      when: 
        - ssm_documents_output.stdout | length > 0
        - ssm_documents_output.stdout != '{}'

    # フォールバック: デフォルト値を設定
    - name: Set default SSM document names if not found
      ansible.builtin.set_fact:
        ssm_documents:
          executeScript: "jenkins-infra-jenkins-execute-script-{{ env_name }}"
          updateRepo: "jenkins-infra-jenkins-update-repo-{{ env_name }}"
          restart: "jenkins-infra-jenkins-restart-{{ env_name }}"
      when: ssm_documents is not defined or ssm_documents | length == 0
    
    # jenkins_configのSSMドキュメントも取得（同様の実装）
    - name: Get config SSM document names
      ansible.builtin.shell: |
        cd {{ pulumi_path }}/jenkins-config
        export PULUMI_ACCESS_TOKEN="{{ lookup('env', 'PULUMI_ACCESS_TOKEN') }}"
        sudo -E /root/.pulumi/bin/pulumi stack output ssmDocuments --json 2>/dev/null || echo '{}'
      register: config_ssm_documents_output
      changed_when: false

    - name: Set config SSM document names
      ansible.builtin.set_fact:
        config_ssm_documents: "{{ config_ssm_documents_output.stdout | from_json }}"
      when: 
        - config_ssm_documents_output.stdout | length > 0
        - config_ssm_documents_output.stdout != '{}'

    # フォールバック: デフォルト値を設定
    - name: Set default config SSM document names if not found
      ansible.builtin.set_fact:
        config_ssm_documents:
          updateRepo: "jenkins-infra-jenkins-update-repo-{{ env_name }}"
          executeScript: "jenkins-infra-jenkins-execute-script-{{ env_name }}"
      when: config_ssm_documents is not defined or config_ssm_documents | length == 0
      
    - name: Display SSM document names
      ansible.builtin.debug:
        msg: |
          SSM Documents available:
          - Execute Script: {{ ssm_documents.executeScript }}
          - Restart: {{ ssm_documents.restart }}
          - Update Repo: {{ config_ssm_documents.updateRepo }}
  
  rescue:
    - name: Display error on application deployment
      ansible.builtin.debug:
        msg: "Failed to deploy Jenkins application configuration. See error details above."
      
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Jenkins application deployment failed."

# Jenkinsインスタンスの取得（Parameter Storeから）
- name: Get active Jenkins instance
  block:
    - name: Get Jenkins instance ID from SSM Parameter Store
      ansible.builtin.shell: |
        eval $({{ scripts_dir }}/aws-env.sh)
        aws ssm get-parameter \
          --name "/{{ project_name }}/{{ env_name }}/jenkins/instanceId" \
          --region {{ aws_region_name }} \
          --query "Parameter.Value" \
          --output text
      register: jenkins_instance_id_param
      changed_when: false
    
    - name: Set Jenkins instance ID
      ansible.builtin.set_fact:
        jenkins_instance_id: "{{ jenkins_instance_id_param.stdout | trim }}"
    
    - name: Verify Jenkins instance ID
      ansible.builtin.fail:
        msg: "Invalid Jenkins instance ID format: {{ jenkins_instance_id }}"
      when: not (jenkins_instance_id | regex_search('^i-[a-f0-9]+$'))
    
    - name: Display Jenkins instance ID
      ansible.builtin.debug:
        msg: "Using Jenkins Instance ID: {{ jenkins_instance_id }}"

# アプリケーション設定の実行
- name: Execute application configuration tasks
  block:
    # 0. Gitリポジトリ更新（既存のSSMドキュメントを使用）
    - name: Update Git repository
      when: update_repo | bool
      block:
        - name: Execute Git repository update
          ansible.builtin.include_tasks: tasks/execute_ssm_command.yml
          vars:
            ssm_document_name: "{{ config_ssm_documents.updateRepo }}"
            ssm_parameters: "ProjectName={{ project_name }},Environment={{ env_name }},GitBranch={{ git_branch }},GitRepo={{ git_repo }}"
            ssm_comment: "Updating Git repository"
            instance_id: "{{ jenkins_instance_id }}"
    
    # 1. Jenkinsバージョン更新
    - name: Update Jenkins version if required
      when: jenkins_version != 'latest' or update_jenkins | default(false) | bool
      block:
        - name: Execute Jenkins version update
          ansible.builtin.include_tasks: tasks/execute_ssm_command.yml
          vars:
            ssm_document_name: "{{ ssm_documents.executeScript }}"
            ssm_parameters: "ScriptPath=scripts/jenkins/shell/application-update-version.sh"
            ssm_comment: "Updating Jenkins version"
            instance_id: "{{ jenkins_instance_id }}"
    
    # 2. プラグインインストール
    - name: Install/Update Jenkins plugins
      when: install_plugins | bool
      block:
        - name: Execute plugin installation
          ansible.builtin.include_tasks: tasks/execute_ssm_command.yml
          vars:
            ssm_document_name: "{{ ssm_documents.executeScript }}"
            ssm_parameters: "ScriptPath=scripts/jenkins/shell/application-install-plugins.sh"
            ssm_comment: "Installing Jenkins plugins"
            instance_id: "{{ jenkins_instance_id }}"
    
    # 3. CLIユーザーとクレデンシャル設定（統合版）
    - name: Setup CLI user and credentials
      when: setup_cli_user | default(true) | bool
      block:
        - name: Create CLI user and setup credentials
          ansible.builtin.include_tasks: tasks/execute_ssm_command.yml
          vars:
            ssm_document_name: "{{ ssm_documents.executeScript }}"
            ssm_parameters: "ScriptPath=scripts/jenkins/shell/application-setup-cli-user-and-credentials.sh"
            ssm_comment: "Setting up CLI user and credentials"
            instance_id: "{{ jenkins_instance_id }}"
    
    # 4. SSHクレデンシャルの設定（パラメータストアから）
    - name: Setup SSH credentials from Parameter Store
      when: setup_ssh_credentials | default(true) | bool
      block:
        - name: Execute SSH credentials setup
          ansible.builtin.include_tasks: tasks/execute_ssm_command.yml
          vars:
            ssm_document_name: "{{ ssm_documents.executeScript }}"
            ssm_parameters: "ScriptPath=scripts/jenkins/shell/application-setup-ssh-credentials.sh"
            ssm_comment: "Setting up SSH credentials from Parameter Store"
            instance_id: "{{ jenkins_instance_id }}"
    
    # 5. JCasCによる統合設定（EC2 Fleet、Shared Library、セキュリティ、Workterminalノード）
    - name: Configure Jenkins using JCasC
      when: configure_with_casc | default(true) | bool
      block:
        - name: Execute JCasC configuration
          ansible.builtin.include_tasks: tasks/execute_ssm_command.yml
          vars:
            ssm_document_name: "{{ ssm_documents.executeScript }}"
            ssm_parameters: "ScriptPath=scripts/jenkins/shell/application-configure-with-casc.sh"
            ssm_comment: "Configuring Jenkins with JCasC"
            instance_id: "{{ jenkins_instance_id }}"
    
    # 6. シードジョブの作成（JCasC後に実行）
    - name: Create seed job
      when: create_seed_job | default(true) | bool
      block:
        - name: Execute seed job creation
          ansible.builtin.include_tasks: tasks/execute_ssm_command.yml
          vars:
            ssm_document_name: "{{ ssm_documents.executeScript }}"
            ssm_parameters: "ScriptPath=scripts/jenkins/shell/application-create-seed-job.sh"
            ssm_comment: "Creating Jenkins seed job"
            instance_id: "{{ jenkins_instance_id }}"
    
    # 7. Jenkins再起動
    - name: Restart Jenkins if required
      when: restart_jenkins | bool
      block:
        - name: Execute Jenkins restart
          ansible.builtin.include_tasks: tasks/execute_ssm_command.yml
          vars:
            ssm_document_name: "{{ ssm_documents.restart }}"
            ssm_parameters: ""  # 空文字列に設定
            ssm_comment: "Restarting Jenkins"
            instance_id: "{{ jenkins_instance_id }}"

# 設定完了を示す変数設定
- name: Set application deployment status
  ansible.builtin.set_fact:
    application_deployed: true

# 設定結果のサマリー表示
- name: Display application deployment summary
  ansible.builtin.debug:
    msg: |
      Jenkins Application Configuration Summary:
      - Repository Updated: {{ update_repo }}
      - Jenkins Version: {{ jenkins_version }}
      - Plugins Installed: {{ install_plugins }}
      - CLI User Setup: {{ setup_cli_user | default(true) }}
      - SSH Credentials Setup: {{ setup_ssh_credentials | default(true) }}
      - JCasC Configuration Applied: {{ configure_with_casc | default(true) }}
      - Seed Job Created: {{ create_seed_job | default(true) }}
      - Jenkins Restarted: {{ restart_jenkins }}
      - Configuration Status: {{ application_deployed | ternary('Success', 'Failed') }}
