---
# SSMコマンド実行用の共通タスク

- name: Execute SSM command - {{ ssm_comment }}
  ansible.builtin.shell: |
    eval $({{ scripts_dir }}/aws-env.sh)
    aws ssm send-command \
      --region {{ aws_region_name }} \
      --document-name "{{ ssm_document_name }}" \
      --targets "Key=instanceids,Values={{ instance_id }}" \
      --parameters "{{ ssm_parameters }}" \
      --comment "{{ ssm_comment }}" \
      --output json 2>&1 | grep -v "^export"
  register: ssm_command
  changed_when: true

- name: Parse command response
  ansible.builtin.set_fact:
    command_data: "{{ ssm_command.stdout | from_json }}"
  when: ssm_command.rc == 0

- name: Wait for command completion
  ansible.builtin.shell: |
    eval $({{ scripts_dir }}/aws-env.sh)
    aws ssm list-commands \
      --region {{ aws_region_name }} \
      --command-id "{{ command_data.Command.CommandId }}" \
      --query "Commands[0].Status" \
      --output text 2>&1 | grep -v "^export"
  register: command_status_result
  until: command_status_result.stdout in ['Success', 'Failed', 'Cancelled', 'TimedOut']
  retries: 60
  delay: 10
  when: command_data is defined

- name: Check command result
  ansible.builtin.fail:
    msg: "SSM command failed with status: {{ command_status_result.stdout }}"
  when: 
    - command_data is defined
    - command_status_result.stdout != 'Success'
