---
# Jenkins Agent AMI Builder 削除プレイブック
# EC2 Image Builderインフラを削除します
#
# 使用方法 (ansibleディレクトリから実行):
#   ansible-playbook playbooks/jenkins/remove/remove_jenkins_agent_ami.yml -e "env=dev confirm=true"
#   ansible-playbook playbooks/jenkins/remove/remove_jenkins_agent_ami.yml -e "env=dev confirm=true skip_ami_deletion=true"  # AMI削除をスキップ
#
# 注意: 
#   - 作成済みのAMIもデフォルトで削除されます
#   - skip_ami_deletion=true を指定するとAMI削除をスキップできます
#   - confirm=true を指定しないと削除は実行されません

- name: Destroy Jenkins Agent AMI Builder
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    # コマンドラインから環境名を受け取る
    env_name: "{{ env | default('dev') }}"
    # 削除確認フラグ
    confirm_destroy: "{{ confirm | default(false) }}"
  
  pre_tasks:
    # all.yml から変数を読み込む
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"
    
    # 必要な変数を設定
    - name: Set required variables from all.yml
      ansible.builtin.set_fact:
        project_name: "{{ infra.project_name }}"
        aws_region_name: "{{ infra.aws.default_region }}"
        agent_ami_project_name: "{{ infra.pulumi.agent_ami_project | default('jenkins-agent-ami') }}"
    
    - name: Check confirmation flag
      ansible.builtin.fail:
        msg: |
          ========================================
          Destruction requires confirmation.
          Please run with: -e "confirm=true"
          ========================================
      when: not confirm_destroy | bool
    
    - name: Display destruction warning
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "WARNING: Jenkins Agent AMI Builder Destruction"
          - "=========================================="
          - "Environment: {{ env_name }}"
          - "Project: {{ project_name }}"
          - "Region: {{ aws_region_name }}"
          - ""
          - "This will destroy:"
          - "  - Image Builder pipelines"
          - "  - Image Builder recipes"
          - "  - Image Builder components"
          - "  - Distribution configurations"
          - "  - Infrastructure configurations"
          - "  - IAM roles and policies"
          - ""
          - "Note: Created AMIs will also be deleted (use skip_ami_deletion=true to keep)"
          - "=========================================="
    
    - name: Countdown before destruction
      ansible.builtin.pause:
        seconds: 10
        prompt: "Starting destruction in 10 seconds... Press Ctrl+C to cancel"
  
  tasks:
    - name: Setup AWS environment
      ansible.builtin.include_role:
        name: aws_setup
    
    - name: Destroy Jenkins Agent AMI Builder
      ansible.builtin.include_role:
        name: jenkins_agent_ami
      vars:
        operation: "destroy"
  
  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Destruction Complete"
          - "=========================================="
          - "Jenkins Agent AMI Builder has been destroyed."
          - ""
          - "Removed resources:"
          - "  - Image Builder infrastructure"
          - "  - Created AMIs (unless skip_ami_deletion=true was used)"
          - "  - Associated EBS snapshots"
          - ""
          - "To delete AMIs manually:"
          - "  1. List AMIs in AWS Console or CLI"
          - "  2. Deregister AMIs"
          - "  3. Delete associated EBS snapshots"
          - "=========================================="
      when: agent_ami_destroyed | default(false)
    
    - name: Display failure message
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Destruction Failed or Incomplete"
          - "=========================================="
          - "Some resources may not have been deleted."
          - "Please check AWS Console for remaining resources."
          - ""
          - "Common cleanup targets:"
          - "  - EC2 > Image Builder"
          - "  - IAM > Roles (search for {{ project_name }})"
          - "=========================================="
      when: not (agent_ami_destroyed | default(false))