# JobDSL設定ファイル

# 共通設定
common-settings:
  # Jenkinsパイプラインリポジトリ設定
  jenkins-pipeline-repo:
    url: 'https://github.com/tielec/infrastructure-as-code'
    credentials: 'github-app-credentials'
    branch: '*/main'

# Jenkinsジョブ定義
jenkins-jobs:
  # Account Management Jobs
  account_self_activation_job:
    name: 'Activate_My_Account'
    displayName: 'Activate My Account'
    dslfile: jenkins/jobs/dsl/account-setup/account_setup_self_activation_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/account-setup/user-self-activation/Jenkinsfile

  # Admin Jobs
  admin_backup_config_job:
    name: 'Backup_Config'
    displayName: 'Backup Jenkins Configurations'
    dslfile: jenkins/jobs/dsl/admin/admin_backup_config_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/admin/backup-config/Jenkinsfile

  admin_convert_key_job:
    name: 'Convert_GitHub_App_Key'
    displayName: 'GitHub App Key Converter'
    dslfile: jenkins/jobs/dsl/admin/admin_convert_key_job.groovy

  admin_github_webhooks_setting_job:
    name: 'Github_Webhooks_Setting'
    displayName: 'GitHub Webhooks Setting Job'
    dslfile: jenkins/jobs/dsl/admin/admin_github_webhooks_setting_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/admin/github-webhooks-setting/Jenkinsfile

  admin_restore_config_job:
    name: 'Restore_Config'
    displayName: 'Restore Jenkins Configurations'
    dslfile: jenkins/jobs/dsl/admin/admin_restore_config_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/admin/restore-config/Jenkinsfile

  admin_run_script_job:
    name: 'Run_Script'
    displayName: 'Run Shell Script as Admin'
    dslfile: jenkins/jobs/dsl/admin/admin_run_script_job.groovy

  admin_test_ec2_fleet_job:
    name: 'Test_EC2_Fleet_Agent'
    displayName: 'Test EC2 Fleet Agent Functionality'
    dslfile: jenkins/jobs/dsl/admin/admin_test_ec2_fleet_job.groovy

  admin_test_github_job:
    name: 'Test_GitHub_Repository_Access'
    displayName: 'GitHub Repository Access Test Job'
    dslfile: jenkins/jobs/dsl/admin/admin_test_github_job.groovy

  admin_update_config_job:
    name: 'Update_Config'
    displayName: 'Update Jenkins Configuration with JCasC'
    dslfile: jenkins/jobs/dsl/admin/admin_update_config_job.groovy

  admin_user_management_job:
    name: 'Manage_User_Accounts'
    displayName: 'User Account Management Job'
    dslfile: jenkins/jobs/dsl/admin/admin_user_management_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/admin/user-management/Jenkinsfile

  # Code Quality Checker Jobs
  code_quality_rust_code_analysis_check_job:
    name: 'rust-code-analysis-check'
    displayName: 'Repository Code Quality Check'
    dslfile: jenkins/jobs/dsl/code-quality-checker/code_quality_rust_code_analysis_check_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/code-quality-checker/rust-code-analysis-check/Jenkinsfile

  code_quality_rust_code_analysis_check_github_trigger_job:
    name: 'rust-code-analysis-check-github-trigger'
    displayName: 'GitHub Trigger - Repository Code Quality Check'
    dslfile: jenkins/jobs/dsl/code-quality-checker/code_quality_rust_code_analysis_check_github_trigger_job.groovy
    downstreamJob: 'rust-code-analysis-check'

  code_quality_pr_complexity_analyzer_job:
    name: 'pr-complexity-analyzer'
    displayName: 'Pull Request Complexity Analyzer'
    dslfile: jenkins/jobs/dsl/code-quality-checker/code_quality_pr_complexity_analyzer_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/code-quality-checker/pr-complexity-analyzer/Jenkinsfile

  code_quality_pr_complexity_analyzer_github_trigger_job:
    name: 'pr-complexity-analyzer-github-trigger'
    displayName: 'GitHub Trigger - Pull Request Complexity Analyzer'
    dslfile: jenkins/jobs/dsl/code-quality-checker/code_quality_pr_complexity_analyzer_github_trigger_job.groovy
    downstreamJob: 'pr-complexity-analyzer'

  # Docs Generator Jobs
  docs_generator_auto_insert_doxygen_comment_job:
    name: 'auto_insert_doxygen_comment'
    displayName: 'Auto Insert Doxygen Comments'
    dslfile: jenkins/jobs/dsl/docs-generator/docs_generator_auto_insert_doxygen_comment_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/docs-generator/auto-insert-doxygen-comment/Jenkinsfile

  docs_generator_auto_insert_doxygen_comment_test_job:
    name: 'auto_insert_doxygen_comment_test'
    displayName: 'Test Auto Insert Doxygen Comments'
    dslfile: jenkins/jobs/dsl/docs-generator/docs_generator_auto_insert_doxygen_comment_test_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/docs-generator/auto-insert-doxygen-comment/tests/Jenkinsfile

  docs_generator_auto_insert_doxygen_comment_github_trigger_job:
    name: 'auto_insert_doxygen_comment_github_trigger'
    displayName: 'GitHub Trigger - Auto Insert Doxygen Comments'
    dslfile: jenkins/jobs/dsl/docs-generator/docs_generator_auto_insert_doxygen_comment_github_trigger_job.groovy
    downstreamJob: auto_insert_doxygen_comment

  docs_generator_generate_doxygen_html_job:
    name: 'generate_doxygen_html'
    displayName: 'Generate Doxygen HTML Documentation'
    dslfile: jenkins/jobs/dsl/docs-generator/docs_generator_generate_doxygen_html_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/docs-generator/generate-doxygen-html/Jenkinsfile

  docs_generator_generate_doxygen_html_github_trigger_job:
    name: 'generate_doxygen_html_github_trigger'
    displayName: 'GitHub Trigger - Generate Doxygen HTML'
    dslfile: jenkins/jobs/dsl/docs-generator/docs_generator_generate_doxygen_html_github_trigger_job.groovy
    downstreamJob: 'generate_doxygen_html'

  docx_generator_pull_request_comment_builder_job:
    name: 'pull_request_comment_builder'
    displayName: 'Build DOCX from Pull Request Comments'
    dslfile: jenkins/jobs/dsl/docs-generator/docx_generator_pull_request_comment_builder_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/docs-generator/pull-request-comment-builder/Jenkinsfile

  docx_generator_pull_request_comment_builder_github_trigger_job:
    name: 'pull_request_comment_builder_github_trigger'
    displayName: 'GitHub Trigger - Build DOCX from PR Comments'
    dslfile: jenkins/jobs/dsl/docs-generator/docx_generator_pull_request_comment_builder_github_trigger_job.groovy
    downstreamJob: 'pull_request_comment_builder'

  docs_generator_multi_pull_request_comment_builder_job:
    name: 'multi_pull_request_comment_builder'
    displayName: 'Build Docs from Multiple PR Comments'
    dslfile: jenkins/jobs/dsl/docs-generator/docs_generator_multi_pull_request_comment_builder_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/docs-generator/multi-pull-request-comment-builder/Jenkinsfile

  docs_generator_technical_docs_writer_job:
    name: 'technical-docs-writer'
    displayName: 'Technical Documentation Writer'
    dslfile: jenkins/jobs/dsl/docs-generator/docs_generator_technical_docs_writer_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/docs-generator/technical-docs-writer/Jenkinsfile

  docs_generator_technical_docs_writer_schedule_trigger_job:
    name: 'technical-docs-writer-trigger'
    displayName: 'Scheduled Technical Documentation Writer'
    dslfile: jenkins/jobs/dsl/docs-generator/docs_generator_technical_docs_writer_schedule_trigger_job.groovy
    downstreamJob: 'technical-docs-writer'

# Pulumi IaC Jobs
  infrastructure_pulumi_stack_action_test_job:
    name: "pulumi_stack_action_test"
    displayName: "Test Pulumi Stack Action"
    dslfile: jenkins/jobs/dsl/infrastructure/infrastructure_pulumi_stack_action_test_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/infrastructure/pulumi-stack-action/Jenkinsfile

  infrastructure_pulumi_stack_action_job:
    name: "pulumi_stack_action"
    displayName: "Pulumi Stack Action Job"
    dslfile: jenkins/jobs/dsl/infrastructure/infrastructure_pulumi_stack_action_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/infrastructure/pulumi-stack-action/Jenkinsfile

  infrastructure_pulumi_dashboard_job:
    name: "pulumi_dashboard"
    displayName: "Pulumi Projects Dashboard"
    dslfile: jenkins/jobs/dsl/infrastructure/infrastructure_pulumi_dashboard_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/infrastructure/pulumi-dashboard/Jenkinsfile

  # SSM Parameter Store Dashboard Job
  infrastructure_ssm_dashboard_job:
    name: "ssm_parameter_store_dashboard"
    displayName: "SSM Parameter Store Dashboard"
    dslfile: jenkins/jobs/dsl/infrastructure/infrastructure_ssm_dashboard_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/infrastructure/ssm-dashboard/Jenkinsfile

  # Ansible Playbook Executor Job
  infrastructure_ansible_playbook_executor_job:
    name: "ansible_playbook_executor"
    displayName: "Ansible Playbook Executor"
    dslfile: jenkins/jobs/dsl/infrastructure/infrastructure_ansible_playbook_executor_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/infrastructure/ansible-playbook-executor/Jenkinsfile
  
  infrastructure_lambda_verification_job:
    name: 'Lambda_Verification'
    displayName: 'Lambda Deployment Verification'
    dslfile: jenkins/jobs/dsl/infrastructure/infrastructure_lambda_verification_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/infrastructure/lambda-verification/Jenkinsfile

  # Shared Library Jobs
  shared_library_aws_sqs_check_operation_test_job:
    name: 'SQS_Check_Operation_Test'
    displayName: 'Test AWS SQS Operations'
    dslfile: jenkins/jobs/dsl/shared-library/shared_library_aws_sqs_check_operation_test_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/shared-library/test-aws-utils/sqs-check-operation/Jenkinsfile

  shared_library_git_deploykeys_operation_test_job:
    name: 'DeployKeys_Operation_Test'
    displayName: 'Test Git Deploy Keys Operations'
    dslfile: jenkins/jobs/dsl/shared-library/shared_library_git_deploykeys_operation_test_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/shared-library/test-git-utils/deploykeys-operation/Jenkinsfile

  shared_library_git_webhook_operation_test_job:
    name: 'Webhook_Operation_Test'
    displayName: 'Test Git Webhook Operations'
    dslfile: jenkins/jobs/dsl/shared-library/shared_library_git_webhook_operation_test_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/shared-library/test-git-utils/webhook-operation/Jenkinsfile

  shared_library_github_apps_basic_operation_test_job:
    name: 'GitHub_Apps_Basic_Operation_Test'
    displayName: 'GitHub Apps Basic Operations Test'
    dslfile: jenkins/jobs/dsl/shared-library/shared_library_github_apps_basic_operation_test_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/shared-library/test-git-utils/github-apps-basic-operation/Jenkinsfile

  shared_library_jenkins_credentials_operation_test_job:
    name: 'Credentials_Operation_Test'
    displayName: 'Test Jenkins Credentials Operations'
    dslfile: jenkins/jobs/dsl/shared-library/shared_library_jenkins_credentials_operation_test_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/shared-library/test-jenkins-utils/credentials-operation/Jenkinsfile

  # Infrastructure Management Jobs
  infrastructure_shutdown_environment_job:
    name: 'Shutdown_Jenkins_Environment'
    displayName: 'Shutdown Jenkins Environment'
    dslfile: jenkins/jobs/dsl/infrastructure-management/infrastructure_shutdown_environment_job.groovy
    jenkinsfile: jenkins/jobs/pipeline/infrastructure-management/shutdown-environment/Jenkinsfile

  # スケジューラージョブ（freestyleジョブのため、jenkinsfileは不要）
  infrastructure_shutdown_scheduler:
    name: 'Shutdown_Environment_Scheduler'
    displayName: 'Environment Auto Shutdown Scheduler'
    dslfile: jenkins/jobs/dsl/infrastructure-management/infrastructure_shutdown_scheduler_job.groovy
    # jenkinsfile: 不要（freestyleジョブ）

# docs-generator 生成対象リポジトリ設定
jenkins-managed-repositories:
  infrastructure-as-code:
    httpsUrl: https://github.com/tielec/infrastructure-as-code
    mainBranch: main
    docBranch: document
    credentialsId: github-app-credentials
    technicalDocsStartDate: '2025-01-01'
    technicalDocsFile: REPODOC.md
    updatePullRequestTitle: 'true'
  
  reflection-cloud-api:
    httpsUrl: https://github.com/tielec/reflection-cloud-api
    mainBranch: main
    docBranch: document
    credentialsId: github-app-credentials
    technicalDocsStartDate: '2025-01-01'
    technicalDocsFile: REPODOC.md
    updatePullRequestTitle: 'true'

# Pulumiプロジェクト定義
pulumi-projects:
  infrastructure-as-code:
    projects:
      # Lambda関連プロジェクト
      lambda_ssm_init:
        project_path: "pulumi/lambda-ssm-init"
        display_name: "Lambda SSM Init"
        project_type: "nodejs"
        description: "Lambda SSMパラメータの初期化"
        environments: ['dev', 'prod']  # 両環境に配置
      
      # Lambda Shipmentプロジェクト
      lambda_shipment_s3:
        project_path: "pulumi/lambda-shipment-s3"
        display_name: "Lambda Shipment S3"
        project_type: "nodejs"
        description: "Lambda関数デプロイメント用S3バケット"
        environments: ['dev', 'prod']  # 両環境に配置
      
      lambda_network:
        project_path: "pulumi/lambda-network"
        display_name: "Lambda Network"
        project_type: "nodejs"
        description: "Lambda用ネットワーク構成"
        environments: ['dev', 'prod']  # 両環境に配置
      
      lambda_security:
        project_path: "pulumi/lambda-security"
        display_name: "Lambda Security"
        project_type: "nodejs"
        description: "Lambdaセキュリティグループとロール"
        environments: ['dev', 'prod']  # 両環境に配置
      
      lambda_nat:
        project_path: "pulumi/lambda-nat"
        display_name: "Lambda NAT"
        project_type: "nodejs"
        description: "Lambda用NATインスタンス"
        environments: ['dev', 'prod']  # 両環境に配置
      
      lambda_vpce:
        project_path: "pulumi/lambda-vpce"
        display_name: "Lambda VPC Endpoint"
        project_type: "nodejs"
        description: "Lambda用VPCエンドポイント"
        environments: ['dev', 'prod']  # 両環境に配置
            
      lambda_functions:
        project_path: "pulumi/lambda-functions"
        display_name: "Lambda Functions"
        project_type: "nodejs"
        description: "Lambda関数定義"
        environments: ['dev', 'prod']  # 両環境に配置
      
      lambda_api_gateway:
        project_path: "pulumi/lambda-api-gateway"
        display_name: "Lambda API Gateway"
        project_type: "nodejs"
        description: "Lambda用API Gateway"
        environments: ['dev', 'prod']  # 両環境に配置
      
      # テスト用プロジェクト
      test_s3:
        project_path: "pulumi/test-s3"
        display_name: "Test S3"
        project_type: "nodejs"
        description: "S3テスト用リソース"
        environments: ['dev']  # 開発環境のみ

# Ansibleプレイブック定義
ansible-playbooks:
  infrastructure-as-code:
    playbooks:
      # Jenkins Misc
      update_jenkins_ami_ssm:
        playbook_path: "jenkins/misc/update_jenkins_ami_ssm.yml"
        display_name: "Update Jenkins AMI SSM"
        description: "Jenkins AMI SSMパラメータの更新"
        category: "jenkins-misc"
        environments: ['dev']  # 共通環境
      
      # Jenkins Maintenance
      cleanup_image_builder_amis:
        playbook_path: "jenkins/maintenance/cleanup_image_builder_amis.yml"
        display_name: "Cleanup Image Builder AMIs"
        description: "古いEC2 Image Builder AMIを定期的にクリーンアップ（保持数を超えた古いAMIを削除）"
        category: "jenkins-maintenance"
        environments: ['dev']  # 共通環境
        ansible_extra_vars: "retention_count=1 dry_run=false generate_report=true"
        schedule: "H 2 * * *"  # 毎日 UTC 2時に実行 （日本時間 11時）
      
      # Lambda
      lambda_ip_whitelist:
        playbook_path: "lambda_ip_whitelist.yml"
        display_name: "Lambda IP Whitelist"
        description: "Lambda IPホワイトリストの管理"
        category: "lambda"
        environments: ['dev', 'prod']  # 両環境に配置
      
      # Lambda Individual Deploy Playbooks
      lambda_ssm_init:
        playbook_path: "lambda/lambda_ssm_init.yml"
        display_name: "Lambda SSM Init"
        description: "Lambda SSMパラメータの初期化"
        category: "lambda-deploy"
        environments: ['dev', 'prod']
      
      lambda_network:
        playbook_path: "lambda/lambda_network.yml"
        display_name: "Lambda Network"
        description: "Lambdaネットワークインフラのデプロイ"
        category: "lambda-deploy"
        environments: ['dev', 'prod']
      
      lambda_security:
        playbook_path: "lambda/lambda_security.yml"
        display_name: "Lambda Security"
        description: "Lambdaセキュリティグループのデプロイ"
        category: "lambda-deploy"
        environments: ['dev', 'prod']
      
      lambda_vpce:
        playbook_path: "lambda/lambda_vpce.yml"
        display_name: "Lambda VPC Endpoints"
        description: "Lambda VPCエンドポイントのデプロイ"
        category: "lambda-deploy"
        environments: ['dev', 'prod']
      
      lambda_nat:
        playbook_path: "lambda/lambda_nat.yml"
        display_name: "Lambda NAT"
        description: "Lambda NATインスタンスのデプロイ"
        category: "lambda-deploy"
        environments: ['dev', 'prod']
      
      lambda_functions:
        playbook_path: "lambda/lambda_functions.yml"
        display_name: "Lambda Functions"
        description: "Lambda関数のデプロイ"
        category: "lambda-deploy"
        environments: ['dev', 'prod']
      
      lambda_api_gateway:
        playbook_path: "lambda/lambda_api_gateway.yml"
        display_name: "Lambda API Gateway"
        description: "API Gatewayのデプロイ"
        category: "lambda-deploy"
        environments: ['dev', 'prod']
      
      # Lambda Pipeline Playbooks
      lambda_setup_pipeline:
        playbook_path: "lambda_setup_pipeline.yml"
        display_name: "Lambda Setup Pipeline"
        description: "Lambda完全セットアップパイプライン"
        category: "lambda-pipeline"
        environments: ['dev', 'prod']  # 両環境に配置
      
      lambda_teardown_pipeline:
        playbook_path: "lambda_teardown_pipeline.yml"
        display_name: "Lambda Teardown Pipeline"
        description: "Lambda完全削除パイプライン"
        category: "lambda-pipeline"
        environments: ['dev', 'prod']  # 両環境に配置
      
      # Test
      test_aws_cli_helper:
        playbook_path: "test/test-aws-cli-helper.yml"
        display_name: "Test AWS CLI Helper"
        description: "AWS CLIヘルパーのテスト"
        category: "test"
        environments: ['dev']  # 開発環境のみ
      
      test_s3_validation:
        playbook_path: "test/test-s3-validation.yml"
        display_name: "Test S3 Validation"
        description: "S3バリデーションのテスト"
        category: "test"
        environments: ['dev']  # 開発環境のみ
      
      test_ssm_parameter_store:
        playbook_path: "test/test-ssm-parameter-store.yml"
        display_name: "Test SSM Parameter Store"
        description: "SSMパラメータストアのテスト"
        category: "test"
        environments: ['dev']  # 開発環境のみ
