---
# Lambda APIネットワークインフラのデプロイタスク

# SSMパラメータから設定を取得（ヘルパーロール使用）
- name: Get VPC CIDR from SSM
  ansible.builtin.include_role:
    name: ssm_parameter_store
    tasks_from: get_parameter
  vars:
    parameter_name: "/{{ project_name }}/{{ env_name }}/network/vpc-cidr"
    store_as: "vpc_cidr_param"

- name: Get isolated subnets flag from SSM
  ansible.builtin.include_role:
    name: ssm_parameter_store
    tasks_from: get_parameter
  vars:
    parameter_name: "/{{ project_name }}/{{ env_name }}/phase/isolated-subnets-enabled"
    store_as: "isolated_subnets_param"

- name: Get flow logs flag from SSM
  ansible.builtin.include_role:
    name: ssm_parameter_store
    tasks_from: get_parameter
  vars:
    parameter_name: "/{{ project_name }}/{{ env_name }}/network/enable-flow-logs"
    store_as: "flow_logs_param"

- name: Set network configuration from SSM
  ansible.builtin.set_fact:
    vpc_cidr: "{{ ssm_parameter_value | default('10.1.0.0/16') }}"
    enable_isolated_subnets: "{{ ssm_parameter_store_isolated_subnets_param | default('false') | bool }}"
    enable_flow_logs: "{{ ssm_parameter_store_flow_logs_param | default('false') | bool }}"

- name: Display network deployment information
  ansible.builtin.debug:
    msg: "Deploying Lambda API Network Infrastructure for {{ env_name }} environment"

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true

# checkモード時は早期終了
- name: Skip deployment in check mode
  ansible.builtin.debug:
    msg: "Check mode is not supported for Pulumi deployments. Please run without --check."
  when: ansible_check_mode

- name: End play in check mode
  ansible.builtin.meta: end_play
  when: ansible_check_mode

# Pulumiデプロイ
- name: Deploy Network Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize network stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-network"
        stack_name: "{{ env_name }}"
    
    - name: Configure network stack - AWS region
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-network"
        config_key: "aws:region"
        config_value: "{{ aws_region_name }}"

    - name: Configure network stack - project name
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-network"
        config_key: "{{ network_project_name }}:projectName"
        config_value: "{{ project_name }}"

    - name: Configure network stack - VPC CIDR
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-network"
        config_key: "{{ network_project_name }}:vpcCidr"
        config_value: "{{ vpc_cidr }}"

    - name: Configure network stack - isolated subnets
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-network"
        config_key: "{{ network_project_name }}:createIsolatedSubnets"
        config_value: "{{ enable_isolated_subnets | string | lower }}"

    - name: Configure network stack - flow logs
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-network"
        config_key: "{{ network_project_name }}:enableFlowLogs"
        config_value: "{{ enable_flow_logs | string | lower }}"
    
    # Pulumiプレビュー
    - name: Preview network deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-network"
      when: preview_only | default(false) | bool
    
    # Pulumiデプロイ
    - name: Deploy network stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-network"
      when: not preview_only | default(false) | bool
    
    # デプロイ成功を示す変数設定
    - name: Set network deployment status
      ansible.builtin.set_fact:
        network_deployed: true
      when: 
        - not preview_only | default(false) | bool
        - not ansible_check_mode
    
    # ネットワーク情報の表示
    - name: Display network deployment summary
      ansible.builtin.debug:
        msg: "Lambda API Network Infrastructure deployed successfully for {{ env_name }} environment"
      when: not preview_only | default(false) | bool
  
  rescue:
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Lambda API network deployment failed."
