---
# Lambda APIネットワークインフラのデプロイタスク

- name: Display network deployment information
  ansible.builtin.debug:
    msg: "Deploying Lambda API Network Infrastructure for {{ env_name }} environment"

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true

# checkモード時は早期終了
- name: Skip deployment in check mode
  ansible.builtin.debug:
    msg: "Check mode is not supported for Pulumi deployments. Please run without --check."
  when: ansible_check_mode

- name: End play in check mode
  ansible.builtin.meta: end_play
  when: ansible_check_mode

# Pulumiデプロイ
- name: Deploy Network Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize network stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-network"
        stack_name: "{{ env_name }}"
    

    # Pulumiプレビュー
    - name: Preview network deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-network"
      when: preview_only | default(false) | bool
    
    # Pulumiデプロイ
    - name: Deploy network stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-network"
      when: not preview_only | default(false) | bool
    
    # デプロイ成功を示す変数設定
    - name: Set network deployment status
      ansible.builtin.set_fact:
        network_deployed: true
      when: 
        - not preview_only | default(false) | bool
        - not ansible_check_mode
    
    # ネットワーク情報の表示
    - name: Display network deployment summary
      ansible.builtin.debug:
        msg: "Lambda API Network Infrastructure deployed successfully for {{ env_name }} environment"
      when: not preview_only | default(false) | bool
  
  rescue:
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Lambda API network deployment failed."
