---
# deploy_jenkins_nat.yml
# Jenkinsインフラの NAT リソース（NAT Gateway または NAT Instance）をデプロイ

- name: Deploy Jenkins NAT Infrastructure
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    # コマンドラインから環境名を受け取る
    env_name: "{{ env | default('dev') }}"
  
  pre_tasks:
    # all.yml から変数を読み込む
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../inventory/group_vars/all.yml"
        
    # 必要な変数を設定
    - name: Set required variables from all.yml
      ansible.builtin.set_fact:
        project_name: "{{ infra.project_name }}"
        aws_region_name: "{{ infra.aws.default_region }}"
        nat_project_name: "{{ infra.pulumi.nat_project | default('jenkins-nat') }}"
        network_project_name: "{{ infra.pulumi.network_project }}"
        security_project_name: "{{ infra.pulumi.security_project }}"
        # NAT設定
        high_availability_mode: "{{ infra.nat.high_availability_mode | default(false) }}"
        nat_instance_type: "{{ infra.nat.instance_type | default('t4g.nano') }}"
        key_name: "{{ infra.aws.key_name | default('') }}"
  
  roles:
    - jenkins_nat
