---
# deploy_jenkins_security.yml
# Jenkinsインフラのセキュリティグループをデプロイ

- name: Set local variables for security deployment
  ansible.builtin.set_fact:
    project_name: "{{ project_name_value }}"
    env_name: "{{ env_name_value }}"
    aws_region_name: "{{ aws_region_name_value }}"

- name: Deploy Security Groups with Pulumi
  block:
    - name: Display security deployment information
      ansible.builtin.debug:
        msg: |
          Deploying Security Groups:
          - Project: {{ project_name }}
          - Security Pulumi Project: {{ security_project_name }}
          - Network Pulumi Project: {{ network_project_name }}
          - Environment: {{ env_name }}
    
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize security stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/security"
        stack_name: "{{ env_name }}"
    
    - name: Configure security stack
      ansible.builtin.shell: |
        cd {{ pulumi_path }}/security
        {{ aws_env_vars }} pulumi config set aws:region {{ aws_region_name }}
        {{ aws_env_vars }} pulumi config set {{ security_project_name }}:projectName {{ project_name }}
        {{ aws_env_vars }} pulumi config set {{ security_project_name }}:networkStackName {{ network_project_name }}
      register: pulumi_config_result
      changed_when: pulumi_config_result.rc == 0
    
    # セキュリティグループのindex.tsファイルを確認
    - name: Check security/index.ts for StackReference
      ansible.builtin.shell: |
        cd {{ pulumi_path }}/security
        # ファイルの内容を表示
        echo "Checking security/index.ts content:"
        grep -n "StackReference" index.ts || echo "StackReference not found in file"
      register: stackref_check_result
      changed_when: false
    
    - name: Display StackReference check result
      ansible.builtin.debug:
        msg: "{{ stackref_check_result.stdout_lines }}"
    
    # VPC IDの確認
    - name: Get VPC ID from network stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: get_outputs
      vars:
        pulumi_project_path: "{{ pulumi_path }}/network"
        output_name: "vpcId"
        mock_output: "mock-vpc-id-for-check-mode"
    
    - name: Display VPC ID
      ansible.builtin.debug:
        msg: "Using VPC ID: {{ stack_output_result.stdout | trim }}"
    
    # Pulumiプレビュー
    - name: Preview security deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/security"
    
    # Pulumiデプロイ
    - name: Deploy security stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/security"
    
    # セキュリティグループIDの取得
    - name: Get ALB security group ID
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: get_outputs
      vars:
        pulumi_project_path: "{{ pulumi_path }}/security"
        output_name: "albSecurityGroupId"
        mock_output: "mock-alb-sg-id"
    
    - name: Set ALB security group ID
      ansible.builtin.set_fact:
        alb_sg_id: "{{ stack_output_result.stdout | trim }}"
    
    - name: Get Jenkins security group ID
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: get_outputs
      vars:
        pulumi_project_path: "{{ pulumi_path }}/security"
        output_name: "jenkinsSecurityGroupId"
        mock_output: "mock-jenkins-sg-id"
    
    - name: Set Jenkins security group ID
      ansible.builtin.set_fact:
        jenkins_sg_id: "{{ stack_output_result.stdout | trim }}"
    
    - name: Get Jenkins agent security group ID
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: get_outputs
      vars:
        pulumi_project_path: "{{ pulumi_path }}/security"
        output_name: "jenkinsAgentSecurityGroupId"
        mock_output: "mock-agent-sg-id"
    
    - name: Set Jenkins agent security group ID
      ansible.builtin.set_fact:
        jenkins_agent_sg_id: "{{ stack_output_result.stdout | trim }}"
    
    - name: Get EFS security group ID
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: get_outputs
      vars:
        pulumi_project_path: "{{ pulumi_path }}/security"
        output_name: "efsSecurityGroupId"
        mock_output: "mock-efs-sg-id"
    
    - name: Set EFS security group ID
      ansible.builtin.set_fact:
        efs_sg_id: "{{ stack_output_result.stdout | trim }}"
    
    - name: Set security facts for use in other playbooks
      ansible.builtin.set_fact:
        security_deployed: true
      
    - name: Summary of security groups deployment
      ansible.builtin.debug:
        msg: |
          Security Groups Deployed Successfully:
          ALB Security Group ID: {{ alb_sg_id }}
          Jenkins Security Group ID: {{ jenkins_sg_id }}
          Jenkins Agent Security Group ID: {{ jenkins_agent_sg_id }}
          EFS Security Group ID: {{ efs_sg_id }}
  
  rescue:
    - name: Set security deployment status on failure
      ansible.builtin.set_fact:
        security_deployed: false
      
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to deploy security groups. See error details above."
