---
# deploy_jenkins_application_v2.yml
# Jenkins Application Configuration V2 - 冪等性を考慮した段階的セットアップ

- name: Deploy Jenkins Application Configuration V2
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    # コマンドラインから環境名を受け取る
    env_name: "{{ env | default('dev') }}"
    # アプリケーション設定
    jenkins_version: "{{ version | default('latest') }}"
    jenkins_recovery_mode: "{{ recovery | default(false) }}"
    jenkins_update_plugins: "{{ update_plugins | default(true) }}"
    jenkins_create_seed_job: "{{ create_seed | default(true) }}"
    jenkins_run_seed_job: "{{ run_seed | default(false) }}"
  
  pre_tasks:
    # all.yml から変数を読み込む
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../inventory/group_vars/all.yml"
        
    # 必要な変数を設定
    - name: Set required variables from all.yml
      ansible.builtin.set_fact:
        project_name: "{{ infra.project_name }}"
        aws_region_name: "{{ infra.aws.default_region }}"
        application_project_name: "{{ infra.pulumi.application_project | default('jenkins-application') }}"
        git_repo: "{{ git_repo | default(jenkins.git.repo) }}"
        git_branch: "{{ git_branch | default(jenkins.git.branch) }}"
        jenkins_color: "{{ color | default(jenkins.color) }}"
  
  roles:
    - jenkins_application_v2
  
  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          ====================================================
          Jenkins Application V2 Configuration Complete
          ====================================================
          
          This playbook can be run multiple times safely.
          Each step checks the current state before making changes.
          
          To reset and start over:
          1. Set the phase parameter to 'not_started' in SSM
          2. Run this playbook again
          
          To skip to a specific phase:
          1. Set the phase parameter to the desired phase in SSM
          2. Run this playbook again
          
          Valid phases:
          - not_started
          - security_disabled
          - plugins_installed
          - system_configured
          - jobs_created
          - security_enabled
          - completed