---
# deploy_jenkins_network.yml
# Jenkinsインフラのネットワークリソース（VPC、サブネット等）をデプロイ

- name: Set local variables for network deployment
  ansible.builtin.set_fact:
    project_name: "{{ project_name_value }}"
    env_name: "{{ env_name_value }}"
    aws_region_name: "{{ aws_region_name_value }}"

- name: Deploy Network Infrastructure with Pulumi
  block:
    - name: Display network deployment information
      ansible.builtin.debug:
        msg: |
          Deploying Network Infrastructure:
          - Project: {{ project_name }}
          - Network Pulumi Project: {{ network_project_name }}
          - Environment: {{ env_name }}
          - VPC CIDR: {{ vpc_cidr | default('10.0.0.0/16') }}
    
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize network stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/network"
        stack_name: "{{ env_name }}"
    
    - name: Configure network stack
      ansible.builtin.shell: |
        cd {{ pulumi_path }}/network
        source {{ playbook_dir }}/../../scripts/aws-env.sh 
        eval $({{ playbook_dir }}/../../scripts/aws-env.sh)
        
        sudo -E /root/.pulumi/bin/pulumi config set aws:region {{ aws_region_name }}
        sudo -E /root/.pulumi/bin/pulumi config set {{ network_project_name }}:projectName {{ project_name }}
        sudo -E /root/.pulumi/bin/pulumi config set {{ network_project_name }}:vpcCidr {{ vpc_cidr | default('10.0.0.0/16') }}
      register: pulumi_config_result
      changed_when: pulumi_config_result.rc == 0


    # Pulumiプレビュー
    - name: Preview network deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/network"
    
    # Pulumiデプロイ
    - name: Deploy network stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/network"
    
    # スタック出力の取得
    - name: Get VPC ID from stack outputs
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: get_outputs
      vars:
        pulumi_project_path: "{{ pulumi_path }}/network"
        output_name: "vpcId"
        mock_output: "mock-vpc-id-for-check-mode"
    
    - name: Set VPC ID
      ansible.builtin.set_fact:
        vpc_id: "{{ stack_output_result.stdout | trim }}"
    
    - name: Get public subnet IDs
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: get_outputs
      vars:
        pulumi_project_path: "{{ pulumi_path }}/network"
        output_name: "publicSubnetIds"
        mock_output: "['mock-public-subnet-1','mock-public-subnet-2']"
    
    - name: Set public subnet IDs
      ansible.builtin.set_fact:
        public_subnet_ids: "{{ stack_output_result.stdout | trim }}"
    
    - name: Get private subnet IDs
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: get_outputs
      vars:
        pulumi_project_path: "{{ pulumi_path }}/network"
        output_name: "privateSubnetIds"
        mock_output: "['mock-private-subnet-1','mock-private-subnet-2']"
    
    - name: Set private subnet IDs
      ansible.builtin.set_fact:
        private_subnet_ids: "{{ stack_output_result.stdout | trim }}"
    
    - name: Set network facts for use in other playbooks
      ansible.builtin.set_fact:
        network_deployed: true
        # スタック参照情報も保存
        network_stack_name: "{{ network_project_name }}"
      
    - name: Summary of network deployment
      ansible.builtin.debug:
        msg: |
          Network Infrastructure Deployed Successfully:
          Stack Name: {{ network_project_name }}
          VPC ID: {{ vpc_id }}
          Public Subnet IDs: {{ public_subnet_ids }}
          Private Subnet IDs: {{ private_subnet_ids }}
  
  rescue:
    - name: Set network deployment status on failure
      ansible.builtin.set_fact:
        network_deployed: false
      
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to deploy network infrastructure. See error details above."
      
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Network deployment failed."
