---
# deploy_jenkins_ssm_init.yml
# SSMパラメータストアの初期化を実行

- name: Initialize SSM Parameter Store for Jenkins Infrastructure
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    # コマンドラインから環境名を受け取る
    env_name: "{{ env | default('dev') }}"
    # パスを明示的に定義
    scripts_dir: "{{ playbook_dir }}/../../scripts"
    pulumi_path: "{{ playbook_dir }}/../../pulumi"
  
  pre_tasks:
    # all.yml から変数を読み込む
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../inventory/group_vars/all.yml"
        
    # 必要な変数を設定
    - name: Set required variables from all.yml
      ansible.builtin.set_fact:
        project_name: "{{ infra.project_name }}"
        aws_region_name: "{{ infra.aws.default_region }}"
  
  roles:
    - aws_setup
    - pulumi_helper
    - jenkins_ssm_init
  
  post_tasks:
    - name: Display SSM initialization summary
      ansible.builtin.debug:
        msg: |
          SSM Parameter Store Initialization Summary
          ==========================================
          Environment: {{ env_name }}
          AWS Region: {{ aws_region_name }}
          Project: {{ project_name }}
          Status: {{ 'SUCCESS' if ssm_initialized | default(false) else 'FAILED' }}
          
          {% if ssm_initialized | default(false) %}
          SSM parameters have been successfully initialized.
          You can now deploy other infrastructure components.
          {% else %}
          SSM parameter initialization failed.
          Please check the error messages above.
          {% endif %}