---
# jenkins_teardown_pipeline.yml
# Jenkins環境削除の全体フローを管理するプレイブック
# 各remove_jenkins_*.ymlプレイブックを逆順で実行

- name: Jenkins Infrastructure Teardown Pipeline
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    # 環境名はコマンドラインから指定可能
    env_name: "{{ env | default('dev') }}"
    # 削除確認フラグ（必須）
    confirm: "{{ confirm | default(false) }}"
  
  tasks:
    # 削除確認（重要）
    - name: Critical confirmation check
      ansible.builtin.fail:
        msg: |
          ================================================================
          CRITICAL WARNING: COMPLETE INFRASTRUCTURE DELETION
          ================================================================
          
          This will PERMANENTLY DELETE the entire Jenkins infrastructure
          for environment '{{ env_name }}'.
          
          ⚠️  THIS ACTION CANNOT BE UNDONE!
          ⚠️  ALL JENKINS DATA WILL BE PERMANENTLY DELETED!
          
          To proceed with deletion, run with: --extra-vars "confirm=true"
          ================================================================
      when: not confirm | bool
    
    - name: Starting teardown process
      ansible.builtin.debug:
        msg: "Deletion confirmed. Starting infrastructure teardown for environment '{{ env_name }}'..."
      when: confirm | bool
    # 削除順序は作成順序の逆（依存関係を考慮）
    
    # Jenkinsアプリケーション設定の削除
    - name: Destroy Jenkins Application Configuration
      ansible.builtin.import_playbook: remove_jenkins_application.yml
      vars:
        env: "{{ env_name }}"
        confirm: true
      when: destroy_application | default(true) | bool
      tags:
        - application
    
    # Jenkinsエージェントの削除
    - name: Destroy Jenkins Agent
      ansible.builtin.import_playbook: remove_jenkins_agent.yml
      vars:
        env: "{{ env_name }}"
        confirm: true
      when: destroy_agent | default(true) | bool
      tags:
        - agent
    
    # Jenkins Agent AMIの削除
    - name: Destroy Jenkins Agent AMI Images
      ansible.builtin.import_playbook: remove_jenkins_agent_ami.yml
      vars:
        env: "{{ env_name }}"
        confirm: true
      when: destroy_agent_ami | default(false) | bool
      tags:
        - agent-ami
    
    # Jenkins設定の削除
    - name: Destroy Jenkins Configuration
      ansible.builtin.import_playbook: remove_jenkins_config.yml
      vars:
        env: "{{ env_name }}"
        confirm: true
      when: destroy_config | default(true) | bool
      tags:
        - config
    
    # Jenkinsコントローラーの削除
    - name: Destroy Jenkins Controller
      ansible.builtin.import_playbook: remove_jenkins_controller.yml
      vars:
        env: "{{ env_name }}"
        confirm: true
      when: destroy_controller | default(true) | bool
      tags:
        - controller
    
    # ロードバランサーの削除
    - name: Destroy LoadBalancer Infrastructure
      ansible.builtin.import_playbook: remove_jenkins_loadbalancer.yml
      vars:
        env: "{{ env_name }}"
        confirm: true
      when: destroy_loadbalancer | default(true) | bool
      tags:
        - loadbalancer
    
    # ストレージ（EFS）の削除
    - name: Destroy Storage Infrastructure (EFS)
      ansible.builtin.import_playbook: remove_jenkins_storage.yml
      vars:
        env: "{{ env_name }}"
        confirm: true
      when: destroy_storage | default(true) | bool
      tags:
        - storage
    
    # NATインフラの削除
    - name: Destroy NAT Infrastructure
      ansible.builtin.import_playbook: remove_jenkins_nat.yml
      vars:
        env: "{{ env_name }}"
        confirm: true
      when: destroy_nat | default(true) | bool
      tags:
        - nat
    
    # セキュリティグループの削除
    - name: Destroy Security Groups
      ansible.builtin.import_playbook: remove_jenkins_security.yml
      vars:
        env: "{{ env_name }}"
        confirm: true
      when: destroy_security | default(true) | bool
      tags:
        - security
    
    # ネットワークインフラの削除
    - name: Destroy Network Infrastructure
      ansible.builtin.import_playbook: remove_jenkins_network.yml
      vars:
        env: "{{ env_name }}"
        confirm: true
      when: destroy_network | default(true) | bool
      tags:
        - network
    
    # SSMパラメータストアの削除（最後に実行）
    - name: Destroy SSM Parameter Store
      ansible.builtin.import_playbook: remove_jenkins_ssm_init.yml
      vars:
        env: "{{ env_name }}"
        confirm: true
      when: destroy_ssm_init | default(true) | bool
      tags:
        - ssm-init

- name: Teardown Complete
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Display teardown summary
      ansible.builtin.debug:
        msg: |
          Jenkins Infrastructure Teardown Complete
          =========================================
          
          Environment: {{ env_name }}
          
          All specified components have been processed for deletion.
          
          ⚠️  Note: Some AWS resources may take a few minutes to fully terminate.
          
          Post-Deletion Checklist:
          ========================
          1. Verify in AWS Console that all resources are deleted
          2. Check CloudWatch Logs for any remaining log groups
          3. Review AWS Cost Explorer for any lingering charges
          4. Remove any local Pulumi state backups if no longer needed
          5. Consider rotating any credentials that were used
