---
# jenkins-setup-pipeline.yml
# Jenkins環境構築の全体フローを管理するプレイブック

- name: Jenkins Infrastructure Setup Pipeline
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    # 環境名はコマンドラインから指定可能
    env_name: "{{ env | default('dev') }}"
    # 共通設定から参照
    project_name: "{{ infra.project_name }}"
    aws_region_name: "{{ infra.aws.default_region }}"
    pulumi_path: "{{ playbook_dir }}/../../pulumi"
    
  tasks:
    - name: Display pipeline information
      ansible.builtin.debug:
        msg: |
          Jenkins Infrastructure Setup Pipeline
          ==================================
          Project: {{ project_name }}
          Environment: {{ env_name }}
          AWS Region: {{ aws_region_name }}
          
          Pulumi Projects:
          - Network: {{ infra.pulumi.network_project }}
          - Security: {{ infra.pulumi.security_project }}
    
    - name: Check Ansible version
      ansible.builtin.debug:
        msg: "Ansible version: {{ ansible_version.full }}"
    
    - name: Check AWS credentials
      ansible.builtin.shell: aws sts get-caller-identity
      register: aws_identity
      changed_when: false
      ignore_errors: yes
      
    - name: Display AWS identity
      ansible.builtin.debug:
        msg: "AWS Identity: {{ aws_identity.stdout }}"
      when: aws_identity.rc == 0
      
    - name: Warning about AWS credentials
      ansible.builtin.debug:
        msg: "WARNING: AWS credentials not configured or not working properly"
      when: aws_identity.rc != 0
    
    # ネットワークインフラのデプロイ
    - name: Deploy Network Infrastructure
      ansible.builtin.include_tasks: 
        file: deploy_jenkins_network.yml
        apply:
          vars:
            # 共通変数を渡す
            network_project_name: "{{ infra.pulumi.network_project }}"
      
    # ネットワークデプロイが成功したらセキュリティグループをデプロイ
    - name: Deploy Security Groups
      ansible.builtin.include_tasks: 
        file: deploy_jenkins_security.yml
        apply:
          vars:
            # 共通変数を渡す
            security_project_name: "{{ infra.pulumi.security_project }}"
            network_project_name: "{{ infra.pulumi.network_project }}"
      when: network_deployed is defined and network_deployed

    # デプロイメント結果サマリー
    - name: Deployment Summary
      ansible.builtin.debug:
        msg: |
          Jenkins Infrastructure Deployment Summary
          =======================================
          Network: {{ network_deployed | default(false) }}
          Security: {{ security_deployed | default(false) }}
          
          # 今後追加予定:
          # Storage: (Not deployed yet)
          # Load Balancer: (Not deployed yet)
          # Jenkins Controller: (Not deployed yet)
          # Jenkins Agent: (Not deployed yet)
          # Jenkins Application: (Not deployed yet)
