---
# remove_jenkins_nat.yml
# Jenkins NAT Gateway/Instanceを削除
#
# 使用方法:
#   ansible-playbook remove_jenkins_nat.yml -e "env=dev confirm=true"
#
# 注意:
#   - confirm=true を指定しないと削除は実行されません
#   - プライベートサブネットからのインターネットアクセスが不可能になります

- name: Destroy Jenkins NAT Gateway/Instance
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    # コマンドラインから環境名を受け取る
    env_name: "{{ env | default('dev') }}"
    # 削除確認フラグ
    confirm_destroy: "{{ confirm | default(false) }}"
  
  pre_tasks:
    # all.yml から変数を読み込む
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../inventory/group_vars/all.yml"
    
    # 必要な変数を設定
    - name: Set required variables from all.yml
      ansible.builtin.set_fact:
        project_name: "{{ infra.project_name }}"
        aws_region_name: "{{ infra.aws.default_region }}"
        nat_project_name: "{{ infra.pulumi.nat_project }}"
        use_nat_instance: "{{ infra.aws.nat.use_instance | default(false) }}"
    
    - name: Check confirmation flag
      ansible.builtin.fail:
        msg: |
          ========================================
          Destruction requires confirmation.
          Please run with: -e "confirm=true"
          ========================================
      when: not confirm_destroy | bool
    
    - name: Display destruction warning
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "WARNING: Jenkins NAT Destruction"
          - "=========================================="
          - "Environment: {{ env_name }}"
          - "Project: {{ project_name }}"
          - "Region: {{ aws_region_name }}"
          - "Type: {{ 'NAT Instance' if use_nat_instance else 'NAT Gateway' }}"
          - ""
          - "This will destroy:"
          - "  - {{ 'NAT Instance (EC2)' if use_nat_instance else 'NAT Gateway' }}"
          - "  - Elastic IP allocation"
          - "  - Route table associations"
          - ""
          - "Impact:"
          - "  - Private subnet resources lose internet access"
          - "  - Jenkins agents cannot download packages"
          - "  - No outbound internet connectivity"
          - "=========================================="
    
    - name: Countdown before destruction
      ansible.builtin.pause:
        seconds: 10
        prompt: "Starting destruction in 10 seconds... Press Ctrl+C to cancel"
  
  tasks:
    - name: Setup AWS environment
      ansible.builtin.include_role:
        name: aws_setup
    
    - name: Destroy Jenkins NAT
      ansible.builtin.include_role:
        name: jenkins_nat
      vars:
        operation: "destroy"
  
  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Destruction Complete"
          - "=========================================="
          - "Jenkins NAT has been destroyed."
          - ""
          - "Removed resources:"
          - "  - {{ 'NAT Instance' if use_nat_instance else 'NAT Gateway' }}"
          - "  - Elastic IP"
          - "  - Route configurations"
          - ""
          - "Impact on environment:"
          - "  - Private subnets have no internet access"
          - "  - Jenkins agents cannot reach external repositories"
          - ""
          - "To restore connectivity:"
          - "  ansible-playbook deploy_jenkins_nat.yml -e 'env={{ env_name }}'"
          - "=========================================="
      when: nat_destroyed | default(false)
    
    - name: Display failure message
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Destruction Failed or Incomplete"
          - "=========================================="
          - "Some resources may not have been deleted."
          - "Please check AWS Console for remaining resources."
          - ""
          - "Common cleanup targets:"
          - "  - VPC > NAT Gateways"
          - "  - EC2 > Instances (if using NAT instance)"
          - "  - VPC > Elastic IPs"
          - ""
          - "Note: NAT Gateway deletion may take several minutes"
          - "=========================================="
      when: not (nat_destroyed | default(false))