---
# ansible/playbooks/test-ssm-basic.yml
# 基本的なSSMパラメータ操作のテスト
- name: Basic SSM Parameter Store test
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    test_param: "/ansible-test/basic-{{ ansible_date_time.epoch[-4:] }}"
    
  tasks:
    # ==================== 基本テスト ====================
    - name: Basic parameter operations
      block:
        # 1. ロールの初期化
        - name: Initialize role
          ansible.builtin.include_role:
            name: ssm_parameter_store

        # 2. パラメータの作成
        - name: Create parameter
          ansible.builtin.include_role:
            name: ssm_parameter_store
            tasks_from: set_parameter
          vars:
            parameter_name: "{{ test_param }}"
            parameter_value: "test-value-123"

        - name: Show create result
          ansible.builtin.debug:
            msg: "Create success: {{ ssm_operation_success }}"

        # 3. パラメータの取得
        - name: Get parameter
          ansible.builtin.include_role:
            name: ssm_parameter_store
            tasks_from: get_parameter
          vars:
            parameter_name: "{{ test_param }}"

        - name: Show get result
          ansible.builtin.debug:
            msg: |
              Get success: {{ ssm_operation_success }}
              Value: {{ ssm_parameter_value }}
              Expected: test-value-123
              Match: {{ ssm_parameter_value == 'test-value-123' }}

        # 4. パラメータの更新
        - name: Update parameter
          ansible.builtin.include_role:
            name: ssm_parameter_store
            tasks_from: set_parameter
          vars:
            parameter_name: "{{ test_param }}"
            parameter_value: "updated-value-456"

        - name: Get updated parameter
          ansible.builtin.include_role:
            name: ssm_parameter_store
            tasks_from: get_parameter
          vars:
            parameter_name: "{{ test_param }}"

        - name: Show update result
          ansible.builtin.debug:
            msg: |
              Update success: {{ ssm_operation_success }}
              New value: {{ ssm_parameter_value }}
              Expected: updated-value-456
              Match: {{ ssm_parameter_value == 'updated-value-456' }}

        # 5. パラメータの削除
        - name: Delete parameter
          ansible.builtin.include_role:
            name: ssm_parameter_store
            tasks_from: delete_parameter
          vars:
            parameter_name: "{{ test_param }}"

        - name: Show delete result
          ansible.builtin.debug:
            msg: "Delete success: {{ ssm_operation_success }}"

        # 6. 削除確認
        - name: Try to get deleted parameter
          ansible.builtin.include_role:
            name: ssm_parameter_store
            tasks_from: get_parameter
          vars:
            parameter_name: "{{ test_param }}"
            ssm_parameter_store_fail_on_missing: false

        - name: Show deletion confirmed
          ansible.builtin.debug:
            msg: "Parameter deleted: {{ not ssm_operation_success }}"

        # 最終結果
        - name: All tests passed
          ansible.builtin.debug:
            msg: |
              ========================================
              ✓ All basic tests passed!
              - Create: OK
              - Get: OK
              - Update: OK
              - Delete: OK
              ========================================

      rescue:
        - name: Test failed
          ansible.builtin.debug:
            msg: |
              ========================================
              ✗ Test failed!
              Task: {{ ansible_failed_task.name | default('Unknown') }}
              Error: {{ ansible_failed_result.msg | default('Unknown error') }}
              ========================================

        # クリーンアップ
        - name: Cleanup on failure
          ansible.builtin.shell: |
            aws ssm delete-parameter \
              --name "{{ test_param }}" \
              --region ap-northeast-1 2>/dev/null || true
          failed_when: false