# AWS CLIコマンドを実行する基本タスク
#
# 必須変数:
#   - aws_command: 実行するAWS CLIコマンド（リージョンは自動追加）
#   - operation_name: 操作名（ログ用）
#
# オプション変数:
#   - no_log_output: 出力をマスクするか (default: false)
#   - parse_output: JSONとしてパースするか (default: true)
#   - timeout: タイムアウト秒数 (default: aws_cli_helper_timeout)
#   - environment: 追加の環境変数
#
# 戻り値:
#   - aws_cli_result: 生の実行結果
#   - aws_cli_success: 成功/失敗フラグ
#   - aws_cli_stdout: 標準出力
#   - aws_cli_stderr: 標準エラー出力
#   - aws_cli_data: パース済みJSONデータ（parse_output=true時）
#   - aws_cli_error_type: エラータイプ（失敗時）

- name: Validate required variables
  ansible.builtin.assert:
    that:
      - aws_command is defined
      - operation_name is defined
    fail_msg: "Required variables 'aws_command' and 'operation_name' must be defined"

# リージョンが含まれていない場合は追加
- name: Prepare AWS command with region
  ansible.builtin.set_fact:
    _aws_command_with_region: >-
      {%- if '--region' not in aws_command -%}
        {{ aws_command }} --region {{ aws_cli_helper_region }}
      {%- else -%}
        {{ aws_command }}
      {%- endif -%}

# AWS CLIコマンドを実行
- name: "Execute AWS CLI: {{ operation_name }}"
  ansible.builtin.shell: |
    set -o pipefail
    {{ _aws_command_with_region }}
  args:
    executable: /bin/bash
  register: _aws_cli_raw_result
  no_log: "{{ no_log_output | default(false) }}"
  failed_when: false
  timeout: "{{ timeout | default(aws_cli_helper_timeout) }}"
  environment: "{{ environment | default({}) | combine({'AWS_DEFAULT_REGION': aws_cli_helper_region}) }}"

# 基本的な結果を設定
- name: Set basic execution results
  ansible.builtin.set_fact:
    aws_cli_result: "{{ _aws_cli_raw_result }}"
    aws_cli_success: "{{ _aws_cli_raw_result.rc == 0 }}"
    aws_cli_stdout: "{{ _aws_cli_raw_result.stdout | default('') }}"
    aws_cli_stderr: "{{ _aws_cli_raw_result.stderr | default('') }}"
  no_log: "{{ no_log_output | default(false) }}"

# エラー解析
- name: Analyze error if failed
  when: not aws_cli_success
  ansible.builtin.include_tasks: check_error.yml
  vars:
    error_output: "{{ aws_cli_stderr }}"

# JSON出力のパース
- name: Parse JSON output if requested
  when:
    - aws_cli_success
    - parse_output | default(true)
    - aws_cli_stdout | length > 0
  ansible.builtin.include_tasks: parse_json.yml
  vars:
    json_string: "{{ aws_cli_stdout }}"

# デフォルト値の設定
- name: Set default values for unsuccessful parsing
  ansible.builtin.set_fact:
    aws_cli_data: {}
  when: aws_cli_data is not defined

# デバッグ出力
- name: Debug AWS CLI execution
  when: aws_cli_helper_debug
  ansible.builtin.debug:
    msg: |
      Operation: {{ operation_name }}
      Command: {{ aws_command | regex_replace('--value\s+"[^"]*"', '--value "***"') }}
      Success: {{ aws_cli_success }}
      {% if not aws_cli_success %}
      Error Type: {{ aws_cli_error_type | default('Unknown') }}
      Error: {{ aws_cli_stderr | truncate(200) }}
      {% endif %}
