# アプリケーションロールのデフォルト変数

# パスがプレイブックからの相対パスになるよう修正
scripts_dir: "{{ playbook_dir }}/../../scripts"
pulumi_path: "{{ playbook_dir }}/../../pulumi"

# 環境名のデフォルト値
env_name: "dev"

# アプリケーション設定のデフォルト値
jenkins_version: "latest"
install_plugins: true
create_seed_job: true
restart_jenkins: true
setup_cli_user: true
