---
# lambda_nat.yml
# Lambda API用NATインフラデプロイメントプレイブック
# 
# 使用方法:
#   ansible-playbook playbooks/lambda/lambda_nat.yml -e "env=dev"
#   ansible-playbook playbooks/lambda/lambda_nat.yml -e "env=dev operation=destroy"

- name: Lambda API NAT Infrastructure Deployment
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    env_name: "{{ env | default('dev') }}"
    preview_only: "{{ preview | default(false) }}"
    
  pre_tasks:
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"
    
    - name: Set required variables
      ansible.builtin.set_fact:
        project_name: "{{ lambda_api_infra.project_name }}"
        aws_region_name: "{{ lambda_api_infra.aws.default_region }}"
        nat_project_name: "{{ lambda_api_infra.pulumi.nat_project }}"
        pulumi_path: "{{ inventory_dir }}/../../pulumi"
        scripts_dir: "{{ inventory_dir }}/../../scripts"
        environment_config: "{{ lambda_api_infra.environments[env_name] }}"
        high_availability_mode: "{{ environment_config.nat_high_availability | default(lambda_api_infra.nat.high_availability_mode) }}"
        nat_instance_type: "{{ environment_config.nat_instance_type | default(lambda_api_infra.nat.instance_type) }}"
        key_name: "{{ lambda_api_infra.aws.key_name | default('') }}"
        
    - name: Display operation info
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda API NAT Infrastructure
          ==========================================
          Operation: {{ operation | default('deploy') }}
          Environment: {{ env_name }}
          Project: {{ nat_project_name }}
          Region: {{ aws_region_name }}
          NAT Mode: {{ 'High Availability (NAT Gateway)' if high_availability_mode else 'Normal (NAT Instance)' }}
          {% if not high_availability_mode %}
          Instance Type: {{ nat_instance_type }}
          {% endif %}
          Preview Only: {{ preview_only }}
          ==========================================
          
    - name: Check dependencies
      block:
        - name: Check network deployment
          ansible.builtin.include_role:
            name: ssm_parameter_store
            tasks_from: get_parameter
          vars:
            parameter_name: "/{{ project_name }}/{{ env_name }}/network/vpc-id"
            store_as: "vpc_check"
            default_value: ""
            ssm_parameter_store_fail_on_missing: false
            
        - name: Check security groups deployment
          ansible.builtin.include_role:
            name: ssm_parameter_store
            tasks_from: get_parameter
          vars:
            parameter_name: "/{{ project_name }}/{{ env_name }}/security/nat-sg-id"
            store_as: "sg_check"
            default_value: ""
            ssm_parameter_store_fail_on_missing: false
            
    - name: Verify dependencies
      ansible.builtin.fail:
        msg: |
          Dependencies not met!
          {% if vpc_check | default('') | length == 0 %}
          - Network infrastructure is not deployed
          {% endif %}
          {% if sg_check | default('') | length == 0 %}
          - Security groups are not deployed
          {% endif %}
          
          Please deploy missing components first.
      when:
        - operation | default('deploy') == 'deploy'
        - (vpc_check | default('') | length == 0 or sg_check | default('') | length == 0)
  
  roles:
    - aws_setup
    - pulumi_helper
    
  tasks:

    - name: Set operation variable
      ansible.builtin.set_fact:
        role_operation: "{{ operation | default('deploy') }}"
        
    - name: Execute NAT deployment
      ansible.builtin.include_role:
        name: lambda_nat
      vars:
        operation: "{{ role_operation }}"
        
    - name: Display results
      ansible.builtin.debug:
        msg: |
          ==========================================
          NAT Infrastructure {{ 'Preview' if preview_only else role_operation | title }} Complete
          ==========================================
          {% if role_operation == 'deploy' and not preview_only %}
          Status: {{ 'Success' if nat_deployed | default(false) else 'Failed' }}
          NAT Type: {{ nat_type | default('N/A') }}
          
          Next step:
          ansible-playbook playbooks/lambda/lambda_functions.yml -e "env={{ env_name }}"
          {% elif role_operation == 'destroy' %}
          NAT infrastructure has been removed.
          {% endif %}