---
# lambda_account_setup.yml
# Lambda APIアカウントレベル設定プレイブック
#
# 注意: これはAWSアカウント全体で1回だけ実行する設定です
#       環境（dev/staging/prod）に依存しません
#
# 使用方法:
#   ansible-playbook playbooks/lambda/lambda_account_setup.yml
#   ansible-playbook playbooks/lambda/lambda_account_setup.yml -e "operation=destroy"

- name: Lambda Account Setup Deployment
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    env_name: "{{ env | default('dev') }}"
    preview_only: "{{ preview | default(false) }}"

  pre_tasks:
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"

    - name: Set required variables
      ansible.builtin.set_fact:
        project_name: "{{ projects.lambda_api.name }}"

    - name: Display operation info
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda Account Setup Deployment
          ==========================================
          Operation: {{ operation | default('deploy') }}
          Environment: {{ env_name }}
          Project: {{ project_name }}-account-setup
          Region: {{ aws_region }}
          Preview Only: {{ preview_only }}
          ==========================================

  roles:
    - aws_setup
    - pulumi_helper

  tasks:

    - name: Set operation variable
      ansible.builtin.set_fact:
        role_operation: "{{ operation | default('deploy') }}"

    - name: Execute Lambda Account Setup deployment
      ansible.builtin.include_role:
        name: lambda_account_setup
      vars:
        operation: "{{ role_operation }}"

    - name: Display results
      ansible.builtin.debug:
        msg: |
          ==========================================
          Lambda Account Setup {{ 'Preview' if preview_only else role_operation | title }} Complete
          ==========================================
          {% if role_operation == 'deploy' and not preview_only %}
          Status: {{ 'Success' if account_setup_deployed | default(false) else 'Failed' }}

          API Gateway CloudWatch Logs role has been configured.

          Next step:
          ansible-playbook playbooks/lambda/lambda_ssm_init.yml -e "env={{ env_name }}"
          {% elif role_operation == 'destroy' %}
          Lambda account setup has been removed.
          Note: This may affect API Gateway logging functionality.
          {% endif %}