---
# lambda_websocket.yml
# WebSocket APIデプロイメントプレイブック（オプション）
# 
# 使用方法:
#   ansible-playbook playbooks/lambda/lambda_websocket.yml -e "env=dev"
#   ansible-playbook playbooks/lambda/lambda_websocket.yml -e "env=dev operation=destroy"

- name: WebSocket API Deployment
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    env_name: "{{ env | default('dev') }}"
    preview_only: "{{ preview | default(false) }}"
    
  pre_tasks:
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"
    
    - name: Set required variables
      ansible.builtin.set_fact:
        project_name: "{{ lambda_api_infra.project_name }}"
        aws_region_name: "{{ lambda_api_infra.aws.default_region }}"
        websocket_project_name: "{{ lambda_api_infra.pulumi.websocket_project }}"
        pulumi_path: "{{ inventory_dir }}/../../pulumi"
        scripts_dir: "{{ inventory_dir }}/../../scripts"
        environment_config: "{{ lambda_api_infra.environments[env_name] }}"
        enable_websocket: "{{ environment_config.enable_websocket | default(false) }}"
        
    - name: Display operation info
      ansible.builtin.debug:
        msg: |
          ==========================================
          WebSocket API Deployment
          ==========================================
          Operation: {{ operation | default('deploy') }}
          Environment: {{ env_name }}
          Project: {{ websocket_project_name }}
          Region: {{ aws_region_name }}
          WebSocket Enabled: {{ enable_websocket }}
          Preview Only: {{ preview_only }}
          ==========================================
          
    - name: Skip if WebSocket is not enabled
      ansible.builtin.debug:
        msg: "WebSocket API is not enabled for {{ env_name }} environment. Skipping deployment."
      when: not enable_websocket
      
    - name: Check Lambda functions deployment
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/{{ project_name }}/{{ env_name }}/lambda/functions-deployed"
        store_as: "functions_check"
        default_value: "false"
        ssm_parameter_store_fail_on_missing: false
      when: enable_websocket
        
    - name: Verify Lambda functions deployment
      ansible.builtin.fail:
        msg: |
          Lambda functions are not deployed!
          Please run: ansible-playbook playbooks/lambda/lambda_functions.yml -e "env={{ env_name }}"
      when:
        - enable_websocket
        - operation | default('deploy') == 'deploy'
        - functions_check | default('false') != 'true'
  
  roles:
    - aws_setup
    - pulumi_helper
    
  tasks:
    - name: Set operation variable
      ansible.builtin.set_fact:
        role_operation: "{{ operation | default('deploy') }}"
        
    - name: Execute WebSocket API deployment
      ansible.builtin.include_role:
        name: lambda_websocket
      vars:
        operation: "{{ role_operation }}"
      when: enable_websocket
        
    - name: Display results
      ansible.builtin.debug:
        msg: |
          ==========================================
          WebSocket API {{ 'Preview' if preview_only else operation | title }} Complete
          ==========================================
          {% if enable_websocket %}
          {% if operation | default('deploy') == 'deploy' and not preview_only %}
          Status: {{ 'Success' if websocket_deployed | default(false) else 'Failed' }}
          WebSocket Endpoint: {{ websocket_endpoint | default('Not available') }}
          
          Optional next step:
          - Database: ansible-playbook playbooks/lambda/lambda_database.yml -e "env={{ env_name }}"
          {% elif operation == 'destroy' %}
          WebSocket API has been removed.
          {% endif %}
          {% else %}
          WebSocket API is not enabled for this environment.
          {% endif %}