---
# lambda_waf.yml
# WAFデプロイメントプレイブック（オプション）
# 
# 使用方法:
#   ansible-playbook playbooks/lambda/lambda_waf.yml -e "env=dev"
#   ansible-playbook playbooks/lambda/lambda_waf.yml -e "env=dev operation=destroy"

- name: WAF Deployment for API Gateway
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    env_name: "{{ env | default('dev') }}"
    operation: "{{ operation | default('deploy') }}"
    preview_only: "{{ preview | default(false) }}"
    
  pre_tasks:
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"
    
    - name: Set required variables
      ansible.builtin.set_fact:
        project_name: "{{ lambda_api_infra.project_name }}"
        aws_region_name: "{{ lambda_api_infra.aws.default_region }}"
        waf_project_name: "{{ lambda_api_infra.pulumi.waf_project }}"
        pulumi_path: "{{ inventory_dir }}/../../pulumi"
        scripts_dir: "{{ inventory_dir }}/../../scripts"
        environment_config: "{{ lambda_api_infra.environments[env_name] }}"
        enable_waf: "{{ environment_config.enable_waf | default(false) }}"
        
    - name: Display operation info
      ansible.builtin.debug:
        msg: |
          ==========================================
          WAF Deployment for API Gateway
          ==========================================
          Operation: {{ operation }}
          Environment: {{ env_name }}
          Project: {{ waf_project_name }}
          Region: {{ aws_region_name }}
          WAF Enabled: {{ enable_waf }}
          Preview Only: {{ preview_only }}
          ==========================================
          
    - name: Skip if WAF is not enabled
      ansible.builtin.debug:
        msg: "WAF is not enabled for {{ env_name }} environment. Skipping deployment."
      when: not enable_waf
      
    - name: Check API Gateway deployment
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/{{ project_name }}/{{ env_name }}/api/rest-api-id"
        store_as: "api_check"
        default_value: ""
        ssm_parameter_store_fail_on_missing: false
      when: enable_waf
        
    - name: Verify API Gateway deployment
      ansible.builtin.fail:
        msg: |
          API Gateway is not deployed!
          Please run: ansible-playbook playbooks/lambda/lambda_api_gateway.yml -e "env={{ env_name }}"
      when:
        - enable_waf
        - operation == 'deploy'
        - api_check | default('') | length == 0
  
  roles:
    - aws_setup
    - pulumi_helper
    
  tasks:
    - name: Execute WAF deployment
      ansible.builtin.include_role:
        name: lambda_waf
      vars:
        operation: "{{ operation }}"
      when: enable_waf
        
    - name: Display results
      ansible.builtin.debug:
        msg: |
          ==========================================
          WAF {{ 'Preview' if preview_only else operation | title }} Complete
          ==========================================
          {% if enable_waf %}
          {% if operation == 'deploy' and not preview_only %}
          Status: {{ 'Success' if waf_deployed | default(false) else 'Failed' }}
          
          Optional next steps:
          - WebSocket API: ansible-playbook playbooks/lambda/lambda_websocket.yml -e "env={{ env_name }}"
          - Database: ansible-playbook playbooks/lambda/lambda_database.yml -e "env={{ env_name }}"
          {% elif operation == 'destroy' %}
          WAF has been removed.
          {% endif %}
          {% else %}
          WAF is not enabled for this environment.
          {% endif %}