# ansible/roles/pulumi_helper/tasks/check_stack_exists.yml
# スタックの存在を確認する専用タスク
# 入力: resolved_stack_name, stack_name
# 出力: stack_exists (true/false)

# 共通変数の読み込み（念のため）
- name: Load common variables if needed
  ansible.builtin.include_tasks: common_vars.yml
  when: pulumi_env_export is not defined

# スタックの選択を試みることで存在確認
- name: Try to select stack to check existence
  ansible.builtin.shell: |
    cd {{ pulumi_project_path }}
    {{ pulumi_env_export }}
    {{ pulumi_aws_auth }}
    
    # まず resolved_stack_name で試す
    if sudo -E {{ pulumi_bin_path }} stack select "{{ resolved_stack_name }}" 2>/dev/null; then
      echo "EXISTS"
      exit 0
    fi
    
    # 次に stack_name で試す
    if sudo -E {{ pulumi_bin_path }} stack select "{{ stack_name }}" 2>/dev/null; then
      echo "EXISTS"
      exit 0
    fi
    
    # どちらも失敗したらスタックは存在しない
    echo "NOT_EXISTS"
    exit 1
  register: stack_check
  changed_when: false
  failed_when: false
  when: not ansible_check_mode

- name: Set stack existence based on selection result
  ansible.builtin.set_fact:
    stack_exists: "{{ stack_check.rc == 0 }}"
  when: not ansible_check_mode

- name: Set mock stack existence (check mode)
  ansible.builtin.set_fact:
    stack_exists: false
  when: ansible_check_mode

- name: Display stack existence check result
  ansible.builtin.debug:
    msg: |
      Stack '{{ resolved_stack_name | default(stack_name) }}' exists: {{ stack_exists }}
      Backend: {{ backend_display_name | default(pulumi_backend_type) }}
  when: ansible_verbosity > 0
