# Pulumiスタックの存在を確認するヘルパータスク
# 
# 必要な変数:
#   - pulumi_project_path: Pulumiプロジェクトのパス
#   - pulumi_stack_name: チェックするスタック名
#
# 設定される変数:
#   - pulumi_stack_exists: スタックが存在する場合true
#   - pulumi_stack_check_result: チェック結果の詳細

# 認証処理を実行（既に認証済みの場合はスキップ）
- name: Ensure Pulumi authentication
  ansible.builtin.include_tasks: login.yml
  when: pulumi_authenticated is not defined

# S3バックエンドの場合、プロジェクト別ログイン
- name: Handle S3 backend project login
  ansible.builtin.include_tasks: s3_backend_login.yml
  when: pulumi_backend_type == 's3'

# スタック一覧を取得して存在確認
- name: Check if stack exists
  ansible.builtin.shell: |
    cd {{ pulumi_project_path }}
    {{ pulumi_env_prefix }} && {{ pulumi_sudo_cmd }} stack ls --json 2>/dev/null | jq -r '.[].name' | grep -q "^{{ pulumi_stack_name }}$"
  register: stack_check_result
  failed_when: false
  changed_when: false

# 結果を変数に設定
- name: Set stack existence flag
  ansible.builtin.set_fact:
    pulumi_stack_exists: "{{ stack_check_result.rc == 0 }}"
    pulumi_stack_check_result: "{{ stack_check_result }}"

# デバッグ情報を表示
- name: Display stack check result
  ansible.builtin.debug:
    msg: |
      Stack check result:
      - Project: {{ pulumi_project_path | basename }}
      - Stack name: {{ pulumi_stack_name }}
      - Exists: {{ pulumi_stack_exists }}
  when: pulumi_debug | default(false) | bool