# Pulumiヘルパーの共通変数定義
# 各タスクファイルから必要に応じてインクルードされる

# 共通変数が既に定義されているかチェック
- name: Check if common vars are already defined
  ansible.builtin.set_fact:
    _pulumi_common_vars_loaded: true
  when: _pulumi_common_vars_loaded is not defined

# すべての変数を一度に定義（条件なし）
- name: Define all Pulumi common variables
  when: pulumi_commands is not defined
  block:
    # Pulumiバイナリパス
    - name: Set Pulumi binary path
      ansible.builtin.set_fact:
        pulumi_bin_path: "/root/.pulumi/bin/pulumi"
    
    # バックエンドタイプの判定（環境変数または extra vars から取得）
    - name: Set backend type
      ansible.builtin.set_fact:
        pulumi_backend_type: >-
          {%- if pulumi_backend_type is defined -%}
            {{ pulumi_backend_type }}
          {%- elif ansible_env.PULUMI_BACKEND_TYPE is defined -%}
            {{ ansible_env.PULUMI_BACKEND_TYPE }}
          {%- else -%}
            {{ lookup('env', 'PULUMI_BACKEND_TYPE') | default('cloud', true) }}
          {%- endif -%}
        backend_display_name: >-
          {%- set backend = pulumi_backend_type | default(ansible_env.PULUMI_BACKEND_TYPE | default(lookup('env', 'PULUMI_BACKEND_TYPE') | default('cloud', true))) -%}
          {{ 'S3 Backend' if backend == 's3' else 'Pulumi Cloud' }}
    
    # S3バックエンド設定（常に定義）
    - name: Set S3 backend configuration
      ansible.builtin.set_fact:
        pulumi_s3_backend:
          bucket: >-
            {%- if pulumi_s3_bucket is defined -%}
              {{ pulumi_s3_bucket }}
            {%- elif ansible_env.PULUMI_S3_BUCKET is defined -%}
              {{ ansible_env.PULUMI_S3_BUCKET }}
            {%- else -%}
              {{ lookup('env', 'PULUMI_S3_BUCKET') | default('', true) }}
            {%- endif -%}
          region: >-
            {%- if pulumi_s3_region is defined -%}
              {{ pulumi_s3_region }}
            {%- elif ansible_env.PULUMI_S3_REGION is defined -%}
              {{ ansible_env.PULUMI_S3_REGION }}
            {%- else -%}
              {{ lookup('env', 'PULUMI_S3_REGION') | default('ap-northeast-1', true) }}
            {%- endif -%}
    
    # パスフレーズとアクセストークンの取得
    - name: Set authentication credentials
      ansible.builtin.set_fact:
        _pulumi_passphrase: >-
          {%- if pulumi_config_passphrase is defined -%}
            {{ pulumi_config_passphrase }}
          {%- elif ansible_env.PULUMI_CONFIG_PASSPHRASE is defined -%}
            {{ ansible_env.PULUMI_CONFIG_PASSPHRASE }}
          {%- else -%}
            {{ lookup('env', 'PULUMI_CONFIG_PASSPHRASE') | default('', true) }}
          {%- endif -%}
        _pulumi_access_token: >-
          {%- if pulumi_access_token is defined -%}
            {{ pulumi_access_token }}
          {%- elif ansible_env.PULUMI_ACCESS_TOKEN is defined -%}
            {{ ansible_env.PULUMI_ACCESS_TOKEN }}
          {%- else -%}
            {{ lookup('env', 'PULUMI_ACCESS_TOKEN') | default('', true) }}
          {%- endif -%}
        # 直接環境変数から取得するバージョンも用意
        _pulumi_access_token_direct: "{{ lookup('env', 'PULUMI_ACCESS_TOKEN') }}"
    
    # 環境変数エクスポートコマンド（バックエンドタイプに応じて適切な環境変数のみを設定）
    - name: Set environment export commands
      ansible.builtin.set_fact:
        pulumi_env_export: >-
          {%- if pulumi_backend_type == 's3' -%}
          unset PULUMI_ACCESS_TOKEN;
          export PULUMI_CONFIG_PASSPHRASE="{{ _pulumi_passphrase }}";
          export AWS_REGION={{ pulumi_s3_backend.region }};
          export AWS_DEFAULT_REGION={{ pulumi_s3_backend.region }};
          {%- else -%}
          unset PULUMI_CONFIG_PASSPHRASE;
          unset PULUMI_BACKEND_TYPE;
          export PULUMI_ACCESS_TOKEN="{{ _pulumi_access_token_direct }}";
          {%- endif -%}
        pulumi_aws_auth: >-
          source {{ playbook_dir }}/../../scripts/aws-env.sh > /dev/null 2>&1 || true;
          eval $({{ playbook_dir }}/../../scripts/aws-env.sh) > /dev/null 2>&1 || true;
    
    # Pulumiコマンド実行プレフィックス
    - name: Set Pulumi execution prefix
      ansible.builtin.set_fact:
        pulumi_exec_prefix: >-
          {%- if pulumi_backend_type == 's3' -%}
          unset PULUMI_ACCESS_TOKEN;
          export PULUMI_CONFIG_PASSPHRASE="{{ _pulumi_passphrase }}";
          export AWS_REGION={{ pulumi_s3_backend.region }};
          export AWS_DEFAULT_REGION={{ pulumi_s3_backend.region }};
          {%- else -%}
          unset PULUMI_CONFIG_PASSPHRASE;
          unset PULUMI_BACKEND_TYPE;
          export PULUMI_ACCESS_TOKEN="{{ _pulumi_access_token_direct }}";
          {%- endif -%}
          source {{ playbook_dir }}/../../scripts/aws-env.sh > /dev/null 2>&1 || true;
          eval $({{ playbook_dir }}/../../scripts/aws-env.sh) > /dev/null 2>&1 || true;
          sudo -E {{ pulumi_bin_path }}
    
    # Pulumiコマンド定義
    - name: Set Pulumi commands
      ansible.builtin.set_fact:
        pulumi_commands:
          preview:      "{{ pulumi_exec_prefix }} preview"
          up:           "{{ pulumi_exec_prefix }} up --yes"
          destroy:      "{{ pulumi_exec_prefix }} destroy --yes"
          refresh:      "{{ pulumi_exec_prefix }} refresh --yes"
          stack_output: "{{ pulumi_exec_prefix }} stack output"
          stack_ls:     "{{ pulumi_exec_prefix }} stack ls"
          stack_rm:     "{{ pulumi_exec_prefix }} stack rm --yes"
          config_set:   "{{ pulumi_exec_prefix }} config set"
          build:        "npm run build"
          tsc:          "npx tsc"
    
    # バックエンドURL
    - name: Set backend URL
      ansible.builtin.set_fact:
        pulumi_backend_url: >-
          {%- if pulumi_backend_type == 's3' -%}
            {%- if pulumi_project_path is defined -%}
              s3://{{ pulumi_s3_backend.bucket }}/{{ pulumi_project_name | default(pulumi_project_path | basename) }}
            {%- else -%}
              s3://{{ pulumi_s3_backend.bucket }}/{{ pulumi_project_name | default('default') }}
            {%- endif -%}
          {%- else -%}
            https://app.pulumi.com
          {%- endif -%}
    
    # 外部タスク用の環境変数エクスポートコマンド
    # Jenkins agentロールなど、pulumi_helperの外部から使用する場合のための設定
    - name: Set external command prefix
      ansible.builtin.set_fact:
        pulumi_external_prefix: >-
          cd {{ pulumi_project_path | default('.') }};
          {%- if pulumi_backend_type == 's3' -%}
          unset PULUMI_ACCESS_TOKEN;
          export PULUMI_CONFIG_PASSPHRASE="{{ _pulumi_passphrase }}";
          export AWS_REGION={{ pulumi_s3_backend.region }};
          export AWS_DEFAULT_REGION={{ pulumi_s3_backend.region }};
          {%- else -%}
          unset PULUMI_CONFIG_PASSPHRASE;
          unset PULUMI_BACKEND_TYPE;
          export PULUMI_ACCESS_TOKEN="{{ _pulumi_access_token_direct }}";
          {%- endif -%}
          source {{ playbook_dir }}/../../scripts/aws-env.sh > /dev/null 2>&1 || true;
          eval $({{ playbook_dir }}/../../scripts/aws-env.sh) > /dev/null 2>&1 || true;
