# Pulumiヘルパーの共通変数定義
# 各タスクファイルから必要に応じてインクルードされる

# 共通変数が既に定義されているかチェック
- name: Check if common vars are already defined
  ansible.builtin.set_fact:
    _pulumi_common_vars_loaded: true
  when: _pulumi_common_vars_loaded is not defined

# すべての変数を一度に定義（条件なし）
- name: Define all Pulumi common variables
  when: pulumi_commands is not defined
  block:
    # Pulumiバイナリパス
    - name: Set Pulumi binary path
      ansible.builtin.set_fact:
        pulumi_bin_path: "/root/.pulumi/bin/pulumi"
    
    # バックエンドタイプの判定
    - name: Set backend type
      ansible.builtin.set_fact:
        pulumi_backend_type: "{{ lookup('env', 'PULUMI_BACKEND_TYPE') | default('cloud', true) }}"
        backend_display_name: "{{ 'S3 Backend' if lookup('env', 'PULUMI_BACKEND_TYPE') | default('cloud', true) == 's3' else 'Pulumi Cloud' }}"
    
    # S3バックエンド設定（常に定義）
    - name: Set S3 backend configuration
      ansible.builtin.set_fact:
        pulumi_s3_backend:
          bucket: "{{ lookup('env', 'PULUMI_S3_BUCKET') | default('', true) }}"
          region: "{{ lookup('env', 'PULUMI_S3_REGION') | default('ap-northeast-1', true) }}"
    
    # 環境変数エクスポートコマンド
    - name: Set environment export commands
      ansible.builtin.set_fact:
        pulumi_env_export: >-
          {%- if pulumi_backend_type == 's3' -%}
          export PULUMI_CONFIG_PASSPHRASE="{{ lookup('env', 'PULUMI_CONFIG_PASSPHRASE') }}";
          export AWS_REGION={{ pulumi_s3_backend.region }};
          export AWS_DEFAULT_REGION={{ pulumi_s3_backend.region }};
          {%- else -%}
          export PULUMI_ACCESS_TOKEN="{{ lookup('env', 'PULUMI_ACCESS_TOKEN') }}";
          {%- endif -%}
        pulumi_aws_auth: >-
          source {{ playbook_dir }}/../../scripts/aws-env.sh > /dev/null 2>&1 || true;
          eval $({{ playbook_dir }}/../../scripts/aws-env.sh) > /dev/null 2>&1 || true;
    
    # Pulumiコマンド実行プレフィックス
    - name: Set Pulumi execution prefix
      ansible.builtin.set_fact:
        pulumi_exec_prefix: >-
          {%- if pulumi_backend_type == 's3' -%}
          export PULUMI_CONFIG_PASSPHRASE="{{ lookup('env', 'PULUMI_CONFIG_PASSPHRASE') }}";
          export AWS_REGION={{ pulumi_s3_backend.region }};
          export AWS_DEFAULT_REGION={{ pulumi_s3_backend.region }};
          {%- else -%}
          export PULUMI_ACCESS_TOKEN="{{ lookup('env', 'PULUMI_ACCESS_TOKEN') }}";
          {%- endif -%}
          source {{ playbook_dir }}/../../scripts/aws-env.sh > /dev/null 2>&1 || true;
          eval $({{ playbook_dir }}/../../scripts/aws-env.sh) > /dev/null 2>&1 || true;
          sudo -E {{ pulumi_bin_path }}
    
    # Pulumiコマンド定義
    - name: Set Pulumi commands
      ansible.builtin.set_fact:
        pulumi_commands:
          preview:      "{{ pulumi_exec_prefix }} preview"
          up:           "{{ pulumi_exec_prefix }} up --yes"
          destroy:      "{{ pulumi_exec_prefix }} destroy --yes"
          refresh:      "{{ pulumi_exec_prefix }} refresh --yes"
          stack_output: "{{ pulumi_exec_prefix }} stack output"
          stack_ls:     "{{ pulumi_exec_prefix }} stack ls"
          stack_rm:     "{{ pulumi_exec_prefix }} stack rm --yes"
          config_set:   "{{ pulumi_exec_prefix }} config set"
          build:        "npm run build"
          tsc:          "npx tsc"
    
    # バックエンドURL
    - name: Set backend URL
      ansible.builtin.set_fact:
        pulumi_backend_url: >-
          {%- if pulumi_backend_type == 's3' -%}
            {%- if pulumi_project_path is defined -%}
              s3://{{ pulumi_s3_backend.bucket }}/{{ pulumi_project_name | default(pulumi_project_path | basename) }}
            {%- else -%}
              s3://{{ pulumi_s3_backend.bucket }}/{{ pulumi_project_name | default('default') }}
            {%- endif -%}
          {%- else -%}
            https://app.pulumi.com
          {%- endif -%}
