# Pulumiのデプロイ実行ヘルパータスク

# 認証処理を実行
- name: Ensure Pulumi authentication
  ansible.builtin.include_tasks: login.yml
  when: pulumi_access_token is not defined

- name: Deploy with Pulumi
  block:
    # スタックが選択されているか確認
    - name: Ensure stack is selected
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        {{ pulumi_env_prefix }} && {{ pulumi_sudo_cmd }} stack --show-name || exit 1
      register: current_stack
      changed_when: false
      failed_when: current_stack.rc != 0
      when: not ansible_check_mode
    
    # デプロイを実行
    - name: Run deployment
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        {{ pulumi_commands.up }}
      register: pulumi_up_result
      changed_when: "'No changes' not in pulumi_up_result.stdout"
      when: not ansible_check_mode
    
    # デプロイ結果を表示
    - name: Display deployment results
      ansible.builtin.debug:
        msg: "{{ pulumi_up_result.stdout_lines }}"
      when: not ansible_check_mode and ansible_verbosity > 0
    
    - name: Set success status
      ansible.builtin.set_fact:
        pulumi_deployment_succeeded: true
        
  rescue:
    - name: Display error message
      ansible.builtin.debug:
        msg: |
          ========== Pulumi Deployment Failed ==========
          Failed to deploy Pulumi stack
          Error code: {{ pulumi_up_result.rc | default('unknown') }}
          {% if pulumi_up_result.stdout is defined %}
          Output:
          {{ pulumi_up_result.stdout }}
          {% endif %}
          {% if pulumi_up_result.stderr is defined and pulumi_up_result.stderr %}
          Error:
          {{ pulumi_up_result.stderr }}
          {% endif %}
          ==============================================
    
    - name: Set failure status
      ansible.builtin.set_fact:
        pulumi_deployment_failed: true
    
    # エラー時にAnsibleの実行を停止
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: |
          Pulumi deployment failed. 
          {% if 'TypeScript' in pulumi_up_result.stdout | default('') %}
          TypeScript compilation errors detected. Please fix the code and try again.
          {% elif 'unhandled exception' in pulumi_up_result.stdout | default('') %}
          An unhandled exception occurred during deployment.
          {% else %}
          Check the output above for details.
          {% endif %}

# チェックモード
- name: Mock deploy (check mode)
  ansible.builtin.debug:
    msg: "Would deploy with Pulumi (check mode active)"
  when: ansible_check_mode
