# Pulumiのデプロイ実行ヘルパータスク

- name: Create Pulumi deployment script
  ansible.builtin.copy:
    dest: "/tmp/pulumi_scripts/deploy.sh"
    content: |
      #!/bin/bash
      # Pulumi デプロイスクリプト
      set -e
      
      echo "========================================"
      echo "       PULUMI スタックデプロイ開始      "
      echo "========================================"
      echo "プロジェクトパス: {{ pulumi_project_path }}"
      
      cd {{ pulumi_project_path }}
      
      echo "========================================"
      echo "      AWS 環境変数設定                 "
      echo "========================================"
      source {{ playbook_dir }}/../../scripts/aws-env.sh
      
      echo "========================================"
      echo "      PULUMI デプロイ実行              "
      echo "========================================"
      sudo -E /root/.pulumi/bin/pulumi up --yes
      
      RESULT=$?
      if [ $RESULT -eq 0 ]; then
        echo "========================================"
        echo "      デプロイ成功                     "
        echo "========================================"
      else
        echo "========================================"
        echo "      デプロイ失敗 (終了コード: $RESULT) "
        echo "========================================"
        exit $RESULT
      fi
    mode: '0755'
  when: not ansible_check_mode

- name: Deploy with Pulumi
  ansible.builtin.shell: /tmp/pulumi_scripts/deploy.sh
  register: pulumi_up_result
  changed_when: "'No changes required' not in pulumi_up_result.stdout"
  when: not ansible_check_mode
  
- name: Display Pulumi deployment results
  ansible.builtin.debug:
    msg: "{{ pulumi_up_result.stdout_lines }}"
  when: not ansible_check_mode and pulumi_up_result is defined
  
- name: Mock deploy (check mode)
  ansible.builtin.debug:
    msg: "Would deploy stack with Pulumi (check mode active)"
  when: ansible_check_mode
