# Pulumiスタックの出力を取得するヘルパータスク

# 認証処理を実行（既に認証済みの場合はスキップ）
- name: Ensure Pulumi authentication
  ansible.builtin.include_tasks: login.yml
  when: pulumi_authenticated is not defined

- name: Get stack outputs
  block:
    # verbosity > 1 の場合のみ詳細を表示
    - name: Display operation details
      ansible.builtin.debug:
        msg: "Getting output '{{ output_name | default('all') }}' from {{ pulumi_project_path | basename }}/{{ stack_name | default('current stack') }}"
      when: ansible_verbosity > 1
    
    # スタックが選択されているか確認
    - name: Check current stack selection
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        {{ pulumi_env_prefix }} && {{ pulumi_sudo_cmd }} stack --show-name 2>/dev/null || echo "NO_STACK_SELECTED"
      register: current_stack_check
      changed_when: false
      when: not ansible_check_mode
    
    # スタックが選択されていない場合の処理
    - name: Select stack if not selected
      when:
        - not ansible_check_mode
        - current_stack_check.stdout == "NO_STACK_SELECTED"
      block:
        # stack_nameが指定されている場合
        - name: Select specified stack
          when: stack_name is defined
          ansible.builtin.shell: |
            cd {{ pulumi_project_path }}
            {{ pulumi_env_prefix }}
            
            # まず単純な名前で試す
            if {{ pulumi_sudo_cmd }} stack select {{ stack_name }} 2>/dev/null; then
              echo "Selected: {{ stack_name }}"
            else
              # 失敗したら、スタック名を含むものを検索
              MATCHING_STACK=$({{ pulumi_sudo_cmd }} stack ls --json | jq -r '.[].name | select(endswith("/{{ stack_name }}"))' | head -1)
              if [ -n "$MATCHING_STACK" ]; then
                {{ pulumi_sudo_cmd }} stack select "$MATCHING_STACK"
                echo "Selected: $MATCHING_STACK"
              else
                echo "ERROR: Stack {{ stack_name }} not found"
                exit 1
              fi
            fi
          register: stack_selection_result
          failed_when: stack_selection_result.rc != 0
        
        # stack_nameが未指定の場合（フォールバック）
        - name: Select first available stack
          when: stack_name is not defined
          ansible.builtin.shell: |
            cd {{ pulumi_project_path }}
            {{ pulumi_env_prefix }}
            
            FIRST_STACK=$({{ pulumi_sudo_cmd }} stack ls --json | jq -r '.[0].name // empty')
            if [ -n "$FIRST_STACK" ]; then
              {{ pulumi_sudo_cmd }} stack select "$FIRST_STACK"
              echo "Selected: $FIRST_STACK"
            else
              echo "ERROR: No stacks available"
              exit 1
            fi
          register: fallback_selection_result
          failed_when: fallback_selection_result.rc != 0
    
    # スタック出力を取得
    - name: Get stack output
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        {{ pulumi_env_prefix }}
        
        if [ -n "{{ output_name | default('') }}" ]; then
          # 実際の値のみを取得（最後の行）
          OUTPUT=$({{ pulumi_sudo_cmd }} stack output {{ output_name }} 2>&1)
          if [ $? -eq 0 ]; then
            echo "$OUTPUT" | tail -1
          else
            echo "ERROR: Output '{{ output_name }}' not found"
          fi
        else
          {{ pulumi_sudo_cmd }} stack output --json 2>/dev/null || echo "{}"
        fi
      register: stack_output_result
      changed_when: false
      when: not ansible_check_mode
    
    # エラーチェック
    - name: Check for output errors
      ansible.builtin.fail:
        msg: "Failed to get output '{{ output_name }}' from stack"
      when:
        - not ansible_check_mode
        - stack_output_result.stdout.startswith('ERROR:')
    
    # 成功時のみ、verbosityが高い場合に結果の概要を表示
    - name: Display output summary
      ansible.builtin.debug:
        msg: >-
          {{ output_name | default('Stack outputs') }}: 
          {{ stack_output_result.stdout | truncate(100) if stack_output_result.stdout | length > 100 else stack_output_result.stdout }}
      when: 
        - ansible_verbosity > 1
        - not ansible_check_mode
        - not stack_output_result.stdout.startswith('ERROR:')
      
    - name: Set output success status
      ansible.builtin.set_fact:
        stack_output_succeeded: true
        
  rescue:
    # エラー時は簡潔なメッセージのみ
    - name: Handle output retrieval failure
      ansible.builtin.debug:
        msg: "Failed to get output '{{ output_name | default('all outputs') }}' from {{ pulumi_project_path | basename }}"
      when: ansible_verbosity > 0
    
    - name: Set fallback output
      ansible.builtin.set_fact:
        stack_output_result:
          stdout: "{{ mock_output | default('') }}"
          rc: 1
        stack_output_failed: true

# チェックモード用のモック出力
- name: Set mock outputs (check mode)
  ansible.builtin.set_fact:
    stack_output_result:
      stdout: "{{ mock_output | default('mock-output-for-check-mode') }}"
      rc: 0
  when: ansible_check_mode
