# Pulumiプロジェクト操作の共通ヘルパータスク
# 
# このロールは以下の機能を提供します：
# - Pulumiの設定と認証（Pulumi Cloud / S3バックエンド両対応）
# - スタックの初期化と選択（init_stack.yml）
# - スタックのプレビュー（preview.yml）
# - スタックのデプロイ（deploy.yml）
# - スタックの削除（destroy.yml）
# - スタックの更新（refresh.yml）
# - スタック設定の管理（set_config.yml）
# - スタック出力の取得（get_outputs.yml）
# - TypeScriptプロジェクトのビルド（build.yml）

# AWS環境の準備
- name: Ensure AWS credential scripts are executable
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../../scripts/aws-env.sh"
    mode: '0755'
  register: aws_env_script_perm
  failed_when: false
  no_log: true  # 詳細出力を抑制

- name: Report AWS script permissions update
  ansible.builtin.debug:
    msg: "aws-env.sh スクリプトに実行権限を付与しました"
  when: aws_env_script_perm.changed | default(false)

- name: Ensure AWS credentials are properly set
  ansible.builtin.include_role:
    name: aws_setup

# Pulumiの確認と準備
- name: Check if Pulumi is installed
  ansible.builtin.stat:
    path: "/root/.pulumi/bin/pulumi"
  register: pulumi_check
  failed_when: false

- name: Check root Pulumi installation
  ansible.builtin.stat:
    path: "/root/.pulumi/bin/pulumi"
  register: pulumi_root_check
  failed_when: false
  when: not pulumi_check.stat.exists

- name: Ensure Pulumi is available
  ansible.builtin.fail:
    msg: "Pulumi is not installed. Please run bootstrap setup first."
  when: not pulumi_check.stat.exists and not pulumi_root_check.stat.exists

- name: Set Pulumi path
  ansible.builtin.set_fact:
    pulumi_bin_path: "/root/.pulumi/bin/pulumi"

# Pulumiのバージョン確認
- name: Check Pulumi version
  ansible.builtin.command: "{{ pulumi_bin_path }} version"
  register: pulumi_version
  changed_when: false
  
- name: Display Pulumi version
  ansible.builtin.debug:
    msg: "Using Pulumi version: {{ pulumi_version.stdout }}"
  when: ansible_verbosity > 0

# バックエンドタイプの判定と表示
- name: Determine backend type
  ansible.builtin.set_fact:
    backend_display_name: "{{ 'S3 Backend' if pulumi_backend_type == 's3' else 'Pulumi Cloud' }}"
    
- name: Display backend information
  ansible.builtin.debug:
    msg: |
      ========== Pulumi Backend Configuration ==========
      Backend Type: {{ backend_display_name }}
      {% if pulumi_backend_type == 's3' %}
      S3 Bucket: {{ pulumi_s3_backend.bucket }}
      Region: {{ pulumi_s3_backend.region }}
      Project: {{ pulumi_project_name | default(project_name) | default('default') }}
      {% endif %}
      ==================================================
  when: ansible_verbosity > 0

# パスフレーズの確認（S3バックエンドの場合）
- name: Check for PULUMI_CONFIG_PASSPHRASE in environment (S3 backend)
  ansible.builtin.set_fact:
    pulumi_passphrase_set: "{{ lookup('env', 'PULUMI_CONFIG_PASSPHRASE') | length > 0 }}"
  when: pulumi_backend_type == 's3'

- name: Warn about missing passphrase (S3 backend)
  ansible.builtin.fail:
    msg: |
      ERROR: S3 backend requires PULUMI_CONFIG_PASSPHRASE environment variable.
      Please set it before running this playbook:
      export PULUMI_CONFIG_PASSPHRASE="your-secure-passphrase"
  when: 
    - pulumi_backend_type == 's3'
    - not pulumi_passphrase_set

# Pulumiコマンド定義（バックエンドタイプに応じて環境変数を設定）
- name: Set environment export command based on backend
  ansible.builtin.set_fact:
    pulumi_env_export: >-
      {%- if pulumi_backend_type == 's3' -%}
      export PULUMI_CONFIG_PASSPHRASE="{{ lookup('env', 'PULUMI_CONFIG_PASSPHRASE') }}";
      export AWS_REGION={{ pulumi_s3_backend.region }};
      export AWS_DEFAULT_REGION={{ pulumi_s3_backend.region }};
      {%- else -%}
      export PULUMI_ACCESS_TOKEN="{{ lookup('env', 'PULUMI_ACCESS_TOKEN') }}";
      {%- endif -%}
    
    # AWS認証スクリプトの実行コマンド
    pulumi_aws_auth: >-
      source {{ playbook_dir }}/../../scripts/aws-env.sh > /dev/null 2>&1 || true;
      eval $({{ playbook_dir }}/../../scripts/aws-env.sh) > /dev/null 2>&1 || true;
    
    # Pulumiコマンド実行時の共通プレフィックス
    pulumi_exec_prefix: >-
      {{ pulumi_env_export }}
      {{ pulumi_aws_auth }}
      sudo -E {{ pulumi_bin_path }}

- name: Set Pulumi standard tasks
  ansible.builtin.set_fact:
    pulumi_commands:
      preview:      "{{ pulumi_exec_prefix }} preview"
      up:           "{{ pulumi_exec_prefix }} up --yes"
      destroy:      "{{ pulumi_exec_prefix }} destroy --yes"
      refresh:      "{{ pulumi_exec_prefix }} refresh --yes"
      stack_output: "{{ pulumi_exec_prefix }} stack output"
      stack_ls:     "{{ pulumi_exec_prefix }} stack ls"
      stack_rm:     "{{ pulumi_exec_prefix }} stack rm --yes"
      config_set:   "{{ pulumi_exec_prefix }} config set"
      build:        "npm run build"
      tsc:          "npx tsc"

# 結果変数の初期化
- name: Initialize result variables
  ansible.builtin.set_fact:
    pulumi_deployment_succeeded: false
    pulumi_deployment_failed: false
    pulumi_destroy_failed: false
    pulumi_refresh_failed: false
    pulumi_build_failed: false
    pulumi_config_failed: false
    stack_output_succeeded: false
    stack_output_failed: false
    stack_rm_failed: false
    stack_init_failed: false

# プロジェクトパスが設定されている場合、プロジェクト固有のログインを実行
- name: Login to Pulumi backend for specific project
  ansible.builtin.include_tasks: login.yml
  when: 
    - pulumi_project_path is defined
    - pulumi_project_path | length > 0