# Pulumiプロジェクト操作の共通ヘルパータスク
# 
# このロールは以下の機能を提供します：
# - Pulumiの設定と認証（Pulumi Cloud / S3バックエンド両対応）
# - スタックの初期化と選択（init_stack.yml）
# - スタックのプレビュー（preview.yml）
# - スタックのデプロイ（deploy.yml）
# - スタックの削除（destroy.yml）
# - スタックの更新（refresh.yml）
# - スタック設定の管理（set_config.yml）
# - スタック出力の取得（get_outputs.yml）
# - TypeScriptプロジェクトのビルド（build.yml）

# AWS環境の準備
- name: Ensure AWS credential scripts are executable
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../../scripts/aws-env.sh"
    mode: '0755'
  register: aws_env_script_perm
  failed_when: false
  no_log: true  # 詳細出力を抑制

- name: Report AWS script permissions update
  ansible.builtin.debug:
    msg: "aws-env.sh スクリプトに実行権限を付与しました"
  when: aws_env_script_perm.changed | default(false)

- name: Ensure AWS credentials are properly set
  ansible.builtin.include_role:
    name: aws_setup

# Pulumiの確認と準備
- name: Check if Pulumi is installed
  ansible.builtin.stat:
    path: "/root/.pulumi/bin/pulumi"
  register: pulumi_check
  failed_when: false

- name: Check root Pulumi installation
  ansible.builtin.stat:
    path: "/root/.pulumi/bin/pulumi"
  register: pulumi_root_check
  failed_when: false
  when: not pulumi_check.stat.exists

- name: Ensure Pulumi is available
  ansible.builtin.fail:
    msg: "Pulumi is not installed. Please run bootstrap setup first."
  when: not pulumi_check.stat.exists and not pulumi_root_check.stat.exists

# Pulumiのバージョン確認
- name: Check Pulumi version
  ansible.builtin.command: "/root/.pulumi/bin/pulumi version"
  register: pulumi_version
  changed_when: false
  
- name: Display Pulumi version
  ansible.builtin.debug:
    msg: "Using Pulumi version: {{ pulumi_version.stdout }}"
  when: ansible_verbosity > 0

# 共通変数の読み込み
- name: Load common variables
  ansible.builtin.include_tasks: common_vars.yml

# バックエンドタイプの表示
- name: Display backend information
  ansible.builtin.debug:
    msg: |
      ========== Pulumi Backend Configuration ==========
      Backend Type: {{ backend_display_name }}
      {% if pulumi_backend_type == 's3' %}
      S3 Bucket: {{ pulumi_s3_backend.bucket }}
      Region: {{ pulumi_s3_backend.region }}
      Project: {{ pulumi_project_name | default(project_name) | default('default') }}
      {% else %}
      Using Pulumi Cloud (https://app.pulumi.com)
      {% endif %}
      
      Authentication Status:
      - Access Token: {{ 'Set' if _pulumi_access_token | default('') != '' else 'Not set' }}
      - Config Passphrase: {{ 'Set' if _pulumi_config_passphrase | default('') != '' else 'Not set' }}
      ==================================================
  when: ansible_verbosity > 0

# Pulumi Cloud認証の確認
- name: Check for PULUMI_ACCESS_TOKEN in environment (Pulumi Cloud)
  ansible.builtin.set_fact:
    pulumi_access_token_set: "{{ _pulumi_access_token | default('') | length > 0 }}"
  when: pulumi_backend_type == 'cloud'

- name: Warn about missing access token (Pulumi Cloud)
  ansible.builtin.fail:
    msg: |
      ERROR: Pulumi Cloud requires PULUMI_ACCESS_TOKEN environment variable.
      Please set it before running this playbook:
      
      export PULUMI_ACCESS_TOKEN="pul-YOUR_ACCESS_TOKEN"
      
      To get your access token:
      1. Visit https://app.pulumi.com/account/tokens
      2. Click "Create token"
      3. Copy the token and set it as shown above
      
      Note: Some stacks may also require PULUMI_CONFIG_PASSPHRASE for decryption.
  when: 
    - pulumi_backend_type == 'cloud'
    - not pulumi_access_token_set

# パスフレーズの確認（S3バックエンドの場合）
- name: Check for PULUMI_CONFIG_PASSPHRASE in environment (S3 backend)
  ansible.builtin.set_fact:
    pulumi_passphrase_set: "{{ _pulumi_config_passphrase | default('') | length > 0 }}"
  when: pulumi_backend_type == 's3'

- name: Warn about missing passphrase (S3 backend)
  ansible.builtin.fail:
    msg: |
      ERROR: S3 backend requires PULUMI_CONFIG_PASSPHRASE environment variable.
      Please set it before running this playbook:
      export PULUMI_CONFIG_PASSPHRASE="your-secure-passphrase"
  when: 
    - pulumi_backend_type == 's3'
    - not pulumi_passphrase_set

# S3バケット名の確認（S3バックエンドの場合）
- name: Check for PULUMI_S3_BUCKET in environment (S3 backend)
  ansible.builtin.set_fact:
    pulumi_s3_bucket_set: "{{ pulumi_s3_backend.bucket | length > 0 }}"
  when: pulumi_backend_type == 's3'

- name: Warn about missing S3 bucket (S3 backend)
  ansible.builtin.fail:
    msg: |
      ERROR: S3 backend requires PULUMI_S3_BUCKET environment variable.
      Please set it before running this playbook:
      export PULUMI_S3_BUCKET="your-pulumi-state-bucket-name"
      
      Optional: You can also set the region (default: ap-northeast-1)
      export PULUMI_S3_REGION="your-aws-region"
  when: 
    - pulumi_backend_type == 's3'
    - not pulumi_s3_bucket_set

# パスフレーズの情報表示（Pulumi Cloudでパスフレーズが設定されている場合）
- name: Display passphrase info for Pulumi Cloud
  ansible.builtin.debug:
    msg: |
      INFO: PULUMI_CONFIG_PASSPHRASE is set.
      This will be used for stacks that require passphrase encryption.
  when:
    - pulumi_backend_type == 'cloud'
    - _pulumi_config_passphrase | default('') != ''
    - ansible_verbosity > 0

# 結果変数の初期化
- name: Initialize result variables
  ansible.builtin.set_fact:
    pulumi_deployment_succeeded: false
    pulumi_deployment_failed: false
    pulumi_destroy_failed: false
    pulumi_refresh_failed: false
    pulumi_build_failed: false
    pulumi_config_failed: false
    stack_output_succeeded: false
    stack_output_failed: false
    stack_rm_failed: false
    stack_init_failed: false

# プロジェクトパスが設定されている場合、プロジェクト固有のログインを実行
- name: Login to Pulumi backend for specific project
  ansible.builtin.include_tasks: login.yml
  when: 
    - pulumi_project_path is defined
    - pulumi_project_path | length > 0