# Pulumiプロジェクト操作の共通ヘルパータスク
# 
# このロールは以下の機能を提供します：
# - Pulumiの設定と認証（Pulumi Cloud / S3バックエンド両対応）
# - スタックの初期化と選択（init_stack.yml）
# - スタックのプレビュー（preview.yml）
# - スタックのデプロイ（deploy.yml）
# - スタックの削除（destroy.yml）
# - スタックの更新（refresh.yml）
# - スタック設定の管理（set_config.yml）
# - スタック出力の取得（get_outputs.yml）
# - TypeScriptプロジェクトのビルド（build.yml）

# AWS環境の準備
- name: Ensure AWS credential scripts are executable
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../../scripts/aws-env.sh"
    mode: '0755'
  register: aws_env_script_perm
  failed_when: false
  no_log: true  # 詳細出力を抑制

- name: Report AWS script permissions update
  ansible.builtin.debug:
    msg: "aws-env.sh スクリプトに実行権限を付与しました"
  when: aws_env_script_perm.changed | default(false)

- name: Ensure AWS credentials are properly set
  ansible.builtin.include_role:
    name: aws_setup

# Pulumiの確認と準備
- name: Check if Pulumi is installed
  ansible.builtin.stat:
    path: "/root/.pulumi/bin/pulumi"
  register: pulumi_check
  failed_when: false

- name: Check root Pulumi installation
  ansible.builtin.stat:
    path: "/root/.pulumi/bin/pulumi"
  register: pulumi_root_check
  failed_when: false
  when: not pulumi_check.stat.exists

- name: Ensure Pulumi is available
  ansible.builtin.fail:
    msg: "Pulumi is not installed. Please run bootstrap setup first."
  when: not pulumi_check.stat.exists and not pulumi_root_check.stat.exists

# Pulumiのバージョン確認
- name: Check Pulumi version
  ansible.builtin.command: "/root/.pulumi/bin/pulumi version"
  register: pulumi_version
  changed_when: false
  
- name: Display Pulumi version
  ansible.builtin.debug:
    msg: "Using Pulumi version: {{ pulumi_version.stdout }}"
  when: ansible_verbosity > 0

# 共通変数の読み込み
- name: Load common variables
  ansible.builtin.include_tasks: common_vars.yml

# バックエンドタイプの表示
- name: Display backend information
  ansible.builtin.debug:
    msg: |
      ========== Pulumi Backend Configuration ==========
      Backend Type: {{ backend_display_name }}
      {% if pulumi_backend_type == 's3' %}
      S3 Bucket: {{ pulumi_s3_backend.bucket }}
      Region: {{ pulumi_s3_backend.region }}
      Project: {{ pulumi_project_name | default(project_name) | default('default') }}
      {% endif %}
      ==================================================
  when: ansible_verbosity > 0

# パスフレーズの確認（S3バックエンドの場合）- 環境変数を直接チェック
- name: Check for PULUMI_CONFIG_PASSPHRASE in environment (S3 backend)
  ansible.builtin.shell: |
    if [ -n "${PULUMI_CONFIG_PASSPHRASE}" ]; then
      echo "SET"
    else
      echo "NOT_SET"
    fi
  register: passphrase_check
  changed_when: false
  when: pulumi_backend_type == 's3'

- name: Display passphrase check result
  ansible.builtin.debug:
    msg: "PULUMI_CONFIG_PASSPHRASE status: {{ passphrase_check.stdout | default('NOT_CHECKED') }}"
  when: 
    - pulumi_backend_type == 's3'
    - ansible_verbosity > 0

- name: Warn about missing passphrase (S3 backend)
  ansible.builtin.fail:
    msg: |
      ERROR: S3 backend requires PULUMI_CONFIG_PASSPHRASE environment variable.
      Please set it before running this playbook:
      export PULUMI_CONFIG_PASSPHRASE="your-secure-passphrase"
      
      If you have already set it, try one of these methods:
      1. Set it in the ansible command:
         ansible-playbook -e "ansible_env.PULUMI_CONFIG_PASSPHRASE=$PULUMI_CONFIG_PASSPHRASE" playbook.yml
      
      2. Or use --extra-vars:
         ansible-playbook --extra-vars "pulumi_config_passphrase=$PULUMI_CONFIG_PASSPHRASE" playbook.yml
      
      3. Or set it in your inventory/group_vars/all.yml:
         ansible_env:
           PULUMI_CONFIG_PASSPHRASE: "your-secure-passphrase"
  when: 
    - pulumi_backend_type == 's3'
    - passphrase_check.stdout == 'NOT_SET'

# S3バケット名の確認（S3バックエンドの場合）- 環境変数を直接チェック
- name: Check for PULUMI_S3_BUCKET in environment (S3 backend)
  ansible.builtin.shell: |
    if [ -n "${PULUMI_S3_BUCKET}" ]; then
      echo "SET"
    else
      echo "NOT_SET"
    fi
  register: s3_bucket_check
  changed_when: false
  when: pulumi_backend_type == 's3'

- name: Display S3 bucket check result
  ansible.builtin.debug:
    msg: "PULUMI_S3_BUCKET status: {{ s3_bucket_check.stdout | default('NOT_CHECKED') }}"
  when: 
    - pulumi_backend_type == 's3'
    - ansible_verbosity > 0

- name: Warn about missing S3 bucket (S3 backend)
  ansible.builtin.fail:
    msg: |
      ERROR: S3 backend requires PULUMI_S3_BUCKET environment variable.
      Please set it before running this playbook:
      export PULUMI_S3_BUCKET="your-pulumi-state-bucket-name"
      
      Optional: You can also set the region (default: ap-northeast-1)
      export PULUMI_S3_REGION="your-aws-region"
      
      If you have already set it, try one of these methods:
      1. Set it in the ansible command:
         ansible-playbook -e "ansible_env.PULUMI_S3_BUCKET=$PULUMI_S3_BUCKET" playbook.yml
      
      2. Or use --extra-vars:
         ansible-playbook --extra-vars "pulumi_s3_bucket=$PULUMI_S3_BUCKET" playbook.yml
  when: 
    - pulumi_backend_type == 's3'
    - s3_bucket_check.stdout == 'NOT_SET'

# 結果変数の初期化
- name: Initialize result variables
  ansible.builtin.set_fact:
    pulumi_deployment_succeeded: false
    pulumi_deployment_failed: false
    pulumi_destroy_failed: false
    pulumi_refresh_failed: false
    pulumi_build_failed: false
    pulumi_config_failed: false
    stack_output_succeeded: false
    stack_output_failed: false
    stack_rm_failed: false
    stack_init_failed: false

# プロジェクトパスが設定されている場合、プロジェクト固有のログインを実行
- name: Login to Pulumi backend for specific project
  ansible.builtin.include_tasks: login.yml
  when: 
    - pulumi_project_path is defined
    - pulumi_project_path | length > 0
