# Pulumiスタックをリフレッシュするヘルパータスク

# 認証処理を実行
- name: Ensure Pulumi authentication
  ansible.builtin.include_tasks: login.yml
  when: pulumi_authenticated is not defined

# S3バックエンドの場合、プロジェクト別ログイン
- name: Handle S3 backend project login
  ansible.builtin.include_tasks: s3_backend_login.yml
  when: pulumi_backend_type == 's3'

- name: Refresh Pulumi stack
  block:
    # ロック状態をチェック
    - name: Check for existing locks
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        {{ pulumi_env_prefix }} && {{ pulumi_sudo_cmd }} cancel --yes 2>&1 || true
      register: lock_check
      changed_when: false
      failed_when: false
      when: not ansible_check_mode
    
    - name: Report lock cancellation
      ansible.builtin.debug:
        msg: "Previous lock has been cancelled if it existed"
      when: 
        - not ansible_check_mode
        - "'the stack is currently locked' in lock_check.stderr | default('')"
    
    # スタックが選択されているか確認
    - name: Ensure stack is selected
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        {{ pulumi_env_prefix }} && {{ pulumi_sudo_cmd }} stack --show-name || exit 1
      register: current_stack
      changed_when: false
      failed_when: current_stack.rc != 0
      when: not ansible_check_mode
    
    # リフレッシュを実行
    - name: Run refresh
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        {{ pulumi_commands.refresh }}
      register: pulumi_refresh_result
      changed_when: "'No changes' not in pulumi_refresh_result.stdout"
      when: not ansible_check_mode
      retries: 2
      delay: 5
      until: "'the stack is currently locked' not in pulumi_refresh_result.stderr | default('')"
    
    # リフレッシュ結果を表示
    - name: Display refresh results
      ansible.builtin.debug:
        msg: "{{ pulumi_refresh_result.stdout_lines }}"
      when: not ansible_check_mode and ansible_verbosity > 0
        
  rescue:
    # ロックエラーの場合、再度キャンセルを試みる
    - name: Force cancel lock on failure
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        {{ pulumi_env_prefix }} && {{ pulumi_sudo_cmd }} cancel --yes
      register: force_cancel
      failed_when: false
      changed_when: false
      when: 
        - not ansible_check_mode
        - "'the stack is currently locked' in pulumi_refresh_result.stderr | default('')"
    
    - name: Display error message
      ansible.builtin.debug:
        msg: |
          ========== Pulumi Refresh Failed ==========
          {% if 'the stack is currently locked' in pulumi_refresh_result.stderr | default('') %}
          Stack was locked. Attempted to cancel the lock.
          {% else %}
          Failed to refresh Pulumi stack
          {% endif %}
          {% if pulumi_refresh_result is defined %}
          Error code: {{ pulumi_refresh_result.rc | default('unknown') }}
          {% if pulumi_refresh_result.stdout is defined %}
          Output:
          {{ pulumi_refresh_result.stdout }}
          {% endif %}
          {% if pulumi_refresh_result.stderr is defined and pulumi_refresh_result.stderr %}
          Error:
          {{ pulumi_refresh_result.stderr }}
          {% endif %}
          {% endif %}
          ==========================================
    
    - name: Set failure status
      ansible.builtin.set_fact:
        pulumi_refresh_failed: true
    
    # エラー時にAnsibleの実行を停止
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: |
          Pulumi refresh operation failed.
          {% if 'no stack named' in pulumi_refresh_result.stderr | default('') %}
          No stack is selected. Please select a stack first.
          {% elif 'unauthorized' in pulumi_refresh_result.stderr | default('') | lower %}
          Authentication failed. Please check your Pulumi access token.
          {% else %}
          Check the output above for details.
          {% endif %}

# チェックモード
- name: Mock refresh (check mode)
  ansible.builtin.debug:
    msg: "Would refresh Pulumi stack (check mode active)"
  when: ansible_check_mode
