# Pulumiスタックを削除するヘルパータスク

- name: Remove Pulumi stack
  block:
    # プロジェクト固有のログインを確認（login.ymlで実行済みでない場合）
    - name: Ensure proper backend login
      ansible.builtin.include_tasks: login.yml
      when: _pulumi_login_needed is not defined
    
    # スタック名の検証
    - name: Verify stack name is provided
      ansible.builtin.fail:
        msg: "Required variable 'stack_name' is not defined"
      when: stack_name is not defined or stack_name | length == 0
    
    # スタック名を解決
    - name: Resolve stack name
      ansible.builtin.include_tasks: resolve_stack_name.yml
    
    # 削除対象のスタックを検索
    - name: Find stack to remove
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        export PULUMI_ACCESS_TOKEN="{{ lookup('env', 'PULUMI_ACCESS_TOKEN') }}"
        # スタック名で終わるものを検索
        sudo -E {{ pulumi_bin_path }} stack ls --json | jq -r '.[].name | select(endswith("/{{ stack_name }}") or . == "{{ stack_name }}")' | head -1
      register: found_stack
      changed_when: false
      when: not ansible_check_mode
    
    # スタックが見つからない場合
    - name: Skip if stack not found
      ansible.builtin.debug:
        msg: "Stack '{{ stack_name }}' not found. Skipping removal."
      when: 
        - not ansible_check_mode
        - found_stack.stdout | default('') | trim == ''
    
    # スタックを削除
    - name: Remove stack
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        source {{ playbook_dir }}/../../scripts/aws-env.sh > /dev/null
        eval $({{ playbook_dir }}/../../scripts/aws-env.sh) > /dev/null
        export PULUMI_ACCESS_TOKEN="{{ lookup('env', 'PULUMI_ACCESS_TOKEN') }}"
        sudo -E {{ pulumi_bin_path }} stack rm --yes "{{ found_stack.stdout | trim }}"
      register: stack_rm_result
      changed_when: stack_rm_result.rc == 0
      when: 
        - not ansible_check_mode
        - found_stack.stdout | default('') | trim != ''
    
    - name: Report removal success
      ansible.builtin.debug:
        msg: "Successfully removed stack '{{ found_stack.stdout | trim }}'"
      when: 
        - not ansible_check_mode
        - stack_rm_result is defined
        - stack_rm_result.rc == 0
  
  rescue:
    - name: Display error message
      ansible.builtin.debug:
        msg: "Failed to remove Pulumi stack '{{ stack_name }}'"

# チェックモード
- name: Mock stack removal (check mode)
  ansible.builtin.debug:
    msg: "Would remove Pulumi stack '{{ stack_name }}' (check mode active)"
  when: ansible_check_mode
