# スタック名を解決する専用タスク
# 入力: stack_name (例: dev)
# 出力: resolved_stack_name (例: myorg/jenkins-agent/dev または dev)

# 認証処理を実行（既に認証済みの場合はスキップ）
- name: Ensure Pulumi authentication
  ansible.builtin.include_tasks: login.yml
  when: pulumi_authenticated is not defined

# S3バックエンドのプロジェクト別ログイン（S3バックエンド固定）
- name: Handle S3 backend project login
  ansible.builtin.include_tasks: s3_backend_login.yml

# verbosity > 2 の場合のみ詳細を表示
- name: Display resolution start
  ansible.builtin.debug:
    msg: "Resolving stack name: {{ stack_name }}"
  when: ansible_verbosity > 2

# S3バックエンドのシンプルなスタック名を使用（S3バックエンド固定）
- name: Set simple stack name for S3 backend
  ansible.builtin.set_fact:
    resolved_stack_name: "{{ stack_name }}"

- name: Display S3 backend stack resolution
  ansible.builtin.debug:
    msg: "S3 backend uses simple stack names without organization"
  when: ansible_verbosity > 1

# チェックモード用
- name: Set mock resolved stack name (check mode)
  ansible.builtin.set_fact:
    resolved_stack_name: "{{ stack_name }}"
  when: ansible_check_mode

# 結果はverbosity > 1の場合のみ表示
- name: Display resolution result
  ansible.builtin.debug:
    msg: |
      Resolved stack name: {{ resolved_stack_name }}
      Backend type: S3
  when: ansible_verbosity > 1