# スタック名を解決する専用タスク
# 入力: stack_name (例: dev)
# 出力: resolved_stack_name (例: myorg/jenkins-agent/dev または dev)

# 認証処理を実行（既に認証済みの場合はスキップ）
- name: Ensure Pulumi authentication
  ansible.builtin.include_tasks: login.yml
  when: pulumi_authenticated is not defined

# S3バックエンドの場合、プロジェクト別ログイン
- name: Handle S3 backend project login
  ansible.builtin.include_tasks: s3_backend_login.yml
  when: pulumi_backend_type == 's3'

# verbosity > 2 の場合のみ詳細を表示
- name: Display resolution start
  ansible.builtin.debug:
    msg: "Resolving stack name: {{ stack_name }}"
  when: ansible_verbosity > 2

- name: Read Pulumi.yaml configuration
  ansible.builtin.slurp:
    src: "{{ pulumi_project_path }}/Pulumi.yaml"
  register: pulumi_yaml_content
  when: not ansible_check_mode

- name: Parse Pulumi configuration
  ansible.builtin.set_fact:
    pulumi_config: "{{ pulumi_yaml_content.content | b64decode | from_yaml }}"
  when: not ansible_check_mode

# デバッグ情報はverbosity > 2の場合のみ
- name: Display parsed configuration
  ansible.builtin.debug:
    msg: |
      Pulumi.yaml contents:
      - Name: {{ pulumi_config.name | default('not set') }}
      - Organization: {{ pulumi_config.organization | default('not set') }}
  when: 
    - not ansible_check_mode
    - ansible_verbosity > 2

- name: Set resolved stack name
  ansible.builtin.set_fact:
    resolved_stack_name: >-
      {%- if pulumi_config.organization is defined and pulumi_config.organization -%}
        {{ pulumi_config.organization }}/{{ pulumi_config.name }}/{{ stack_name }}
      {%- else -%}
        {{ stack_name }}
      {%- endif -%}
  when: not ansible_check_mode

- name: Set mock resolved stack name (check mode)
  ansible.builtin.set_fact:
    resolved_stack_name: "{{ stack_name }}"
  when: ansible_check_mode

# 結果はverbosity > 1の場合のみ表示
- name: Display resolution result
  ansible.builtin.debug:
    msg: "Resolved stack name: {{ resolved_stack_name }}"
  when: ansible_verbosity > 1