# スタック名を解決する専用タスク
# 入力: stack_name (例: dev)
# 出力: resolved_stack_name (例: myorg/jenkins-agent/dev または dev)

- name: Display resolution start
  ansible.builtin.debug:
    msg: |
      Resolving stack name...
      Input: {{ stack_name }}
      Project: {{ pulumi_project_path }}

- name: Read Pulumi.yaml configuration
  ansible.builtin.slurp:
    src: "{{ pulumi_project_path }}/Pulumi.yaml"
  register: pulumi_yaml_content
  when: not ansible_check_mode

- name: Parse Pulumi configuration
  ansible.builtin.set_fact:
    pulumi_config: "{{ pulumi_yaml_content.content | b64decode | from_yaml }}"
  when: not ansible_check_mode

- name: Display parsed configuration
  ansible.builtin.debug:
    msg: |
      Pulumi.yaml contents:
      - Name: {{ pulumi_config.name | default('not set') }}
      - Organization: {{ pulumi_config.organization | default('not set') }}
      - Runtime: {{ pulumi_config.runtime | default('not set') }}
  when: 
    - not ansible_check_mode
    - ansible_verbosity > 0

- name: Set resolved stack name
  ansible.builtin.set_fact:
    resolved_stack_name: >-
      {%- if pulumi_config.organization is defined and pulumi_config.organization -%}
        {{ pulumi_config.organization }}/{{ pulumi_config.name }}/{{ stack_name }}
      {%- else -%}
        {{ stack_name }}
      {%- endif -%}
  when: not ansible_check_mode

- name: Set mock resolved stack name (check mode)
  ansible.builtin.set_fact:
    resolved_stack_name: "{{ stack_name }}"
  when: ansible_check_mode

- name: Display resolution result
  ansible.builtin.debug:
    msg: |
      Stack name resolution complete:
      - Input: {{ stack_name }}
      - Resolved: {{ resolved_stack_name }}
      - Organization used: {{ 'Yes' if resolved_stack_name != stack_name else 'No' }}
