# Pulumiスタックの設定値を管理するヘルパータスク

# 認証処理を実行
- name: Ensure Pulumi authentication
  ansible.builtin.include_tasks: login.yml
  when: pulumi_access_token is not defined

- name: Configure Pulumi stack
  block:
    # 必須変数の確認
    - name: Verify required variables
      ansible.builtin.fail:
        msg: "Required variables 'config_key' and 'config_value' are not defined"
      when: config_key is not defined or config_value is not defined
    
    # スタックが選択されているか確認
    - name: Ensure stack is selected
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        {{ pulumi_env_prefix }} && {{ pulumi_sudo_cmd }} stack --show-name || exit 1
      register: current_stack
      changed_when: false
      failed_when: current_stack.rc != 0
      when: not ansible_check_mode
  
    # 設定値をセット
    - name: Set config value
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        source {{ playbook_dir }}/../../scripts/aws-env.sh > /dev/null
        eval $({{ playbook_dir }}/../../scripts/aws-env.sh) > /dev/null
        {{ pulumi_env_prefix }} && {{ pulumi_sudo_cmd }} config set {{ config_key }} "{{ config_value }}" {{ '--secret' if config_secret | default(false) else '' }}
      register: config_result
      changed_when: config_result.rc == 0
      when: not ansible_check_mode
  
    - name: Display config result
      ansible.builtin.debug:
        msg: "Set config '{{ config_key }}' = {{ 'secret' if config_secret | default(false) else config_value }}"
      when: not ansible_check_mode and ansible_verbosity > 0
      
  rescue:
    - name: Display error message
      ansible.builtin.debug:
        msg: |
          ========== Pulumi Config Failed ==========
          Failed to set Pulumi config '{{ config_key }}'
          {% if config_result is defined %}
          Error code: {{ config_result.rc | default('unknown') }}
          {% if config_result.stdout is defined %}
          Output:
          {{ config_result.stdout }}
          {% endif %}
          {% if config_result.stderr is defined and config_result.stderr %}
          Error:
          {{ config_result.stderr }}
          {% endif %}
          {% endif %}
          =========================================
    
    - name: Set failure status
      ansible.builtin.set_fact:
        pulumi_config_failed: true
    
    # エラー時にAnsibleの実行を停止
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: |
          Failed to set Pulumi configuration.
          Key: {{ config_key }}
          {% if 'no stack named' in config_result.stderr | default('') %}
          No stack is selected. Please select a stack first.
          {% elif 'invalid configuration key' in config_result.stderr | default('') %}
          Invalid configuration key format. Use namespace:key format (e.g., aws:region).
          {% else %}
          Check the output above for details.
          {% endif %}

# チェックモード
- name: Mock config set (check mode)
  ansible.builtin.debug:
    msg: "Would set config '{{ config_key | default('unknown') }}' = {{ 'secret' if config_secret | default(false) else config_value | default('unknown') }} (check mode active)"
  when: ansible_check_mode
