# Pulumiスタックの設定値を管理するヘルパータスク

# 認証処理を実行（既に認証済みの場合はスキップ）
- name: Ensure Pulumi authentication
  ansible.builtin.include_tasks: login.yml
  when: pulumi_authenticated is not defined

- name: Configure Pulumi stack
  block:
    # 必須変数の確認
    - name: Verify required variables
      ansible.builtin.fail:
        msg: "Required variables 'config_key' and 'config_value' are not defined"
      when: config_key is not defined or config_value is not defined
    
    # スタックが選択されているか確認（エラー出力を抑制）
    - name: Ensure stack is selected
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        {{ pulumi_env_prefix }} && {{ pulumi_sudo_cmd }} stack --show-name || exit 1
      register: current_stack
      changed_when: false
      failed_when: current_stack.rc != 0
      when: not ansible_check_mode
  
    # 設定値をセット
    - name: Set config value
      ansible.builtin.shell: |
        cd {{ pulumi_project_path }}
        {{ pulumi_env_prefix }} && {{ pulumi_sudo_cmd }} config set {{ config_key }} "{{ config_value }}" {{ '--secret' if config_secret | default(false) else '' }}
      register: config_result
      changed_when: config_result.rc == 0
      when: not ansible_check_mode
  
    # 結果を簡潔に表示
    - name: Report config update
      ansible.builtin.debug:
        msg: "Config set: {{ config_key }} = {{ '***' if config_secret | default(false) else config_value }}"
      when: not ansible_check_mode
      
  rescue:
    - name: Report config failure
      ansible.builtin.debug:
        msg: |
          Failed to set config '{{ config_key }}'
          {% if 'no stack named' in config_result.stderr | default('') %}
          Reason: No stack selected
          {% elif 'invalid configuration key' in config_result.stderr | default('') %}
          Reason: Invalid key format (use namespace:key)
          {% else %}
          Error code: {{ config_result.rc | default('unknown') }}
          {% endif %}
    
    # 詳細はverbosity > 0の場合のみ
    - name: Display error details
      ansible.builtin.debug:
        msg: |
          Error output:
          {{ config_result.stderr | default('No error output') }}
      when: 
        - ansible_verbosity > 0
        - config_result is defined
    
    - name: Set failure status
      ansible.builtin.set_fact:
        pulumi_config_failed: true
    
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Failed to set Pulumi configuration. Run with -v for more details."

# チェックモード
- name: Mock config set (check mode)
  ansible.builtin.debug:
    msg: "Would set config '{{ config_key | default('unknown') }}' (check mode)"
  when: ansible_check_mode
