---
# API Gatewayのデプロイタスク

- name: Display API Gateway deployment information
  ansible.builtin.debug:
    msg: |
      Deploying API Gateway:
      - Project: {{ project_name }}
      - API Gateway Pulumi Project: {{ api_gateway_project_name }}
      - Environment: {{ env_name }}
      - Rate Limit: {{ api_rate_limit }} req/s

# Pulumiデプロイ
- name: Deploy API Gateway with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize API Gateway stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-api-gateway"
        stack_name: "{{ env_name }}"
    
    - name: Configure API Gateway stack - AWS region
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-api-gateway"
        config_key: "aws:region"
        config_value: "{{ aws_region_name }}"

    # Pulumi Configは使用しない（SSMパラメータから取得するため）
    
    # Pulumiプレビュー
    - name: Preview API Gateway deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-api-gateway"
      when: preview_only | default(false) | bool
    
    # Pulumiデプロイ
    - name: Deploy API Gateway stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-api-gateway"
      when: not preview_only | default(false) | bool
    
    # SSMからAPI Gateway情報を取得
    - name: Get API Gateway configuration from SSM
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/{{ project_name }}/{{ env_name }}/api-gateway/config"
        store_as: "api_config_json"
        default_value: "{}"
        ssm_parameter_store_fail_on_missing: false
      when: not preview_only | default(false) | bool
    
    - name: Parse API Gateway configuration
      ansible.builtin.set_fact:
        api_outputs: "{{ api_config_json | from_json }}"
      when: 
        - not preview_only | default(false) | bool
        - api_config_json is defined and api_config_json | length > 0
    
    # デプロイ成功を示す変数設定
    - name: Set API Gateway deployment status
      ansible.builtin.set_fact:
        api_gateway_deployed: true
        api_endpoint: "{{ api_outputs.apiEndpoint | default('N/A') }}"
      when: not preview_only | default(false) | bool
    
    # API Gateway情報の表示
    - name: Display API Gateway deployment summary
      ansible.builtin.debug:
        msg: |
          API Gateway deployment successful:
          - API ID: {{ api_outputs.apiId | default('N/A') }}
          - API Endpoint: {{ api_outputs.apiEndpoint | default('N/A') }}
          - Stage: {{ api_outputs.stageName | default('N/A') }}
          - API Key Required: Yes
          
          To get API key:
          aws ssm get-parameter --name "/{{ project_name }}/{{ env_name }}/api-gateway/api-key" --with-decryption --query 'Parameter.Value' --output text
      when: 
        - api_gateway_deployed is defined and api_gateway_deployed
        - api_outputs is defined
  
  rescue:
    - name: Display error on API Gateway deployment
      ansible.builtin.debug:
        msg: "Failed to deploy API Gateway. See error details above."
      
    - name: Set API Gateway deployment failure
      ansible.builtin.set_fact:
        api_gateway_deployed: false
      
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "API Gateway deployment failed."
