---
# API Gatewayの削除タスク

- name: Display API Gateway destruction information
  ansible.builtin.debug:
    msg: |
      Destroying API Gateway:
      - Project: {{ project_name }}
      - API Gateway Pulumi Project: {{ api_gateway_project_name }}
      - Environment: {{ env_name }}
      - Remove Stack: {{ remove_stacks | default(false) }}

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true

# Pulumiによる削除
- name: Destroy API Gateway with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize API Gateway stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-api-gateway"
        stack_name: "{{ env_name }}"
    
    # Pulumiリソースの削除
    - name: Destroy API Gateway resources with Pulumi
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: destroy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-api-gateway"
    
    # スタック自体の削除（オプション）
    - name: Remove API Gateway stack (if requested)
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: remove_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-api-gateway"
        stack_name: "{{ env_name }}"
      when: remove_stacks | default(false) | bool
    
    # 削除ステータスの設定
    - name: Set API Gateway destruction status on success
      ansible.builtin.set_fact:
        api_gateway_destroyed: true
  
  rescue:
    # エラーハンドリング
    - name: Set API Gateway destruction status on failure
      ansible.builtin.set_fact:
        api_gateway_destroyed: false
    
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to destroy API Gateway. See error details above."

# 削除結果のサマリー表示
- name: Display API Gateway destruction summary
  ansible.builtin.debug:
    msg: |
      API Gateway destruction summary:
      - API Gateway Resources: {{ api_gateway_destroyed | ternary('Destroyed', 'Failed') }}
      - Stack Removed: {{ (remove_stacks | default(false) | bool and api_gateway_destroyed) | ternary('Yes', 'No') }}
