---
# NAT リソースデプロイタスク

- name: Display NAT deployment information
  ansible.builtin.debug:
    msg: "Deploying NAT Infrastructure for {{ env_name }} environment"

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true  # 詳細なログを抑制

# Pulumiデプロイ
- name: Deploy NAT Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize NAT stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-nat"
        stack_name: "{{ env_name }}"
    
    - name: Configure NAT stack - AWS region
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-nat"
        config_key: "aws:region"
        config_value: "{{ aws_region_name }}"

    # Pulumiプレビュー
    - name: Preview NAT deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-nat"
    
    # Pulumiデプロイ
    - name: Deploy NAT stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-nat"
    
    - name: Set NAT deployment status
      ansible.builtin.set_fact:
        nat_deployed: true

    - name: Summary of NAT deployment
      ansible.builtin.debug:
        msg: "NAT Infrastructure deployed successfully for {{ env_name }} environment"
  
  rescue:
    - name: Set NAT deployment status on failure
      ansible.builtin.set_fact:
        nat_deployed: false
      
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to deploy NAT infrastructure. See error details above."
      
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "NAT deployment failed."
