---
# ストレージ（EFS）デプロイタスク

- name: Display storage deployment information
  ansible.builtin.debug:
    msg: "Deploying Storage Infrastructure for {{ env_name }} environment"

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true  # 詳細なログを抑制

# Pulumiデプロイ
- name: Deploy Storage Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize storage stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-storage"
        stack_name: "{{ env_name }}"
    
    # Pulumiプレビュー
    - name: Preview storage deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-storage"
    
    # Pulumiデプロイ
    - name: Deploy storage stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-storage"
    

    - name: Set storage deployment status
      ansible.builtin.set_fact:
        storage_deployed: true

    - name: Summary of storage deployment
      ansible.builtin.debug:
        msg: "Storage Infrastructure deployed successfully for {{ env_name }} environment"
  
  rescue:
    - name: Set storage deployment status on failure
      ansible.builtin.set_fact:
        storage_deployed: false
      
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to deploy storage infrastructure. See error details above."
      
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Storage deployment failed."
