---
# ストレージ（EFS）デプロイタスク

- name: Display storage deployment information
  ansible.builtin.debug:
    msg: |
      Deploying Storage Infrastructure:
      - Project: {{ project_name }}
      - Storage Pulumi Project: {{ storage_project_name }}
      - Network Pulumi Project: {{ network_project_name }}
      - Security Pulumi Project: {{ security_project_name }}
      - Environment: {{ env_name }}

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true  # 詳細なログを抑制
  
- name: Report permission update
  ansible.builtin.debug:
    msg: "aws-env.sh スクリプトに実行権限を付与しました"
  when: aws_env_script_permission.changed

# Pulumiデプロイ
- name: Deploy Storage Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize storage stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-storage"
        stack_name: "{{ env_name }}"
    
    - name: Configure storage stack - AWS region
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-storage"
        config_key: "aws:region"
        config_value: "{{ aws_region_name }}"

    # SSMパラメータの確認
    - name: Get project name from SSM Parameter Store
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/config/project-name"
        store_as: "ssm_project_name"
    
    - name: Get VPC ID from SSM Parameter Store
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/network/vpc-id"
        store_as: "network_vpc_id"
    
    - name: Get EFS security group ID from SSM Parameter Store
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/security/efs-sg-id"
        store_as: "efs_security_group_id"
    
    - name: Display configuration from SSM
      ansible.builtin.debug:
        msg: |
          Using configuration from SSM:
          - Project Name: {{ ssm_project_name }}
          - VPC ID: {{ network_vpc_id }}
          - EFS Security Group ID: {{ efs_security_group_id }}
    
    # Pulumiプレビュー
    - name: Preview storage deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-storage"
    
    # Pulumiデプロイ
    - name: Deploy storage stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-storage"
    
    # デプロイ後に少し待機してスタックが完全に更新されるのを待つ
    - name: Wait for stack outputs to be available
      ansible.builtin.pause:
        seconds: 10
      when: not ansible_check_mode
    
    # EFSファイルシステムIDの取得
    - name: Get EFS file system ID from SSM Parameter Store
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/storage/efs-file-system-id"
        store_as: "efs_file_system_id"
    
    # Jenkins Access Point IDの取得
    - name: Get Jenkins access point ID from SSM Parameter Store
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/storage/jenkins-access-point-id"
        store_as: "jenkins_access_point_id"
    
    # EFS DNS名の取得
    - name: Get EFS DNS name from SSM Parameter Store
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/storage/efs-dns-name"
        store_as: "efs_dns_name"
    
    - name: Set storage facts for use in other playbooks
      ansible.builtin.set_fact:
        storage_deployed: true
        # スタック参照情報も保存
        storage_stack_name: "{{ storage_project_name }}"
      
    - name: Summary of storage deployment
      ansible.builtin.debug:
        msg: |
          Storage Infrastructure Deployed Successfully:
          - EFS File System ID: {{ efs_file_system_id }}
          - EFS DNS Name: {{ efs_dns_name | default('N/A') }}
          - Jenkins Access Point ID: {{ jenkins_access_point_id }}
  
  rescue:
    - name: Set storage deployment status on failure
      ansible.builtin.set_fact:
        storage_deployed: false
      
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to deploy storage infrastructure. See error details above."
      
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Storage deployment failed."
