---
# lambda_ssm_init/tasks/deploy.yml
# Lambda APIインフラのSSMパラメータ初期化デプロイタスク

- name: Set project variables
  ansible.builtin.set_fact:
    lambda_ssm_init_project: "lambda-ssm-init"
    lambda_ssm_init_path: "{{ pulumi_path }}/lambda-ssm-init"
    deployment_timestamp: "{{ ansible_date_time.iso8601 }}"

- name: Display SSM initialization info
  ansible.builtin.debug:
    msg: |
      Lambda SSM Parameter Initialization
      ===================================
      Project: {{ lambda_ssm_init_project }}
      Environment: {{ env_name }}
      Region: {{ aws_region_name }}
      Path: {{ lambda_ssm_init_path }}

- name: Check if Pulumi project exists
  ansible.builtin.stat:
    path: "{{ lambda_ssm_init_path }}/Pulumi.yaml"
  register: pulumi_project_exists

- name: Fail if Pulumi project doesn't exist
  ansible.builtin.fail:
    msg: "Pulumi project not found at {{ lambda_ssm_init_path }}"
  when: not pulumi_project_exists.stat.exists

- name: Install npm dependencies
  ansible.builtin.command:
    cmd: npm install
    chdir: "{{ lambda_ssm_init_path }}"
  register: npm_install
  changed_when: "'added' in npm_install.stdout or 'updated' in npm_install.stdout"

- name: Deploy SSM parameters with Pulumi
  block:
    - name: Build TypeScript
      ansible.builtin.command:
        cmd: npm run build
        chdir: "{{ lambda_ssm_init_path }}"
      register: build_result
      changed_when: true

    - name: Initialize Pulumi stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ lambda_ssm_init_path }}"
        stack_name: "{{ env_name }}"

    - name: Set Pulumi configuration - project name
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ lambda_ssm_init_path }}"
        config_key: "projectName"
        config_value: "{{ project_name }}"

    - name: Set Pulumi configuration - AWS region
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ lambda_ssm_init_path }}"
        config_key: "aws:region"
        config_value: "{{ aws_region_name }}"

    - name: Preview SSM parameter deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ lambda_ssm_init_path }}"
      when: preview_only | default(false) | bool

    - name: Deploy SSM parameters
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ lambda_ssm_init_path }}"
      when: not preview_only | default(false)
      
    - name: Set SSM initialization success fact
      ansible.builtin.set_fact:
        ssm_init_deployed: true
        
  rescue:
    - name: SSM initialization failed
      ansible.builtin.debug:
        msg: "SSM parameter initialization failed: {{ ansible_failed_result.msg | default('Unknown error') }}"
      
    - name: Set SSM initialization failure fact
      ansible.builtin.set_fact:
        ssm_init_deployed: false
    
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "SSM parameter initialization failed"

- name: Wait for SSM parameters to be available
  ansible.builtin.pause:
    seconds: 5
  when: 
    - not preview_only | default(false)
    - ssm_init_deployed | default(false)

- name: Get stack outputs
  ansible.builtin.include_role:
    name: pulumi_helper
    tasks_from: get_outputs
  vars:
    pulumi_project_path: "{{ lambda_ssm_init_path }}"
  when: 
    - not preview_only | default(false)
    - ssm_init_deployed | default(false)

- name: Verify SSM parameter initialization
  ansible.builtin.include_role:
    name: ssm_parameter_store
    tasks_from: get_parameter
  vars:
    parameter_name: "/{{ project_name }}/{{ env_name }}/common/init-complete"
    store_as: "init_complete_check"
    default_value: "false"
    ssm_parameter_store_fail_on_missing: false
  when: not preview_only | default(false)

- name: Display initialization status
  ansible.builtin.debug:
    msg: |
      SSM Parameter Initialization Status
      ==================================
      Initialization: {{ 'Complete' if ssm_init_deployed | default(false) else 'Failed' }}
      {% if pulumi_output is defined %}
      Total Parameters Created: {{ pulumi_output.parametersCreated | default('N/A') }}
      Parameter Prefix: {{ pulumi_output.ssmParameterPrefix | default('N/A') }}
      {% endif %}
  when: 
    - not preview_only | default(false)