---
# Jenkins Agent AMI SSM Parameter Update Playbook
# このプレイブックは、Image Builderで作成された最新のAMI IDを
# SSMパラメータストアに登録します
#
# 使用方法 (ansibleディレクトリから実行):
#   ansible-playbook playbooks/jenkins/misc/update_jenkins_ami_ssm.yml -e "env=dev"
#
# このプレイブックは以下の場合に使用します：
#   - Image Builderのビルドが完了した後
#   - 手動でSSMパラメータを更新したい場合
#   - CI/CDパイプラインから自動実行する場合

- name: Update Jenkins Agent AMI IDs in SSM Parameter Store
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    env_name: "{{ env | default('dev') }}"
  
  pre_tasks:
    - name: Include group_vars/all.yml
      ansible.builtin.include_vars:
        file: "{{ inventory_dir }}/group_vars/all.yml"
    
    - name: Set required variables
      ansible.builtin.set_fact:
        project_name: "{{ infra.project_name }}"
        env: "{{ env_name }}"
    
    - name: Get Pipeline ARNs from SSM
      include_role:
        name: ssm_parameter_store
        tasks_from: get_parameters
      vars:
        parameter_names:
          - "/{{ project_name }}/{{ env }}/agent-ami/pipeline-x86-arn"
          - "/{{ project_name }}/{{ env }}/agent-ami/pipeline-arm-arn"
    
    - name: Set agent_ami_outputs for the role
      ansible.builtin.set_fact:
        agent_ami_outputs:
          imagePipelineX86Arn: "{{ ssm_parameters['/jenkins-infra/' + env + '/agent-ami/pipeline-x86-arn'] }}"
          imagePipelineArmArn: "{{ ssm_parameters['/jenkins-infra/' + env + '/agent-ami/pipeline-arm-arn'] }}"
        wait_for_ami_build: false  # ビルド待機は不要（既に完了している）
  
  tasks:
    - name: Update SSM parameters with latest AMI IDs
      include_role:
        name: jenkins_agent_ami
        tasks_from: update_ssm_parameters