---
# Lambda API NATインフラのデプロイタスク

- name: Display NAT deployment information
  ansible.builtin.debug:
    msg: |
      Deploying Lambda API NAT Infrastructure:
      - Project: {{ project_name }}
      - NAT Pulumi Project: {{ nat_project_name }}
      - Environment: {{ env_name }}
      - High Availability Mode: {{ high_availability_mode }}
      {% if not high_availability_mode %}
      - NAT Instance Type: {{ nat_instance_type }}
      {% endif %}

# Pulumiデプロイ
- name: Deploy NAT Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize NAT stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-nat"
        stack_name: "{{ env_name }}"
    
    - name: Configure NAT stack - AWS region
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-nat"
        config_key: "aws:region"
        config_value: "{{ aws_region_name }}"

    - name: Configure NAT stack - project name
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-nat"
        config_key: "{{ nat_project_name }}:projectName"
        config_value: "{{ project_name }}"

    - name: Configure NAT stack - network stack name
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-nat"
        config_key: "{{ nat_project_name }}:networkStackName"
        config_value: "{{ network_project_name }}"

    - name: Configure NAT stack - security stack name
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-nat"
        config_key: "{{ nat_project_name }}:securityStackName"
        config_value: "{{ security_project_name }}"

    - name: Configure NAT stack - high availability mode
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-nat"
        config_key: "{{ nat_project_name }}:highAvailabilityMode"
        config_value: "{{ high_availability_mode | string | lower }}"

    - name: Configure NAT stack - instance type
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-nat"
        config_key: "{{ nat_project_name }}:natInstanceType"
        config_value: "{{ nat_instance_type }}"
      when: not high_availability_mode

    - name: Configure NAT stack - key name
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-nat"
        config_key: "{{ nat_project_name }}:keyName"
        config_value: "{{ key_name }}"
      when: key_name is defined and key_name

    - name: Configure NAT stack - user data script
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: set_config
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-nat"
        config_key: "{{ nat_project_name }}:userDataScript"
        config_value: "scripts/aws-nat-instance-setup.sh"
    
    # Pulumiプレビュー
    - name: Preview NAT deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-nat"
      when: preview_only | default(false) | bool
    
    # Pulumiデプロイ
    - name: Deploy NAT stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/lambda-nat"
      when: not preview_only | default(false) | bool
    
    # NAT情報の取得
    - name: Get NAT outputs
      ansible.builtin.shell: |
        cd {{ pulumi_path }}/lambda-nat
        export PULUMI_ACCESS_TOKEN="{{ lookup('env', 'PULUMI_ACCESS_TOKEN') }}"
        pulumi stack output --json
      register: nat_outputs_raw
      changed_when: false
      when: not preview_only | default(false) | bool
    
    - name: Parse NAT outputs
      ansible.builtin.set_fact:
        nat_outputs: "{{ nat_outputs_raw.stdout | from_json }}"
      when: 
        - not preview_only | default(false) | bool
        - nat_outputs_raw.stdout is defined
    
    # デプロイ成功を示す変数設定
    - name: Set NAT deployment status
      ansible.builtin.set_fact:
        nat_deployed: true
        nat_type: "{{ 'NAT Gateway' if high_availability_mode else 'NAT Instance' }}"
      when: not preview_only | default(false) | bool
    
    # NAT情報の表示
    - name: Display NAT deployment summary
      ansible.builtin.debug:
        msg: |
          NAT deployment successful:
          - Type: {{ nat_type }}
          {% if high_availability_mode %}
          - NAT Gateway IDs: {{ nat_outputs.natGatewayIds | default([]) | join(', ') }}
          {% else %}
          - NAT Instance ID: {{ nat_outputs.natInstanceId | default('N/A') }}
          - NAT Instance IP: {{ nat_outputs.natInstancePrivateIp | default('N/A') }}
          {% endif %}
      when: 
        - nat_deployed is defined and nat_deployed
        - nat_outputs is defined
  
  rescue:
    - name: Display error on NAT deployment
      ansible.builtin.debug:
        msg: "Failed to deploy Lambda API NAT infrastructure. See error details above."
      
    - name: Set NAT deployment failure
      ansible.builtin.set_fact:
        nat_deployed: false
      
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Lambda API NAT deployment failed."
