# Pulumiヘルパーのデフォルト変数
pulumi_base_path: "{{ playbook_dir }}/../../pulumi"

# バックエンド設定
# all.ymlから読み込むか、デフォルト値を使用
pulumi_backend_type: "{{ pulumi.backend_type | default('s3') }}"

# Pulumi Cloud設定
pulumi_cloud_url: "{{ pulumi.cloud.url | default('https://api.pulumi.com') }}"

# S3バックエンド設定
# all.ymlから読み込むか、CloudFormationで作成されたバケットを自動検出
pulumi_s3_bucket: "{{ pulumi.s3.bucket | default(pulumi_state_bucket_name | default('')) }}"
pulumi_s3_region: "{{ pulumi.s3.region | default('ap-northeast-1') }}"
# S3バックエンドのパスフレーズは環境変数PULUMI_CONFIG_PASSPHRASEから取得

# ログ出力の制御
pulumi_helper_verbose: "{{ ansible_verbosity > 0 }}"
pulumi_helper_debug: "{{ ansible_verbosity > 1 }}"

# セパレータのスタイル
pulumi_helper_separator: "=========================================="
pulumi_helper_separator_short: "----------"

# デフォルトのタイムアウト設定
pulumi_operation_timeout: 600  # 10分
pulumi_operation_poll: 10      # 10秒ごとにポーリング
