# Pulumiヘルパーのデフォルト変数
pulumi_base_path: "{{ inventory_dir }}/../../pulumi"

# S3バックエンド設定（S3バックエンド固定）
# S3バケット名はSSMパラメータストアから自動取得されるため、デフォルトは空
pulumi_s3_bucket: ""
pulumi_s3_region: "{{ aws_region }}"
# S3バックエンドのパスフレーズは環境変数PULUMI_CONFIG_PASSPHRASEから取得

# ログ出力の制御
pulumi_helper_verbose: "{{ ansible_verbosity > 0 }}"
pulumi_helper_debug: "{{ ansible_verbosity > 1 }}"

# セパレータのスタイル
pulumi_helper_separator: "=========================================="
pulumi_helper_separator_short: "----------"

# デフォルトのタイムアウト設定
pulumi_operation_timeout: 600  # 10分
pulumi_operation_poll: 10      # 10秒ごとにポーリング
