# Pulumiヘルパーのデフォルト変数
pulumi_base_path: "{{ playbook_dir }}/../../pulumi"

# バックエンド設定
pulumi_backend_type: "cloud"  # "cloud" または "s3"

# Pulumi Cloud設定（デフォルト）
pulumi_cloud_url: "https://api.pulumi.com"

# S3バックエンド設定
pulumi_s3_bucket: "pulumi-state-bucket"
pulumi_s3_region: "ap-northeast-1"
# S3バックエンドのパスフレーズは環境変数PULUMI_CONFIG_PASSPHRASEから取得

# ログ出力の制御
pulumi_helper_verbose: "{{ ansible_verbosity > 0 }}"
pulumi_helper_debug: "{{ ansible_verbosity > 1 }}"

# セパレータのスタイル
pulumi_helper_separator: "=========================================="
pulumi_helper_separator_short: "----------"

# デフォルトのタイムアウト設定
pulumi_operation_timeout: 600  # 10分
pulumi_operation_poll: 10      # 10秒ごとにポーリング
