# lambda_waf ロールのデフォルト変数

# パスがプレイブックからの相対パスになるよう修正
scripts_dir: "{{ inventory_dir }}/../../scripts"
pulumi_path: "{{ inventory_dir }}/../../pulumi"

# 環境名のデフォルト値
env_name: "dev"

# WAF設定のデフォルト値
ip_whitelist_source: "secretsManager"
rate_limit_per_5min: 2000
block_duration_seconds: 240

# プレビューモード
preview_only: false
