---
# コントローラーデプロイタスク

- name: Display controller deployment information
  ansible.builtin.debug:
    msg: "Deploying Jenkins Controller Infrastructure for {{ env_name }} environment"

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true  # 詳細なログを抑制

# Pulumiデプロイ
- name: Deploy Controller Infrastructure with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize controller stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-controller"
        stack_name: "{{ env_name }}"
    
    # Pulumiプレビュー
    - name: Preview controller deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-controller"
    
    # Pulumiデプロイ
    - name: Deploy controller stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-controller"
    
    # Jenkinsインスタンス情報の取得（後続処理で必要）
    - name: Get Jenkins instance ID from SSM Parameter Store
      ansible.builtin.include_role:
        name: ssm_parameter_store
        tasks_from: get_parameter
      vars:
        parameter_name: "/jenkins-infra/{{ env_name }}/controller/instance-id"
        store_as: "jenkins_instance_id"
    
    # SSMエージェントが準備完了になるまで待機
    - name: Wait for SSM agent to be ready on Jenkins instance
      ansible.builtin.include_role:
        name: aws_cli_helper
        tasks_from: wait_for_ssm
      vars:
        instance_id: "{{ jenkins_instance_id }}"
        max_wait_time: 300  # 5分間待機
        check_interval: 10  # 10秒ごとにチェック
        aws_region: "{{ aws_region }}"
      when: jenkins_instance_id is defined

    - name: Summary of controller deployment
      ansible.builtin.debug:
        msg: "Jenkins Controller Infrastructure deployed successfully (Instance: {{ jenkins_instance_id }})"
  
  rescue:
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to deploy controller infrastructure. See error details above."

    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Controller deployment failed."
