---
# セキュリティグループデプロイタスク

- name: Display security deployment information
  ansible.builtin.debug:
    msg: "Deploying Security Groups for {{ env_name }} environment"

# ファイル権限設定
- name: Ensure aws-env.sh has execute permissions
  ansible.builtin.file:
    path: "{{ scripts_dir }}/aws/aws-env.sh"
    mode: '0755'
  register: aws_env_script_permission
  no_log: true  # 詳細なログを抑制

# Pulumiデプロイ
- name: Deploy Security Groups with Pulumi
  block:
    # Pulumiヘルパータスクを呼び出す
    - name: Initialize security stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: init_stack
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-security"
        stack_name: "{{ env_name }}"
    
    # Pulumiプレビュー
    - name: Preview security deployment
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: preview
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-security"
    
    # Pulumiデプロイ
    - name: Deploy security stack
      ansible.builtin.include_role:
        name: pulumi_helper
        tasks_from: deploy
      vars:
        pulumi_project_path: "{{ pulumi_path }}/jenkins-security"
    
    
    - name: Set security deployment status
      ansible.builtin.set_fact:
        security_deployed: true

    - name: Summary of security groups deployment
      ansible.builtin.debug:
        msg: "Security Groups deployed successfully for {{ env_name }} environment"
  
  rescue:
    - name: Set security deployment status on failure
      ansible.builtin.set_fact:
        security_deployed: false
      
    - name: Display error
      ansible.builtin.debug:
        msg: "Failed to deploy security groups. See error details above."
      
    - name: Fail the playbook
      ansible.builtin.fail:
        msg: "Security deployment failed."
